// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="about-cold-warm-migration_{context}"]
= About cold and warm migration

{project-short} supports cold migration from:

* VMware vSphere
* {rhv-full} ({rhv-short})
* {osp}
* Remote {virt} clusters

{project-short} supports warm migration from VMware vSphere and from {rhv-short}.

[id="cold-migration_{context}"]
== Cold migration

Cold migration is the default migration type. The source virtual machines are shut down while the data is copied.

[id="warm-migration_{context}"]
== Warm migration

Most of the data is copied during the _precopy_ stage while the source virtual machines (VMs) are running.

Then the VMs are shut down and the remaining data is copied during the _cutover_ stage.

.Precopy stage

The VMs are not shut down during the precopy stage.

The VM disks are copied incrementally by using link:https://kb.vmware.com/s/article/1020128[changed block tracking (CBT)] snapshots. The snapshots are created at one-hour intervals by default. You can change the snapshot interval by updating the `forklift-controller` deployment.

[IMPORTANT]
====
You must enable CBT for each source VM and each VM disk.

A VM can support up to 28 CBT snapshots. If the source VM has too many CBT snapshots and the `Migration Controller` service is not able to create a new snapshot, warm migration might fail. The `Migration Controller` service deletes each snapshot when the snapshot is no longer required.
====

The precopy stage runs until the cutover stage is started manually or is scheduled to start.

.Cutover stage

The VMs are shut down during the cutover stage and the remaining data is migrated. Data stored in RAM is not migrated.

You can start the cutover stage manually by using the {project-short} console or you can schedule a cutover time in the `Migration` manifest.

[id="warm-migration-versus-cold-migration"_{context}]
== Advantages and disadvantages of cold and warm migrations

[id="warm-cold-migration-overview_{context}"]
=== Overview

Both cold migration and warm migration have advantages and disadvantages, as described in the table that follows:

[cols="1,1,1",options="header"]
.Advantages and disadvantages of cold and warm migrations

|===
| |Duration |VM downtime

|Cold migration
|Minimal
|High

|Warm migration
|Longer and variable
|Minimal
|===

[id="warm-cold-migration-detailed_{context}"]
=== Detailed description

The table that follows offers a more detailed description of the advantages and disadvantages of each type of migration. It assumes that you have installed Red Hat Enterprise Linux (RHEL) 9 on the {ocp} platform on which you installed {project-short}.

[cols="1,1,1",options="header"]
.Detailed description of advantages and disadvantages

|===
| |Cold migration |Warm migration

|*Duration*
| Each block is copied only once, making the duration of the migration shorter.
| A block might be copied in more than one snapshot. {project-short} ensures that only the most recent snapshot is used, but eliminating duplicate snapshots adds time to the duration of the migration.

|*Fail fast*
| Each block is converted to be compatible with {ocp-short} and, if the conversion is successful, the block is transferred. If a block cannot be converted, the migration fails immediately.
| All blocks are transferred before any are converted. This means that it takes longer for a warm migration to fail than a cold migration, because a cold migration fails before all blocks are transferred.

|*Tools*
| {project-short} only.
| {project-short} and CDI from {virt}

|*VM downtime*
| Longer than with a warm migration because in a cold migration, all the source VMs are shut down and then the data is transferred.
| Shorter than with a cold migration, because the disks are transferred, and then shut down before being converted.

|*Parallelism*
| Disks must be transferred sequentially.
| Disks can be transferred in parallel, using different pods.
|===

[NOTE]
====
The preceding table describes the situation for VMs that are running, because the main benefit of warm migration is the reduced downtime, and there is no reason to initiate warm migration for VMs that are down. However, performing warm migration for VMs that are down is not the same as cold migration, even when {project-short} uses `virt-v2v` and RHEL 9. For VMs that are down, {project-short} transfers the disks using CDI, unlike in cold migration.
====









