// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_advanced-migration-options.adoc

:_mod-docs-content-type: CONCEPT
[id="about-hooks-for-migration-plans_{context}"]
= About hooks for {project-short} migration plans

[role="_abstract"]
You can add hooks to an {project-first} migration plan to perform automated operations on a VM, either before or after you migrate it.

You can add hooks to {project-first} migration plans by using either the {project-short} CLI or the {project-short} user interface, which is located in the {ocp} web console.

Hook types::

* Pre-migration hooks: Hooks that perform operations on a VM that is located on a provider. This prepares the VM for migration.
* Post-migration hooks: Hooks that perform operations on a VM that has migrated to {virt}.

Hook configuration::

* Default hook image: The default hook image for an {project-short} hook is `quay.io/kubev2v/hook-runner`. The image is based on the Ansible Runner image with the addition of `python-openshift` to provide Ansible Kubernetes resources and a recent `oc` binary.
* Hook execution: An Ansible Playbook that is provided as part of a migration hook is mounted into the hook container as a `ConfigMap`. The hook container is run as a job on the relevant cluster in the `openshift-mtv` namespace. When you add a hook, you must specify the name of the hook and whether it is a pre-migration hook or a post-migration hook.
* Service account: You can optionally specify a service account when adding a hook. When you add a hook by using the {ocp} web console, you can specify the service account name in the *Service account* field when creating or editing the migration plan. When you add a hook by using the CLI, you can specify the service account in the `Hook` CR. If you specify a service account, it must have the appropriate RBAC permissions to manage cluster resources and at least write access for the `openshift-mtv` namespace where hooks execute.

[IMPORTANT]
====
For a hook to run on a VM, the VM must be started and available using SSH.
====
