// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_advanced-migration-options.adoc

:_mod-docs-content-type: CONCEPT
[id="about-rego-files_{context}"]
= About Rego files

[role="_abstract"]
Validation rules are written in Rego, the Open Policy Agent (OPA) native query language. The rules are stored as `.rego` files in the `/usr/share/opa/policies/io/konveyor/forklift/<provider>` directory of the `Validation` pod.

Each validation rule is defined in a separate `.rego` file and tests for a specific condition. If the condition evaluates as `true`, the rule adds a `{“category”, “label”, “assessment”}` hash to the `concerns`. The `concerns` content is added to the `concerns` key in the inventory record of the VM. The web console displays the content of the `concerns` key for each VM in the provider inventory.

The following `.rego` file example checks for distributed resource scheduling enabled (`has_drs_enabled`) in the cluster of a VMware VM:

[source,terminal]
----
package io.konveyor.forklift.vmware

has_drs_enabled {
    input.host.cluster.drsEnabled
}

concerns[flag] {
    has_drs_enabled
    flag := {
        "category": "Information",
        "label": "VM running in a DRS-enabled cluster",
        "assessment": "Distributed resource scheduling is not currently supported by OpenShift Virtualization. The VM can be migrated but it will not have this feature in the target environment."
    }
}
----
where:

`package io.konveyor.forklift.vmware`::
Is the package namespace in this example, The package namespaces are `io.konveyor.forklift.vmware` for VMware and `io.konveyor.forklift.ovirt` for {rhv-full}.

`input.host.cluster.drsEnabled`::
Is the query parameter in this example. Query parameters are based on the `input` key of the `Validation` service JSON.

For information about Rego queries and rules and examples of Rego rules, see the following resources:

* link:https://www.openpolicyagent.org/docs/latest/policy-language/[Policy Language] in the _Open Policy Agent_ documentation.
* link:https://github.com/kubev2v/forklift/tree/main/validation#opa-rules-files[OPA Rules Files] in the `forklift` documentation.
* link:https://github.com/kubev2v/forklift/tree/main/validation/policies/io/konveyor/forklift/vmware[VMware .rego files] in the `forklift` repository.

