// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="about-cold-warm-migration_{context}"]
= About cold and warm migration

{project-short} supports cold migration from:

* VMware vSphere
* {rhv-full} ({rhv-short})
* {osp}
* Remote {virt} clusters

{project-short} supports warm migration from VMware vSphere and from {rhv-short}.

[id="cold-migration_{context}"]
== Cold migration

Cold migration is the default migration type. The source virtual machines are shut down while the data is copied.

[id="warm-migration_{context}"]
== Warm migration

Most of the data is copied during the _precopy_ stage while the source virtual machines (VMs) are running.

Then the VMs are shut down and the remaining data is copied during the _cutover_ stage.

.Precopy stage

The VMs are not shut down during the precopy stage.

The VM disks are copied incrementally using link:https://kb.vmware.com/s/article/1020128[changed block tracking (CBT)] snapshots. The snapshots are created at one-hour intervals by default. You can change the snapshot interval by updating the `forklift-controller` deployment.

[IMPORTANT]
====
You must enable CBT for each source VM and each VM disk.

A VM can support up to 28 CBT snapshots. If the source VM has too many CBT snapshots and the `Migration Controller` service is not able to create a new snapshot, warm migration might fail. The `Migration Controller` service deletes each snapshot when the snapshot is no longer required.
====

The precopy stage runs until the cutover stage is started manually or is scheduled to start.

.Cutover stage

The VMs are shut down during the cutover stage and the remaining data is migrated. Data stored in RAM is not migrated.

You can start the cutover stage manually by using the {project-short} console or you can schedule a cutover time in the `Migration` manifest.
