// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_mapping-networks-storage.adoc

:_mod-docs-content-type: CONCEPT
[id="about-network-maps_{context}"]
= About network maps in migration plans

[role="_abstract"]
Create network maps in {project-first} to map source networks to {virt} networks. You can create two types of network map: maps for a specific migration plan and maps for use by any migration plan.

Plan-specific maps::

Plan-specific maps are owned by that plan. You can create this kind of map in the *Network maps* step of the *Plan creation wizard*.

Ownerless maps::

Maps created for use by any migration plan are to said to be _ownerless_. You can create this kind of map in the *Network maps* page of the *Migration for Virtualization* section of the {virt} web console.
+
You, or anyone working in the same project, can use ownerless maps when creating a migration plan in the *Plan creation wizard*. When you choose one of these unowned maps for a migration plan, {project-short} creates a copy of the map and defines your migration plan as the _owner of that copy_. Any changes you make to the copy do not affect the original map, nor do they apply to any other plan that uses a copy of the map.

Both types of network map for a project are shown in the *Network maps* page, but there is an important difference in the information displayed in the *Owner* column of that page for each:

* Maps created in the *Network maps* step of the *Plan creation wizard* are shown as being owned by the migration plan.
* Maps created in the *Network maps* page of the *Migration for Virtualization* section of the {virt} web console are shown as having no owner.




