// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="about-api-hooks-in-migration-plans_{context}"]
= API-based hooks for {project-short} migration plans

You can use migration hooks to perform automated operations on a VM either before or after you migrate it.

* Hooks that perform operations on VMs before migration are called _pre-migration_ hooks.  A pre-migration hook is performed on a VM that is located on the provider and prepares the VM for migration.

* Hooks that perform operations on VMs after migration are called _post-migration_ hooks. A post-migration hook is performed on a VM after it has been migrated to {virt}.

You can add hooks to a migration plan using either the {project-first} CLI or the {project-short} UI.

[id="default-hook-image_{context}"]
== Default hook image
The default hook image for an {project-short} hook is`quay.io/konveyor/hook-runner`. The image is based on the Ansible Runner image with the addition of `python-openshift` to provide Ansible Kubernetes resources and a recent `oc` binary.

[id="hook-execution_{context}"]
== Hook execution
An Ansible playbook that is provided as part of a migration hook is mounted into the hook container as a `ConfigMap`. The hook container is run as a job on the desired cluster, using the default `ServiceAccount` in the `konveyor-forklift` namespace.


When you add a hook, you must specify the namespace where the hook CR is located, the name of the hook, and specify whether the hook is a pre-migration hook or a post-migration hook.

[IMPORTANT]
====
In order for a hook to run on a VM, the VM must be started and available via SSH.
====

The illustration that follows shows the general process of using a migration hook. Specific procedures are described in TBD1 and TBD2.

Figure

Process:


. Input your Ansible hook and credentials.

.. Input an Ansible hook image to the {project-short} controller using either the UI or the CLI.
+
* In the UI, you specify the `ansible-runner` and enter the `playbook.yml` that contains the hook.
* In the CLI, you input the hook image, which specifies the playbook that runs the hook.

.. If you need additional data to run the playbook inside the pod, such as SSH data, create a Secret that contains credentials for the VM. The Secret is not mounted to the pod, but is called by the playbook.
+
[NOTE]
====
This Secret is not the same as the `Secret` CR that contains the credentials of your source provider.
====

. The {project-short} controller creates the `configmap`, which contains:

** `workload.yml`, which contains information about the VMs.
** `playbook.yml`, the raw string playbook you want to execute.
** `plan.yml`, which is the `Plan CR`.
+
The `configmap` contains the name of the VM and instructs the playbook what to do.

. The {project-short} controller does the following:

** Creates a job that starts the user specified image.
** Mounts the `configmap` to the container.

+
The Ansible hook imports the Secret that the user previously
. The job runs a prehook or a posthook as follows:

** For a prehook, the job logs into the VMs on the source provider using SSH and runs the prehook.
** For a posthook, the job logs into the VMs on {virt} using SSH and runs the posthook.








