// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="about-storage-copy-offload_{context}"]
= About migrating virtual machines by using storage copy offload

You can migrate {vmw} virtual machines (VMs) that are in a storage array network (SAN) more efficiently by using a method called _storage copy offload_. You use this method to accelerate migration speed and reduce the load on your network. 

{vmw}'s vSphere Storage APIs-Array Integration (VAAI) includes a command named `XCOPY`, which lets you copy data inside a SAN more efficiently than copying the data over a network.

{product-first} 2.10.0 leverages this command as the basis for storage copy offload, allowing you to delegate cloning your VMs' data to the storage hardware instead having it to transit it between {project-short} and {virt}. 

This feature is available as a Development Preview for {project-first} 2.10.0 for cold migration only and is not available for shared disks. 

// Create development preview snippet and insert here. 

== How it works 

Without storage copy offload, {project-short} migrates a virtual disk as follows:

. {project-short} reads the disk from the source storage.
. {project-short} sends the data over a network to {virt}.
. {virt} writes the data to its storage. 
+
This method can be slow and consume significant network and host resources. With storage copy offload, the process is streamlined:

. {project-short} initiates a disk transfer request.
. Instead of sending the data, {project-short} instructs the storage array to perform a direct copy from the source storage to {virt}.
+
The storage array handles the cloning of the VM disk internally, often at a much higher speed than a network-based transfer.

The Forklift project, a key component of MTV, includes a specialized `vsphere-xcopy-volume-populator` that directly interacts with VMware's VAAI. This allows MTV to trigger the high-speed, array-level data copy operation for supported storage systems.

You can use storage copy offload for migrating VMs by using either the UI or the CLI. 

[role="_additional-resources"]
.Additional resources

* xref:running-storage-copy-offload-ui_vmware[Storage copy offload in the UI]
* xref:running-storage-copy-offload-cli_vmware[Storage copy offload in the CLI]