// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_advanced-migration-options.adoc

:_mod-docs-content-type: PROCEDURE
[id="accessing-default-validation-rules_{context}"]
= Checking the default validation rules

[role="_abstract"]
Before you create a custom rule, you must check the default rules of the `Validation` service to ensure that you do not create a rule that redefines an existing default value.

Example: If a default rule contains the line `default valid_input = false` and you create a custom rule that contains the line `default valid_input = true`, the `Validation` service will not start.

.Procedure

. Connect to the terminal of the `Validation` pod:
+
[source,terminal,subs="attributes+"]
----
$ {oc} rsh <validation_pod>
----

. Go to the OPA policies directory for your provider:
+
[source,terminal]
----
$ cd /usr/share/opa/policies/io/konveyor/forklift/<provider>
----
+
where:

provider::
Specifies the provider. Valid options: `vmware` or `ovirt`.

. Search for the default policies:
+
[source,terminal]
----
$ grep -R "default" *
----
