// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_troubleshooting-migration.adoc

:_mod-docs-content-type: PROCEDURE
[id="accessing-logs-cli_{context}"]
= Accessing logs and custom resource information from the command line

[role="_abstract"]
You can access logs and information about custom resources (CRs) from the command line by using the `must-gather` tool. You must attach a `must-gather` data file to all customer cases.

You can gather data for a specific namespace, a completed, failed, or canceled migration plan, or a migrated virtual machine (VM) by using the filtering options.

[NOTE]
====
If you specify a non-existent resource in the filtered `must-gather` command, no archive file is created.
====

.Prerequisites

* You must be logged in to the {virt} cluster as a user with the `cluster-admin` role.
* You must have the {ocp-doc}/cli_tools/openshift-cli-oc#openshift-cli-oc[{ocp} CLI (oc)] installed.

.Procedure

. Navigate to the directory where you want to store the `must-gather` data.
. Run the `oc adm must-gather` command:
+
[source,terminal,subs="attributes+"]
----
$ {oc} adm must-gather --image={must-gather}
----
+
The data is saved as `/must-gather/must-gather.tar.gz`. You can upload this file to a support case on the link:https://access.redhat.com/[Red Hat Customer Portal].

. Optional: Run the `oc adm must-gather` command with the following options to gather filtered data:

* Namespace:
+
[source,terminal,subs="attributes+"]
----
$ {oc} adm must-gather --image={must-gather} \
  -- NS=<namespace> /usr/bin/targeted
----

* Migration plan:
+
[source,terminal,subs="attributes+"]
----
$ {oc} adm must-gather --image={must-gather} \
  -- PLAN=<migration_plan> /usr/bin/targeted
----

* Virtual machine:
+
[source,terminal,subs="attributes+"]
----
$ {oc} adm must-gather --image={must-gather} \
  -- VM=<vm_name> NS=<namespace> /usr/bin/targeted
----
+
where:

`<vm_name>`::
Specifies the VM _name_, not the VM ID, as it appears in the `Plan` CR.
