// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="adding-vddk-to-mtv_{context}"]
= Creating a VDDK image and adding it to a config map

{the} {project-first} uses the VMware Virtual Disk Development Kit (VDDK) SDK to transfer virtual disks.

You must download VDDK, build a VDDK image, push it to a private image registry, and then add the image to the `v2v-vmware` config map.

[NOTE]
====
Storing the VDDK image in a public registry might violate the VMware license terms.
====

.Prerequisites

* link:https://docs.openshift.com/container-platform/{ocp-version}/registry/configuring_registry_storage/configuring-registry-storage-baremetal.html[{ocp} image registry] or a secure link:https://docs.openshift.com/container-platform/{ocp-version}/registry/registry-options.html[external registry].
* `podman` installed.
* If you are using an external registry, {virt} must be able to access it.

.Procedure

. Create and navigate to a temporary directory:
+
[source,terminal]
----
$ mkdir /tmp/<dir_name> && cd /tmp/<dir_name>
----

. In a browser, navigate to the link:https://code.vmware.com/home[VMware code] site and click *SDKs*.
. In the *Hyperconverged Infrastructure* section, click *Virtual Disk Development Kit (VDDK)*.
. Select the latest VDDK version.
. Click *Download* and save the VDDK archive file in the temporary directory.
. Extract the VDDK archive:
+
[source,terminal]
----
$ tar -xzf VMware-vix-disklib-<version>.x86_64.tar.gz
----

. Create a `Dockerfile`:
+
[source,terminal]
----
$ cat > Dockerfile <<EOF
FROM registry.access.redhat.com/ubi8/ubi-minimal
COPY vmware-vix-disklib-distrib /vmware-vix-disklib-distrib
RUN mkdir -p /opt
ENTRYPOINT ["cp", "-r", "/vmware-vix-disklib-distrib", "/opt"]
EOF
----

. Build the VDDK image:
+
[source,terminal]
----
$ podman build . -t <image> <1>
----
<1> Specify the image, for example, `image-registry.openshift-image-registry.svc:5000/openshift/vddk:latest` or `registry.example.com:5000/vddk:latest`.

. Push the VDDK image to the registry:
+
[source,terminal]
----
$ podman push <image>
----

. Patch the `v2v-vmware` config map to add the `vddk-init-image` field:
+
[source,terminal]
----
$ oc patch configmap/v2v-vmware -n openshift-cnv \
    -p '{"data": {"vddk-init-image": "<image>"}}'
----
