// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_advanced-migration-options.adoc

:_mod-docs-content-type: PROCEDURE
[id="adding-migration-hook-via-ui_{context}"]
= Adding a migration hook to a migration plan using the {ocp} web console

[role="_abstract"]
You can add a migration hook to an existing migration plan by using the {ocp} web console. For example, you can create a hook to install the `cloud-init` service on a VM and write a file before migration. You can optionally specify a service account for the hook directly in the web console.

You can run one pre-migration hook, one post-migration hook, or one of each per migration plan.

.Prerequisites

* Migration plan.
* Migration hook file, whose contents you copy and paste into the web console.
* File containing the `Secret` for the source provider.
* (Optional) {ocp} service account called by the hook. The service account must have at least write access for the `openshift-mtv` namespace where hooks execute. For information about creating a service account, see link:https://docs.openshift.com/container-platform/{ocp-version}/authentication/understanding-and-creating-service-accounts.html[Understanding and creating service accounts].
* SSH access for VMs you want to migrate with the public key installed on the VMs.
* VMs running on Microsoft Server only: Remote Execution enabled.

.Procedure

. In the {ocp} web console, click *Migration for Virtualization* > *Migration plans* and then click the migration plan you want to add the hook to.
. Click *Hooks*.
. For a pre-migration hook, perform the following steps:

.. In the *Pre migration hook* section, toggle the *Enable hook* switch to *Enable pre migration hook*.
.. Enter the *Hook runner image*. If you are specifying the `spec.playbook`, you need to use an image that has an `ansible-runner`.
.. Optional: Enter the *Service account* name. The service account must have the necessary RBAC permissions to manage cluster resources and at least write access for the `openshift-mtv` namespace where hooks execute.
.. Paste your hook as a YAML file in the *Ansible playbook* text box. 

. For a post-migration hook, perform the following steps:

.. In the *Post migration hook*, toggle the *Enable hook* switch to *Enable post migration hook*.
.. Enter the *Hook runner image*. If you are specifying the `spec.playbook`, you need to use an image that has an `ansible-runner`.
.. Optional: Enter the *Service account* name. The service account must have the necessary RBAC permissions to manage cluster resources and at least write access for the `openshift-mtv` namespace where hooks execute.
.. Paste your hook as a YAML file in the *Ansible playbook* text box.

. At the top of the tab, click *Update hooks*.
+
The following example hook ensures that the VM can be accessed using SSH, creates an SSH key, and runs two tasks: stopping the MariaDB database and generating a text file.
+
[source,yaml,subs="attributes+"]
----
- name: Main
  hosts: localhost
  vars_files:
    - plan.yml
    - workload.yml
  tasks:
  - k8s_info:
      api_version: v1
      kind: Secret
      name: privkey
      namespace: openshift-mtv
    register: ssh_credentials

  - name: Ensure SSH directory exists
    file:
      path: ~/.ssh
      state: directory
      mode: 0750

  - name: Create SSH key
    copy:
      dest: ~/.ssh/id_rsa
      content: "{{ ssh_credentials.resources[0].data.key | b64decode }}"
      mode: 0600

  - add_host:
      name: "{{ vm.ipaddress }}"  # ALT "{{ vm.guestnetworks[2].ip }}"
      ansible_user: root
      groups: vms

- hosts: vms
  vars_files:
    - plan.yml
    - workload.yml
  tasks:
  - name: Stop MariaDB
    service:
      name: mariadb
      state: stopped

  - name: Create Test File
    copy:
      dest: /premigration.txt
      content: "Migration from {{ provider.source.name }}
                of {{ vm.vm1.vm0.id }} has finished\n"
      mode: 0644
----
