// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="adding-migration-hook-via-ui_{context}"]
= Adding a migration hook to a migration plan using the {ocp} web console

[role="_abstract"]
You can add a migration hook to an existing migration plan by using the {ocp} web console. 

[NOTE]
====
You need to run one command in the {project-first} CLI.
====

For example, you can create a hook to install the `cloud-init` service on a VM and write a file before migration.

[NOTE]
====
You can run one pre-migration hook, one post-migration hook, or one of each per migration plan.
====

.Prerequisites

* Migration plan
* Migration hook file, whose contents you copy and paste into the web console
* File containing the `Secret` for the source provider
* {ocp} service account called by the hook and that has at least write access for the namespace you are working in
* SSH access for VMs you want to migrate with the public key installed on the VMs
* VMs running on Microsoft Server only: Remote Execution enabled

.Additional resources
For instructions for creating a service account, see {ocp-doc}/authentication_and_authorization/index#understanding-and-creating-service-accounts[Understanding and creating service accounts].

.Procedure

. In the {ocp} web console, click *Migration* > *Plans for virtualization* and then click the migration plan you want to add the hook to.
. Click *Hooks*.
. For a pre-migration hook, perform the following steps:

.. In the *Pre migration hook* section, toggle the *Enable hook* switch to *Enable pre migration hook*.
.. Enter the *Hook runner image*. If you are specifying the `spec.playbook`, you need to use an image that has an `ansible-runner`.
.. Paste your hook as a YAML file in the *Ansible playbook* text box.

. For a post-migration hook, perform the following steps:

.. In the *Post migration hook*, toggle the *Enable hook* switch *Enable post migration hook*.
.. Enter the *Hook runner image*. If you are specifying the `spec.playbook`, you need to use an image that has an `ansible-runner`.
.. Paste your hook as a YAML file in the *Ansible playbook* text box.

. At the top of the tab, click *Update hooks*.
. In a terminal, enter the following command to associate each hook with your {ocp} service account:
+
[source,terminal,subs="attributes+"]
----
$ oc -n openshift-mtv patch hook <name_of_hook> \
  -p '{"spec":{"serviceAccount":"<service_account>"}}' --type merge
----

include::snip_example-hook-for-migration-plans.adoc[]
