// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="adding-source-provider_{context}"]
ifdef::vmware[]
= Adding a VMware vSphere source provider

You can migrate VMware vSphere VMs from VMware vCenter or from a VMWare ESX/ESXi server. In {project-short} versions 2.6 and later, you can migrate directly from an ESX/ESXi server, without going through vCenter, by specifying the SDK endpoint to that of an ESX/ESXi server.

[IMPORTANT]
====
EMS enforcement is disabled for migrations with VMware vSphere source providers in order to enable migrations from versions of vSphere that are supported by {project-full} but do not comply with the 2023 FIPS requirements. Therefore, users should consider whether migrations from vSphere source providers risk their compliance with FIPS. Supported versions of vSphere are specified in xref:../master.adoc#compatibility-guidelines_mtv[Software compatibility guidelines].
====

include::snip-mtu-value.adoc[]

.Prerequisites

* It is strongly recommended to create a VMware Virtual Disk Development Kit (VDDK) image in a secure registry that is accessible to all clusters. A VDDK image accelerates migration and reduces the risk of a plan failing. If you are not using VDDK and a plan fails, then please retry with VDDK installed. For more information, see xref:../master.adoc#creating-vddk-image_mtv[Creating a VDDK image].

include::snip-vsan.adoc[]

endif::[]
ifdef::rhv[]
= Adding {a-rhv} source provider

You can add {a-rhv} source provider by using the {ocp} web console.

.Prerequisites

* {manager} CA certificate, unless it was replaced by a third-party certificate, in which case, specify the {manager} Apache CA certificate
endif::[]
ifdef::ova[]
= Adding an Open Virtual Appliance (OVA) source provider

You can add Open Virtual Appliance (OVA) files that were created by VMware vSphere as a source provider by using the {ocp} web console.

endif::[]
ifdef::ostack[]
= Adding an {osp} source provider

You can add an {osp} source provider by using the {ocp} web console.

[IMPORTANT]
====
When you migrate an image-based VM from an {osp} provider, a snapshot is created for the image that is attached to the source VM and the data from the snapshot is copied over to the target VM. This means that the target VM will have the same state as that of the source VM at the time the snapshot was created.
====
endif::[]
ifdef::cnv[]
= Adding a Red Hat {virt} source provider

You can use a Red Hat {virt} provider as both a source provider and destination provider.

Specifically, the host cluster that is automatically added as a {virt} provider can be used as both a source provider and a destination provider.

You can migrate VMs from the cluster that {project-short} is deployed on to another cluster, or from a remote cluster to the cluster that {project-short} is deployed on.

// [NOTE]
// ====
// The {ocp} cluster version of the source provider must be 4.16 or later.
// ====
endif::[]
ifdef::dest_vmware,dest_rhv,dest_ostack,dest_ova,dest_cnv[]
= Adding {a-virt} destination provider

You can use a Red Hat {virt} provider as both a source provider and destination provider.

Specifically, the host cluster that is automatically added as a {virt} provider can be used as both a source provider and a destination provider.

You can also add another {virt} destination provider to the {ocp} web console in addition to the default {virt} destination provider, which is the cluster where you installed {project-short}.

You can migrate VMs from the cluster that {project-short} is deployed on to another cluster, or from a remote cluster to the cluster that {project-short} is deployed on.

.Prerequisites

* You must have {a-virt} link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/authentication_and_authorization/using-service-accounts[service account token] with `cluster-admin` privileges.
endif::[]

.Procedure

. In the {ocp} web console, click *Migration* -> *Providers for virtualization*.
. Click *Create Provider*.
ifdef::vmware[]
. Click *vSphere*.
. Specify the following fields:

+
*Provider details*

* *Provider resource name*: Name of the source provider.
* *Endpoint type*: Select the vSphere provider endpoint type. Options: *vCenter* or *ESXi*. You can migrate virtual machines from vCenter, an ESX/ESXi server that is not managed by vCenter, or from an ESX/ESXi server that is managed by vCenter but does not go through vCenter.
* *URL*: URL of the SDK endpoint of the vCenter on which the source VM is mounted. Ensure that the URL includes the `sdk` path, usually `/sdk`. For example, `https://vCenter-host-example.com/sdk`. If a certificate for FQDN is specified, the value of this field needs to match the FQDN in the certificate.
* *VDDK init image*: `VDDKInitImage` path. It is strongly recommended to create a VDDK init image to accelerate migrations. For more information, see xref:../master.adoc#creating-vddk-image_mtv[Creating a VDDK image].


+
*Provider credentials*

* *Username*: vCenter user or ESXi user. For example, `user@vsphere.local`.
* *Password*: vCenter user password or ESXi user password.

[start=5]
include::snip-certificate-options.adoc[]

endif::[]

ifdef::rhv[]
. Click *Red Hat Virtualization*
. Specify the following fields:

* *Provider resource name*: Name of the source provider.
* *URL*: URL of the API endpoint of the {rhv-full} Manager (RHVM) on which the source VM is mounted. Ensure that the URL includes the path leading to the RHVM API server, usually `/ovirt-engine/api`. For example, `https://rhv-host-example.com/ovirt-engine/api`.
* *Username*: Username.
* *Password*: Password.
+
include::snip-certificate-options.adoc[]
endif::[]
ifdef::ova[]
. Click *Open Virtual Appliance (OVA)*.
. Specify the following fields:

* *Provider resource name*: Name of the source provider
* *URL*: URL of the NFS file share that serves the OVA
endif::[]
ifdef::ostack[]
. Click *OpenStack*.
. Specify the following fields:

* *Provider resource name*: Name of the source provider.
* *URL*: URL of the {osp} Identity (Keystone) endpoint. For example, `http://controller:5000/v3`.
* *Authentication type*: Choose one of the following methods of authentication and supply the information related to your choice. For example, if you choose *Application credential ID* as the authentication type, the *Application credential ID* and the *Application credential secret* fields become active, and you need to supply the ID and the secret.

** *Application credential ID*
*** *Application credential ID*: {osp} application credential ID
*** *Application credential secret*: {osp} application credential `Secret`

** *Application credential name*
*** *Application credential name*: {osp} application credential name
*** *Application credential secret*: {osp} application credential `Secret`
*** *Username*: {osp} username
*** *Domain*: {osp} domain name

** *Token with user ID*
*** *Token*: {osp} token
*** *User ID*: {osp} user ID
*** *Project ID*:  {osp} project ID

** *Token with user Name*
*** *Token*: {osp} token
*** *Username*: {osp} username
*** *Project*: {osp} project
*** *Domain name*: {osp} domain name

** *Password*
*** *Username*: {osp} username
*** *Password*: {osp} password
*** *Project*: {osp} project
*** *Domain*: {osp} domain name
+
include::snip-certificate-options.adoc[]
endif::[]
ifdef::cnv[]
. Click *{virt}*.
. Specify the following fields:

* *Provider resource name*: Name of the source provider
* *URL*: URL of the endpoint of the API server
* *Service account bearer token*: Token for a service account with `cluster-admin` privileges
+
If both *URL* and *Service account bearer token* are left blank, the local {ocp-short} cluster is used.
+
include::snip-certificate-options.adoc[]
endif::[]
ifdef::dest_vmware,dest_rhv,dest_ostack,dest_ova,dest_cnv[]
. Click *{virt}*.
. Specify the following fields:

* *Provider resource name*: Name of the source provider
* *URL*: URL of the endpoint of the API server
* *Service account bearer token*: Token for a service account with `cluster-admin` privileges
+
If both *URL* and *Service account bearer token* are left blank, the local {ocp-short} cluster is used.
+
include::snip-certificate-options.adoc[]
endif::[]

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.

ifdef::vmware[]
+
[NOTE]
====
It might take a few minutes for the provider to have the status `Ready`.
====
endif::[]

ifdef::ova[]
+
[NOTE]
====
An error message might appear that states that an error has occurred. You can ignore this message.
====
endif::[]

ifdef::vmware,rhv,ostack,cnv,cnv2[]
. Optional: Add access to the UI of the provider:
.. On the *Providers* page, click the provider.
+
The *Provider details* page opens.
.. Click the *Edit* icon under *External UI web link*.
.. Enter the link and click *Save*.
+
[NOTE]
====
If you do not enter a link, {project-short} attempts to calculate the correct link.

* If {project-short} succeeds, the hyperlink of the field points to the calculated link.
* If {project-short} does not succeed, the field remains empty.
====
endif::[]
