// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="adding-source-provider_{context}"]
ifdef::vmware[]
= Adding a VMware source provider

You can add a VMware source provider by using the {ocp} web console.

.Prerequisites

* VMware Virtual Disk Development Kit (VDDK) image in a secure registry that is accessible to all clusters.
endif::[]
ifdef::rhv[]
= Adding {a-rhv} source provider

You can add {a-rhv} source provider by using the {ocp} web console.

.Prerequisites

* {manager} CA certificate, unless it was replaced by a third-party certificate, in which case, specify the {manager} Apache CA certificate
endif::[]

.Procedure

. In the {ocp} web console, click *Migration* -> *Providers for virtualization*.
. Click *Create Provider*.
ifdef::vmware[]
. Select *VMware* from the *Provider type* list.
. Fill in the following fields:

* *Provider name*: Name to display in the list of providers
* *vCenter host name or IP address*: vCenter host name or IP address - if a certificate for FQDN is specified, the value of this field needs to match the FQDN in the certificate
* *vCenter user name*: vCenter user, for example, `user@vsphere.local`
* *vCenter password*: vCenter user password
* *VDDK init image*: VDDKInitImage path

. To allow a migration without validating the provider's CA certificate, select the *Skip certificate validation* check box. By default, the checkbox is cleared, meaning that the certificate will be validated.
. Enter the *SHA-1 fingerprint*.
endif::[]
ifdef::rhv[]
. Select *Red Hat Virtualization* from the *Provider type* list.
. Fill in the following fields:

* *Provider name*: Name to display in the list of providers
* *RHV Manager host name or IP address*: {manager} host name or IP address -  if a certificate for FQDN is specified, the value of this field needs to match the FQDN in the certificate
* *RHV Manager user name*: {manager} user
* *RHV Manager password*: {manager} password

. To allow a migration without validating the provider's CA certificate, select the *Skip certificate validation* check box. By default, the checkbox is cleared, meaning that the certificate will be validated.
. If you did not select *skip certificate validation*, the *CA certificate* field is visible. Drag the CA certificate to the text box or browse for it and click *Select*. Use the {manager} CA certificate or {manager} Apache CA certificate if the {manager} CA certificate was replaced by a third-party certificate on the Apache server. If you did select the check box, the *CA certificate* text box is not visible.
endif::[]

. Click *Create* to add and save the provider.
+
The source provider appears in the list of providers.
