// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="adding-migration-hook-via-cli_{context}"]
= Adding a migration hook to a migration plan using the CLI

You can use a `Hook` CR to add a pre-migration hook or a post-migration hook to an existing migration plan using the {project-first} CLI.

For example, you can create a `Hook` CR to install the `cloud-init` service on a VM and write a file before migration.

[NOTE]
====
You can run one pre-migration hook, one post-migration hook, or one of each per migration plan. Each hook needs its own `Hook` needs its own CR, but a `Plan` CR contains data for all the hooks it uses.
====

[NOTE]
====
You can retrieve additional information stored in a secret or in a `configMap` by using a `k8s` module.
====

.Prerequisites

* Migration plan
* Migration hook image or the playbook containing the hook image

[NOTE]
====
You can run one pre-migration hook, one post-migration hook, or one of each per migration plan.
====

* File containing the Secret for the source provider
* {ocp} service account that has at least write access for the namespace you are working in
* SSH access for VMs you want to migrate with the public key installed on the VMs
* VMs running on Microsoft Server only: Remote Execution enabled

.Procedure
. If needed, create a Secret with an SSH private key for the VM.
.. Choose an existing key or generate a key pair.
.. Install the public key on the VM.
.. Encode the private key in the Secret to base64.
+
[source,yaml]
----
apiVersion: v1
data:
  key: VGhpcyB3YXMgZ2Vu...
kind: Secret
metadata:
  name: ssh-credentials
  namespace: konveyor-forklift
type: Opaque
----
. Encode your playbook by concatenating a file and piping it for base64, for example:
+
[source,shell]
----
$ cat playbook.yml | base64 -w0
----
+
[NOTE]
====
You can also use a `here` document to add instructions to encode a playbook inside a larger command:

[source,shell]
----
$ cat << EOF | base64 -w0
- hosts: localhost
  tasks:
  - debug:
      msg: test
EOF
----
====

. Create a Hook CR:
+
[source,yaml,subs="attributes+"]
----
$  cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: Hook
metadata:
  name: <hook>
  namespace: <namespace>
spec:
  image: quay.io/konveyor/hook-runner
  playbook: |
    LS0tCi0gbm...
EOF
----
+
where:
+
`playbook` refers to an optional Base64-encoded Ansible Playbook. If you specify a playbook, the `image` must be `hook-runner`.
+
[NOTE]
====
You can use the default `hook-runner` image or specify a custom image. If you specify a custom image, you do not have to specify a playbook.
====
+
[NOTE]
====
To decode an attached playbook, retrieve the resource with custom output and pipe it to base64. For example:
[source,shell]
----
 oc get -n konveyor-forklift hook playbook -o \
   go-template='{{ .spec.playbook }}' | base64 -d
----
====
+
. In the `Plan` CR of the migration, for each VM, add the following section to the end of the CR:
+
[source,yaml]
----
  vms:
    - id: <vm_id>
      hooks:
        - hook:
            namespace: <namespace>
            name: <name_of_hook>
          step: <type_of_hook> <1>
----
<1> Options are `PreHook`, to run the hook before the migration, and `PostHook`, to run the hook after the migration.

[IMPORTANT]
====
In order for a PreHook to run on a VM, the VM must be started and available via SSH.
====

include::snip_example-hook-for-migration-plans.adoc[]