// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="cnv-prerequisites_{context}"]
= {virt} prerequisites

The following prerequisites apply to migrations from one {virt} cluster to another:

* Both the source and destination {virt} clusters must have the same version of {project-first} installed.
* The source cluster must use {virt} 4.16 or later.
* Migration from a later version of {virt} to an earlier one is not supported.
* Migration from an earlier version of {virt} to a later version is supported, if both are supported by the current version of {project-short}. For example, if the current version of {virt} is 4.18, a migration from version 4.16 or 4.17 to version 4.18 is supported, but a migration from version 4.15 to any version is not.

[IMPORTANT]
====
It is strongly recommended to migrate only between clusters with the same version of {virt}, although migration from an earlier version of {virt} to a later one is supported.
====




