// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="cnv-cnv-live-prerequisites_{context}"]
= {virt} live migration prerequisites

[role="_abstract"]
Live migration between {virt} clusters using {project-first} has its own set of prerequisites:

* {project-short} 2.10.0 or later installed.
* {virt} 4.20.0 or later installed on both source and target clusters.
* In the {project-short} Operator, in the `spec` portion of the `forklift-controller` YAML, `feature_ocp_live_migration` is set to true`. You must have `admin-cluster` privileges to set this label.
* In the `KubeVirt` resource of both clusters in the `featureGates` of the YAML,`DecntralizedLiveMigration` is listed.You must have `admin-cluster` privileges to set this label.
* Connectivity between the clusters must be established.
* `forklift-controller` has access to read and create `VirtualMachineInstanceMigration` instances on both the source and target clusters.