// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="mtv-cold-warm-migration_{context}"]
= Cold migration and warm migration in {project-short}

[role="_abstract"]
{project-first} supports two types of migration, cold and warm.

Cold migration is when a powered *_off_* virtual machine (VM) is migrated to a separate host. The VM is powered off, and there is no need for common shared storage.

Warm migration is when a powered *_on_* VM is migrated to a separate host. A source host state is cloned to the destination host.

[id="mtv-cold-warm-migration-precopy_{context}"]
== Warm migration precopy stage

. Create an initial snapshot of running VM disks.
. Copy first snapshot to target: full-disk transfer, the largest amount of data copied. It takes more time to complete.
. Copy deltas: changed data, copying only data that has changed since the last snapshot was taken. It takes less time to complete.
.. Create a new snapshot.
.. Copy the delta between the previous snapshot and the new snapshot.
.. Schedule the next snapshot, configurable by default, one hour after the last snapshot finished.
. An arbitrary number of deltas can be copied.

[id="mtv-cold-warm-migration-cutover_{context}"]
== Warm migration cutover stage

. Scheduled time to finalize warm migration
. Shut down the source VM.
. Copy the final snapshot delta to the target.
. Continue in the same way as cold migration
.. Guest conversion
.. Starting target VM (optional)
