// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="compatibility-guidelines_{context}"]
= Software compatibility guidelines

You must install compatible software versions.

[cols="1,1,1,1,1,1", options="header"]
.Compatible software versions
|===
|{project-full} |{ocp} |{virt} |VMware vSphere |{rhv-full}|OpenStack
|{project-z-version} |4.12 or later |4.12 or later |6.5 or later |4.4 SP1 or later|16.1 or later
|===

[NOTE]
.Migration from {rhv-full} 4.3
====
MTV 2.5 was tested only with {rhv-full} (RHV) 4.4 SP1.
Migration from {rhv-full} ({rhv-short}) 4.3 has not been tested with {project-short} {project-version}.

As {rhv-short} 4.3 lacks the improvements that were introduced in {rhv-short} 4.4 for {project-short}, and new features were not tested with {rhv-short} 4.3, migrations from {rhv-short} 4.3 may not function at the same level as migrations from {rhv-short} 4.4, with some functionality may be missing.

Therefore, it is recommended to upgrade {rhv-short} to the supported version above before the migration to {virt}.

However, migrations from {rhv-short} 4.3.11 were tested with {project-short} 2.3, and may work in practice in many environments using {project-short} {project-version}. In this case, we advise upgrading {rhv-full} Manager (RHVM) to the previously mentioned supported version before the migration to {virt}.
====

[NOTE]
====
Deployment of MTV 2.5.3 and later is enabled on OpenShift Kubernetes Engine (OKE). For more information, see link:https://docs.openshift.com/container-platform/4.14/welcome/oke_about.html[About OpenShift Kubernetes Engine].
====

[openshift-operator-life-cycles]
== OpenShift Operator Life Cycles

For more information about the software maintenance Life Cycle classifications for Operators shipped by Red Hat for use with OpenShift Container Platform, see link:https://access.redhat.com/support/policy/updates/openshift_operators#platform-agnostic[OpenShift Operator Life Cycles].

