// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="compatibility-guidelines_{context}"]
= Software compatibility guidelines

You must install compatible software versions.


// check OCP version
[cols="1,1,1,1,1,1", options="header"]
.Compatible software versions
|===
|{project-full} |{ocp} |{virt} |VMware vSphere |{rhv-full}|OpenStack
|{project-z-version} |{ocp-y-version} |{ocp-y-version} |6.5 or later |4.4 SP1 or later|16.1 or later
|===

[NOTE]
.Migration from {rhv-full} 4.3
====
{project-short} was tested only with {rhv-full} (RHV) 4.4 SP1.
Migration from {rhv-full} ({rhv-short}) 4.3 has not been tested with {project-short} {project-version}. While not supported, basic migrations from {rhv-short} 4.3 are expected to work.

Generally it is advised to upgrade {rhv-full} Manager (RHVM) to the previously mentioned supported version before the migration to {virt}.

Therefore, it is recommended to upgrade {rhv-short} to the supported version above before the migration to {virt}.

However, migrations from {rhv-short} 4.3.11 were tested with {project-short} 2.3, and may work in practice in many environments using {project-short} {project-version}. In this case, we advise upgrading {rhv-full} Manager (RHVM) to the previously mentioned supported version before the migration to {virt}.
====

[id="openshift-operator-life-cycles"]
== OpenShift Operator Life Cycles

For more information about the software maintenance Life Cycle classifications for Operators shipped by Red Hat for use with OpenShift Container Platform, see link:https://access.redhat.com/support/policy/updates/openshift_operators#platform-agnostic[OpenShift Operator Life Cycles].

