// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/master.adoc

:_mod-docs-content-type: CONCEPT

[id="con_planning-intro_{context}"]
= Planning a migration

[role="_abstract"]
You can use the Migration Toolkit for Virtualization (MTV) to plan your migration of virtual machines from the
following source providers to OpenShift Virtualization destination providers:

* {vmw} vSphere
* {rhv-full} 
* {osp}
* Open Virtual Appliances (OVAs) that were created by {vmw} vSphere
* Remote {virt} clusters

== Types of migration

{project-short} supports three types of migration: cold, warm, and live.

* Cold migration is available for all of the source providers listed above. This type of migration migrates VMs that are powered *_off_* and does not require common stored storage. 

* Warm migration is available only for {vmw} vSphere and {rhv-full}. This type of migration migrates VMs that are powered *_on_* and does require common stored storage. 
+
These two types of migration are discussed in detail in xref:about-cold-warm-migration_mtv[About cold and warm migration].

* Live migration is available *_only_* for migrations between {virt} clusters or between namespaces on the same {virt} cluster. It requires {project-short} version 2.10 or later and {virt} version 4.20 or later. 
+
Live migration is discussed in detail in xref:assembly_live-migration_mtv[Live migration in {project-short}].
