// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_advanced-migration-options.adoc

:_mod-docs-content-type: CONCEPT
[id="con_about-udn_{context}"]
= About user defined networks

[role="_abstract"]
Use a user-defined network (UDN) as your default network for migrations from all source providers. UDNs are not supported for {ocp-short}-to-{ocp-short} migrations. You can configure UDNs in {virt} and specify them in migration plan mappings.

{project-short} has been redesigned to make it easy for you to migrate VMs to UDN namespaces. When you configure your UDN in {virt}, you can specify it as your default network in the migration plan mapping. {project-short} is now able to distinguish a UDN from a conventional pod network. 

You can use this feature for creating migration plans by using the {ocp} web console or by using the {project-short} command-line interface. The procedures for creating migration plans have been updated to include the new feature. 

[role="_additional-resources"]
.Additional resources

* {ocp-doc}/virtualization/networking#virt-connecting-vm-to-primary-udn[Connecting a virtual machine to a primary user-defined network]
