// Module included in the following assemblies:
//
// assembly_migrating-vms-web-console.adoc

:_mod-docs-content-type: CONCEPT
[id="con_target-vm-power-states_{context}"]

= Target VM power states

[role="_abstract"]
You can configure the post-migration power state of VMs in advance of a migration. Plan for VMs to start up automatically, remain powered off, or preserve the power state of the source VM. For example, if you are migrating a VM that is running in the source environment, you can ensure that the VM is powered off post-migration to preserve start-up dependencies between VMs. 

Benefits::

* Ensure that critical applications are available immediately without manual intervention.
* Optimize resource usage and reduce downtime for users.
* Make informed decisions about resource allocation and operational efficiency.
* Manage application start-up dependencies.

The configuration of post-migration power states has different uses for cold migrations and warm migration:

* *Cold migrations:* The cold migration process involves transferring source VMs that might be running in the source environment. MTV shuts down running VMs during the cold migration process, and then starts the target VMs. You can determine a VM's final power state on the {virt} cluster. For example, set the `targetPowerState` parameter to `auto` to start up a VM that was running before the migration started and before MTV shut it down for the cold migration.
* *Warm migrations:* The warm migration process includes an optional step to start a target VM when the migration is complete, but the `targetPowerState` parameter provides a more transparent method for managing the power state of migrated VMs. For example, set the `targetPowerState` parameter to `off` to prevent the VM from starting up when migrating workloads for testing or staging.

