// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_understanding-mtv-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="con_mtv-resources-and-services_{context}"]
= {project-short} custom resources and services

[role="_abstract"]
The {operator-name} is a {ocp} Operator that creates and manages the {project-short} custom resources (CRs) and services.

[id="mtv-custom-resources_{context}"]
== {project-short} custom resources

* A `Provider` CR stores attributes that {project-short} uses to connect to and interact with the source and target providers.
* A `NetworkMapping` CR maps the networks of the source and target providers.
* A `StorageMapping` CR maps the storage of the source and target providers.
* A `Plan` CR contains a list of virtual machines (VMs) with the same migration parameters and associated network and storage mappings.
* A `Migration` CR runs a migration plan.
+
Only one `Migration` CR per migration plan can run at a given time. You can create multiple `Migration` CRs for a single `Plan` CR.

[id="mtv-services_{context}"]
== {project-short} services

* The `Inventory` service performs the following actions:
** Connects to the source and target providers.
** Maintains a local inventory for mappings and plans.
** Stores VM configurations.
** Runs the `Validation` service if it detects a VM configuration change.

* The `Validation` service checks whether a VM is suitable for migration by applying rules.
* The `Migration Controller` service orchestrates migrations.
+
When you create a migration plan, the `Migration Controller` service validates the plan and adds a status label. If the plan fails validation, the status is *Not ready*, and you cannot use the plan to perform a migration. If the plan passes validation, the status is *Ready*, and you can use it to perform a migration. After a successful migration, the `Migration Controller` service changes the plan status to *Complete*.
+
[IMPORTANT]
====
For successful migrations, {project-short} automatically deletes temporary PVC mounts, conversion pods, and populator pods and changes the plan's status to *Complete* in the UI, or `Succeeded` in the YAML file. For failed migrations, the plan's status is *Incomplete* in the UI, or `failed` in the YAML file, and temporary PVC mounts are kept so you can investigate the failure. You must archive a failed migration plan to clean up temporary resources.
====

* The `Populator Controller` service orchestrates disk transfers using Volume Populators.

* The `Kubevirt Controller` and `Containerized Data Import (CDI) Controller` services handle most technical operations.

[role="_additional-resources"]
.Additional resources
* link:{mtv-mig}assembly_troubleshooting-migration_mtv#con_post-migration-cleanup_mtv[Post-migration cleanup and archiving migration plans]
