// Module included in the following assemblies:
//
// assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: CONCEPT
[id="con_migration-of-luks-encrypted-disks_{context}"]

= Migration of LUKS-encrypted disks

[role="_abstract"]
If you have virtual machines (VMs) with LUKS-encrypted disks in your source VMware VSphere environment, you can migrate them to Red Hat {virt} by using one of the following methods:

* Enabling Network-Bound Disk Encryption (NBDE) with Clevis to retrieve passwords from the Clevis server.
* Selecting an existing `Secret` manifest that contains the decryption passphrase. The secret must have `type` set to `Opaque`.
* Manually entering passphrases for LUKS-encrypted devices in your migration plan.

These methods are mutually exclusive. You must select only one method per migration plan.

MTV transfers the data of VMs with LUKS-encrypted disks from the source environment to the target {virt} cluster. MTV reads only the blocks that are required for guest conversion, decrypting the required blocks and re-encrypting them locally with the same key.

Clevis is a client-side framework that automates the decryption of LUKS volumes by binding a LUKS key slot to a policy. During the migration of VMs with LUKS-encrypted disks, MTV authenticates with the configured network service by requesting the key to unlock the LUKS-encrypted disk from the Tang server. The automatic retrieval of the key allows the VM to boot without a manual passphrase entry from an administrator.

Benefits of NBDE::

* *Automation:* Eliminates the need to enter keys manually during migration.
* *Enhanced security:* Maintains the security of VMs throughout their migration lifecycle by preserving LUKS encryption from the source to the destination.
* *Seamless operation:* Ensures that VMs with encrypted disks can be brought online in the new OpenShift Virtualization environment with minimal interruption.


