// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_troubleshooting-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="con_collected-logs-cr-info_{context}"]
= Collected logs and custom resource information

[role="_abstract"]
You can download logs and custom resource (CR) YAML files for the following targets by using the {ocp} web console or the command-line interface (CLI):

* Migration plan: Web console or CLI.
* Virtual machine: Web console or CLI.
* Namespace: CLI only.

The `must-gather` tool collects the following logs and CR files in an archive file:

* CRs:
** `DataVolume` CR: Represents a disk mounted on a migrated VM.
** `VirtualMachine` CR: Represents a migrated VM.
** `Plan` CR: Defines the VMs and storage and network mapping.
** `Job` CR: Optional: Represents a pre-migration hook, a post-migration hook, or both.

* Logs:
** `importer` pod: Disk-to-data-volume conversion log. The `importer` pod naming convention is `importer-<migration_plan>-<vm_id><5_char_id>`, for example, `importer-mig-plan-ed90dfc6-9a17-4a8btnfh`, where `ed90dfc6-9a17-4a8` is a truncated {rhv-short} VM ID and `btnfh` is the generated 5-character ID.
** `conversion` pod: VM conversion log. The `conversion` pod runs `virt-v2v`, which installs and configures device drivers on the PVCs of the VM. The `conversion` pod naming convention is `<migration_plan>-<vm_id><5_char_id>`.
** `virt-launcher` pod: VM launcher log. When a migrated VM is powered on, the `virt-launcher` pod runs `QEMU-KVM` with the PVCs attached as VM disks.
** `forklift-controller` pod: The log is filtered for the migration plan, virtual machine, or namespace specified by the `must-gather` command.
** `forklift-must-gather-api` pod: The log is filtered for the migration plan, virtual machine, or namespace specified by the `must-gather` command.
** `hook-job` pod: The log is filtered for hook jobs. The `hook-job` naming convention is `<migration_plan>-<vm_id><5_char_id>`, for example, `plan2j-vm-3696-posthook-4mx85` or `plan2j-vm-3696-prehook-mwqnl`.
+
[NOTE]
====
Empty or excluded log files are not included in the `must-gather` archive file.
====

The following schematic drawing shows the `must-gather` archive structure for an example VMware migration plan:

----
must-gather
в””в”Ђв”Ђ namespaces
    в”њв”Ђв”Ђ target-vm-ns
    в”‚   в”њв”Ђв”Ђ crs
    в”‚   в”‚   в”њв”Ђв”Ђ datavolume
    в”‚   в”‚   в”‚   в”њв”Ђв”Ђ mig-plan-vm-7595-tkhdz.yaml
    в”‚   в”‚   в”‚   в”њв”Ђв”Ђ mig-plan-vm-7595-5qvqp.yaml
    в”‚   в”‚   в”‚   в””в”Ђв”Ђ mig-plan-vm-8325-xccfw.yaml
    в”‚   в”‚   в””в”Ђв”Ђ virtualmachine
    в”‚   в”‚       в”њв”Ђв”Ђ test-test-rhel8-2disks2nics.yaml
    в”‚   в”‚       в””в”Ђв”Ђ test-x2019.yaml
    в”‚   в””в”Ђв”Ђ logs
    в”‚       в”њв”Ђв”Ђ importer-mig-plan-vm-7595-tkhdz
    в”‚       в”‚   в””в”Ђв”Ђ current.log
    в”‚       в”њв”Ђв”Ђ importer-mig-plan-vm-7595-5qvqp
    в”‚       в”‚   в””в”Ђв”Ђ current.log
    в”‚       в”њв”Ђв”Ђ importer-mig-plan-vm-8325-xccfw
    в”‚       в”‚   в””в”Ђв”Ђ current.log
    в”‚       в”њв”Ђв”Ђ mig-plan-vm-7595-4glzd
    в”‚       в”‚   в””в”Ђв”Ђ current.log
    в”‚       в””в”Ђв”Ђ mig-plan-vm-8325-4zw49
    в”‚           в””в”Ђв”Ђ current.log
    в””в”Ђв”Ђ {namespace}
        в”њв”Ђв”Ђ crs
        в”‚   в””в”Ђв”Ђ plan
        в”‚       в””в”Ђв”Ђ mig-plan-cold.yaml
        в””в”Ђв”Ђ logs
            в”њв”Ђв”Ђ forklift-controller-67656d574-w74md
            в”‚   в””в”Ђв”Ђ current.log
            в””в”Ђв”Ђ forklift-must-gather-api-89fc7f4b6-hlwb6
                в””в”Ђв”Ђ current.log
----
