// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_cold-warm-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="con_warm-migration_{context}"]
= Warm migration

[role="_abstract"]
Warm migration copies most of the data while the source virtual machines (VMs) remain running, minimizing downtime.

The migration process has two stages:

* *Precopy stage*: Most data is copied while VMs continue running. VM disks are copied incrementally using changed block tracking (CBT) snapshots. For more information about CBT snapshots, see the "Additional resources" section.
* *Cutover stage*: VMs are shut down and the remaining data is migrated. Data stored in RAM is not migrated.

Warm migration transfers snapshots to {ocp-short} first, then converts the VM during the cutover stage. This means disk blocks may be copied multiple times if the VM has high utilization, but VMs remain available during most of the migration process. You must enable CBT for each source VM and each VM disk before starting a warm migration.

[role="_additional-resources"]
== Additional resources

* link:https://kb.vmware.com/s/article/1020128[Changed Block Tracking (CBT) on virtual machines]
