// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/master.adoc

:_mod-docs-content-type: CONCEPT

[id="con_planning-intro_{context}"]
= Planning a migration

[role="_abstract"]
You can use the {project-first} to plan your migration of virtual machines (VMs) from specific source providers to OpenShift Virtualization destination providers.

The supported source providers are:

* {vmw} vSphere
* {rhv-full} 
* {osp}
* Open Virtual Appliances (OVAs) that were created by {vmw} vSphere
* Remote {virt} clusters

[NOTE]
====
OVA migration is validated for migrating supported guest operating systems exported from {vmw} vSphere. For third-party networking or security appliances, check with the vendor for native QCOW2 or Kernel-based Virtual Machine (KVM) images.
====

[id="types-of-migration_{context}"]
== Types of migration
{project-short} supports three types of migration: cold, warm, and live.

* Cold migration is available for all of the preceding source providers. This type of migration migrates VMs that are powered _off_ and does not require shared storage.

* Warm migration is available only for {vmw} vSphere and {rhv-full}. This type of migration migrates VMs that are powered _on_ and requires shared storage.

* Live migration is available *_only_* for migrations between {virt} clusters or between namespaces on the same {virt} cluster. It requires {project-short} version 2.10 or later and {virt} version 4.20 or later. 

[role="_additional-resources"]
.Additional resources
* xref:con_about-cold-warm-migration_mtv[About cold and warm migration]
* link:{mtv-plan}assembly_live-migration_mtv[Live migration in {project-short}]
