// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="configuring-mtv-operator_{context}"]
= Configuring the {operator-name}

You can configure all of the following settings of the {operator-name} by modifying the `ForkliftController` CR, or in the *Settings* section of the *Overview* page, unless otherwise indicated.

* Maximum number of virtual machines (VMs) per plan that can be migrated simultaneously.
* How long `must gather` reports are retained before being automatically deleted.
* CPU limit allocated to the main controller container.
* Memory limit allocated to the main controller container.
* Interval at which a new snapshot is requested before initiating a warm migration.
* Frequency with which the system checks the status of snapshot creation or removal during a warm migration.
* Percentage of space in persistent volumes allocated as file system overhead when the `storageclass` is `filesystem` (`ForkliftController` CR only).
* Fixed amount of additional space allocated in persistent block volumes. This setting is applicable for any `storageclass` that is block-based (`ForkliftController` CR only).
* Configuration map of operating systems to preferences for vSphere source providers (`ForkliftController` CR only).
* Configuration map of operating systems to preferences for {rhv-full} ({rhv-short}) source providers (`ForkliftController` CR only).

The procedure for configuring these settings using the user interface is presented in xref:mtv-overview-page_{context}[Configuring MTV settings]. The procedure for configuring these settings by modifying the `ForkliftController` CR is presented following.

.Procedure

* Change a parameter's value in  the `spec` portion of the `ForkliftController` CR by adding the label and value as follows:
[source, YAML]
----
spec:
  label: value <1>
----
<1> Labels you can configure using the CLI are shown in the table that follows, along with a description of each label and its default value.

.{operator-name} labels
[cols="1,1,1",options="header"]
|===
|Label |Description |Default value

|`controller_max_vm_inflight`
|The maximum number of VMs per plan that can be migrated simultaneously.
|`20`

|`must_gather_api_cleanup_max_age`
|The duration in hours for retaining `must gather` reports before they are automatically deleted.
|`-1` (disabled)

|`controller_container_limits_cpu`
|The CPU limit allocated to the main controller container.
|`500m`

|`controller_container_limits_memory`
|The memory limit allocated to the main controller container.
|`800Mi`

|`controller_precopy_interval`
|The interval in minutes at which a new snapshot is requested before initiating a warm migration.
|`60`

|`controller_snapshot_status_check_rate_seconds`
|The frequency in seconds with which the system checks the status of snapshot creation or removal during a warm migration.
|`10`

|`controller_filesystem_overhead`
|Percentage of space in persistent volumes allocated as file system overhead when the `storageclass` is `filesystem`.

`ForkliftController` CR only.
|`10`

|`controller_block_overhead`
|Fixed amount of additional space allocated in persistent block volumes. This setting is applicable for any `storageclass` that is block-based. It can be used when data, such as encryption headers, is written to the persistent volumes in addition to the content of the virtual disk.

`ForkliftController` CR only.
|`0`

|`vsphere_osmap_configmap_name`
|Configuration map for vSphere source providers. This configuration map maps the operating system of the incoming VM to a {virt} preference name. This configuration map needs to be in the namespace where the {project-short} Operator is deployed.

To see the list of preferences in your {virt} environment, open the {ocp-name} web console and click *Virtualization* -> *Preferences*.

You can add values to the configuration map when this label has the default value, `forklift-vsphere-osmap.` In order to override or delete values, specify a configuration map that is different from `forklift-vsphere-osmap`.

`ForkliftController` CR only.
|`forklift-vsphere-osmap`

|`ovirt_osmap_configmap_name`
|Configuration map for {rhv-short} source providers. This configuration map maps the operating system of the incoming VM to a {virt} preference name. This configuration map needs to be in the namespace where the {project-short} Operator is deployed.

To see the list of preferences in your {virt} environment, open the {ocp-name} web console and click *Virtualization* -> *Preferences*.

You can add values to the configuration map when this label has the default value, `forklift-ovirt-osmap.` In order to override or delete values, specify a configuration map that is different from `forklift-ovirt-osmap`.

`ForkliftController` CR only.
|`forklift-ovirt-osmap`
|===


