// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="creating-migration-plan_{context}"]
= Creating a migration plan

You can create a migration plan by using the {project-short} web console.

A migration plan allows you to group virtual machines to be migrated together or with the same migration parameters, for example, a percentage of the members of a cluster or a complete application.

You can configure a hook to run an Ansible playbook or custom container image during a specified stage of the migration plan.

.Prerequisites

* If {project-short} is not installed on the target cluster, you must add a target provider on the *Providers* page of the web console.

.Procedure

. In the web console, click *Migration plans* and then click *Create migration plan*.
. Complete the following fields:

* *Plan name*: Enter a migration plan name to display in the migration plan list.
* *Plan description*: Optional: Brief description of the migration plan.
* *Source provider*: Select a source provider.
* *Target provider*: Select a target provider.
* *Target namespace*: You can type to search for an existing target namespace or create a new namespace.
* You can change the migration transfer network for this plan by clicking *Select a different network*, selecting a network from the list, and clicking *Select*.
+
If you defined a migration transfer network for the {virt} provider and if the network is in the target namespace, that network is the default network for all migration plans. Otherwise, the `pod` network is used.

. Click *Next*.
. Select options to filter the list of source VMs and click *Next*.
. Select the VMs to migrate and then click *Next*.
. Select an existing network mapping or create a new network mapping.
+
To create a new network mapping:

* Select a target network for each source network.
* Optional: Select *Save mapping to use again* and enter a network mapping name.
. Click *Next*.
. Select an existing storage mapping or create a new storage mapping.
+
To create a new storage mapping:

* Select a target storage class for each VMware data store or {rhv-full} storage domain.
* Optional: Select *Save mapping to use again* and enter a storage mapping name.
. Click *Next*.
. Select a migration type and click *Next*.
* Cold migration: The source VMs are stopped while the data is copied.
* Warm migration: The source VMs run while the data is copied incrementally. Later, you will run the cutover, which stops the VMs and copies the remaining VM data and metadata.

. Optional: You can create a migration hook to run an Ansible playbook before or after migration:
.. Click *Add hook*.
.. Select the step when the hook will run.
.. Select a hook definition:
* *Ansible playbook*: Browse to the Ansible playbook or paste it into the field.
* *Custom container image*: If you do not want to use the default `hook-runner` image, enter the image path: `<registry_path>/<image_name>:<tag>`.
+
[NOTE]
====
The registry must be accessible to your {ocp} cluster.
====

. Click *Next*.
. Review your migration plan and click *Finish*.
+
The migration plan is saved in the migration plan list.

. Click the {kebab} of the migration plan and select *View details* to verify the migration plan details.
