// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="creating-migration-quick-plan-vm_{context}"]
= Creating and running a migration plan starting on Providers for virtualization

.Procedure

. In the {ocp} web console, click *Providers for virtualization*.
. In the row of the appropriate source provider, click *VMs*.
+.
The *Virtual Machines* tab opens.
. Select the VMs you want to migrate and click *Create migration plan*.
+
The *Create migration plan* pane opens. It displays the source provider's name and suggestions for a target provider and namespace, a network map, and a storage map.
. Enter the *Plan name*.
. Make any desired changes to the editable items.
. Click *Add mapping* to edit a suggested network mapping or a storage mapping, or to add one or more additional mappings.
. Click *Create migration plan*.
+
{project-short} validates the migration plan and the *Plan details* page opens, indicating whether the plan is ready for use or contains an error. In all cases, the details of the plan are listed, and you can edit the items you filled in on the previous page. If you make any changes, {project-short} again validates the plan.
. If the plan is valid,
.. You can run the plan now by clicking *Start migration*.
.. You can run the plan later by selecting it on the *Plans for virtualization* page and following the procedure in xref:running-migration-plan_{context}[Running a migration plan].
