// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="creating-storage-mapping_{context}"]
= Creating a storage mapping

You can create a storage mapping by using the {project-short} web console to map source data stores to {virt} storage classes.

.Prerequisites

* Source and target providers added to the web console.
* Local and shared persistent storage that support VM migration.

.Procedure

. Click *Mappings*.
. Click the *Storage* tab and then click *Create mapping*.
. Enter the *Name* of the storage mapping.
. Select a *Source provider* and a *Target provider*.
. If your source provider is VMware, select a *Source datastore* and a *Target storage class*.

. If your source provider is {rhv-full}, select a *Source storage domain* and a *Target storage class*.

. Optional: Click *Add* to create additional storage mappings or to map multiple source data stores or storage domains to a single storage class.
. Click *Create*.
+
The mapping is displayed on the *Storage mappings* page.
