// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-cnv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-osp.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-ova.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-rhv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-yaml-based-stoarge-maps-ui_{context}"]

= Creating ownerless storage maps using YAML or JSON definitions in the {project-short} UI

[role="_abstract"]
You can create ownerless storage maps by using YAML or JSON definitions in the {project-first} UI.

.Procedure

. In the {ocp} web console, click *Migration for Virtualization* > *Storage maps*.
. Click *Create storage map* > *Create with YAML*.
+
The *Create StorageMap* page opens.
. Enter the YAML or JSON definitions into the editor, or drag and drop a file into the editor.
. If you enter YAML definitions, use the following:

ifdef::vmware[]
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        id: <source_datastore>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
* `accessMode`: Allowed values are `ReadWriteOnce` and `ReadWriteMany`.
* `id`: Specify the VMware vSphere datastore moRef, for example, `f2737930-b567-451a-9ceb-2887f6207009`. For more information about retrieving the moRef, see 'Retrieving a VMware vSphere moRef' in _Migrating your virtual machines to Red Hat {virt}_.
endif::[]

ifdef::rhv[]
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        id: <source_storage_domain>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
* `accessMode`: Allowed values are `ReadWriteOnce` and `ReadWriteMany`.
* `id`: Specify the {rhv-short} storage domain UUID, for example, `f2737930-b567-451a-9ceb-2887f6207009`.
endif::[]

ifdef::ova[]
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        name:  Dummy storage for source provider <provider_name>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
* `accessMode`: Allowed values are `ReadWriteOnce` and `ReadWriteMany`.
* `name`: For OVA, the `StorageMap` can map only a single storage, which all the disks from the OVA are associated with, to a storage class at the destination. For this reason, the storage is referred to in the UI as "Dummy storage for source provider <provider_name>". In the YAML, write the phrase as it appears above, without the quotation marks and replacing <provider_name> with the actual name of the provider.
endif::[]

ifdef::ostack[]
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        id: <source_volume_type>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
* `accessMode`: Allowed values are `ReadWriteOnce` and `ReadWriteMany`.
* `id`: Specify the {osp} `volume_type` UUID, for example, `f2737930-b567-451a-9ceb-2887f6207009`.
endif::[]

ifdef::cnv[]
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        name: <storage_class>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
* `accessMode`: Allowed values are `ReadWriteOnce` and `ReadWriteMany`.
endif::[]

[start=5]
. Optional: To download your input, click *Download*.
. Click *Create*.
+
Your map appears in the list of storage maps.
