// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="creating-storage-mapping_{context}"]
= Creating a storage mapping

You can create a storage mapping by using the {ocp} web console to map source disk storages to {virt} storage classes.

.Prerequisites

* Source and target providers added to the {ocp} web console.
* Local and shared persistent storage that support VM migration.

.Procedure

. In the {ocp} web console, click *Migration* -> *StorageMaps for virtualization*.
. Click *Create StorageMap*.
. Specify the following fields:

* *Name*: Enter a name to display in the storage mappings list.
* *Source provider*: Select a source provider.
* *Target provider*: Select a target provider.

. To create a storage mapping, click *Add* and map storage sources to target storage classes as follows:

.. If your source provider is VMware vSphere, select a *Source datastore* and a *Target storage class*.
.. If your source provider is {rhv-full}, select a *Source storage domain* and a *Target storage class*.
.. If your source provider is {osp}, select a *Source volume type* and a *Target storage class*.
.. If your source provider is a set of one or more OVA files, select a *Source* and a *Target storage class* for the dummy storage that applies to all virtual disks within the OVA files.
.. If your storage provider is {virt}. select a *Source storage class* and a *Target storage class*.
.. Optional: Click *Add* to create additional storage mappings, including mapping multiple storage sources to a single target storage class.
. Click *Create*.
+
The mapping is displayed on the *StorageMaps* page.
