// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-rhv.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-yaml-based-storage-maps-ui-rhv_{context}"]
= Creating ownerless storage maps using YAML or JSON definitions in the {project-short} UI

[role="_abstract"]
You can create ownerless storage maps by using YAML or JSON definitions in the {project-first} UI.

.Procedure

. In the {ocp} web console, click *Migration for Virtualization* > *Storage maps*.
. Click *Create storage map* > *Create with YAML*.
+
The *Create StorageMap* page opens.
. Enter the YAML or JSON definitions into the editor, or drag and drop a file into the editor.
. If you enter YAML definitions, use the following:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        id: <source_storage_domain>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
+
* `accessMode`: Allowed values are `ReadWriteOnce` and `ReadWriteMany`.
* `id`: Specify the {rhv-short} storage domain UUID, for example, `f2737930-b567-451a-9ceb-2887f6207009`.

. Optional: To download your input, click *Download*.
. Click *Create*.
+
Your map appears in the list of storage maps.

