// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="creating-vddk-image_{context}"]
= Creating a VDDK image

{the} {project-first} uses the VMware Virtual Disk Development Kit (VDDK) SDK to accelerate transferring virtual disks from VMware vSphere. Therefore, creating a VDDK image, although optional, is highly recommended.

To make use of this feature, you download the VMware Virtual Disk Development Kit (VDDK), build a VDDK image, and push the VDDK image to your image registry.

The VDDK package contains symbolic links, therefore, the procedure of creating a VDDK image must be performed on a file system that preserves symbolic links (symlinks).

[NOTE]
====
Storing the VDDK image in a public registry might violate the VMware license terms.
====

.Prerequisites

* link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/registry/setting-up-and-configuring-the-registry#configuring-registry-storage-baremetal[{ocp} image registry].
* `podman` installed.
* You are working on a file system that preserves symbolic links (symlinks).
* If you are using an external registry, {virt} must be able to access it.

.Procedure

. Create and navigate to a temporary directory:
+
[source,terminal]
----
$ mkdir /tmp/<dir_name> && cd /tmp/<dir_name>
----

. In a browser, navigate to the link:https://developer.vmware.com/web/sdk/8.0/vddk[VMware VDDK version 8 download page].
. Select version 8.0.1 and click *Download*.

[NOTE]
====
In order to migrate to {virt} 4.12, download VDDK version 7.0.3.2 from the link:https://developer.vmware.com/web/sdk/7.0/vddk[VMware VDDK version 7 download page].
====

// On 17 January 2025, remove this note unless the OpenShift Container Platform's life cycle is extended.

. Save the VDDK archive file in the temporary directory.
. Extract the VDDK archive:
+
[source,terminal]
----
$ tar -xzf VMware-vix-disklib-<version>.x86_64.tar.gz
----

. Create a `Dockerfile`:
+
[source,terminal]
----
$ cat > Dockerfile <<EOF
FROM registry.access.redhat.com/ubi8/ubi-minimal
USER 1001
COPY vmware-vix-disklib-distrib /vmware-vix-disklib-distrib
RUN mkdir -p /opt
ENTRYPOINT ["cp", "-r", "/vmware-vix-disklib-distrib", "/opt"]
EOF
----

. Build the VDDK image:
+
[source,terminal]
----
$ podman build . -t <registry_route_or_server_path>/vddk:<tag>
----

. Push the VDDK image to the registry:
+
[source,terminal]
----
$ podman push <registry_route_or_server_path>/vddk:<tag>
----

. Ensure that the image is accessible to your {virt} environment.
