// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-form-based-storage-maps-ui-vmware_{context}"]
= Creating ownerless storage maps using the form page of the {project-short} UI

[role="_abstract"]
You can create ownerless storage maps by using the form page of the {project-short} UI.

.Prerequisites

* Have a {vmw} source provider and a {virt} destination provider. For more information, see xref:adding-source-provider_vmware[Adding a VMware vSphere source provider] or xref:adding-source-provider_dest_vmware[Adding {a-virt} destination provider].

.Procedure

. In the {ocp} web console, click *Migration for Virtualization* > *Storage maps*.
. Click *Create storage map* > *Create with form*.
. Specify the following:

* *Map name*: Name of the storage map.
* *Project*: Select from the list.
* *Source provider*: Select from the list.
* *Target provider*: Select from the list.
* *Source storage*: Select from the list.
* *Target storage*: Select from the list.

. Optional: If this is a storage map for a migration using storage copy offload, specify the following offload options:

* *Offload plugin*: Select from the list.
* *Storage secret*: Select from the list.
* *Storage product*: Select from the list.
+
[NOTE]
====
Storage copy offload is a feature that allows you to migrate {vmw} virtual machines (VMs) that are in a storage array network (SAN) more efficiently. The feature makes use of the `XCOPY` command in {vmw}'s vSphere Storage APIs-Array Integration (VAAI). This command lets you copy data inside a SAN more efficiently than copying the data over a network. Storage copy offload is available as a Technology Preview feature for {project-first} 2.10.0 for cold migration and as a Developer Preview feature for warm migration. It is not available for shared disks for either cold or warm migration For more information, see TBD.
====

. Optional: Click *Add mapping* to create additional storage maps, including mapping multiple storage sources to a single target storage class.
. Click *Create*.
+
Your map appears in the list of storage maps.
