// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="creating-plan-wizard-290-ova_{context}"]

= Creating an Open Virtualization Appliance (OVA) migration plan by using the MTV wizard

You can migrate Open Virtual Appliance (OVA) files that were created by {vmw} vSphere by using the {project-full} plan creation wizard.

The wizard is designed to lead you step-by-step in creating a migration plan.

[WARNING]
====
Do not include virtual machines with guest-initiated storage connections, such as Internet Small Computer Systems Interface (iSCSI) connections or Network File System (NFS) mounts. These require either additional planning before migration or reconfiguration after migration.

This prevents concurrent disk access to the storage the guest points to.
====

include::snip_plan-limits.adoc[]

[IMPORTANT]
====
When you click *Create plan* in the *Review and create* page of the wizard, {project-first} validates your plan. If everything is OK, the *Plan details* page for your plan opens. This page contains settings that do not appear in the wizard itself, but are important. Be sure to read and follow the instructions for this page carefully even though it is outside the plan creation wizard. The page can be opened later, any time before you run the plan, so you can come back to it if needed.
====

.Prerequisites

* Have an OVA source provider and a {virt} destination provider. For more information, see xref:adding-source-provider_ova[Adding an Open Virtual Appliance (OVA) source provider] or xref:adding-source-provider_dest_ova[Adding {a-virt} destination provider].

.Procedure

. In the {ocp} web console, click *Migration for Virtualization > *Migration plans*.
. Click *Create plan*.
+
The *Create migration plan* wizard opens.
+
// General page
. In the *General* page, specify the following fields:

* *Plan name*: Enter a name.
* *Plan project*: Select from the list.
* *Source provider*: Select from the list.
* *Target provider*: Select from the list.
* *Target project*: Select from the list.

. Click *Next*.
+
// Virtual machines page
. In the *Virtual machines* page, select the virtual machines you want to migrate and click *Next*.
+
// Network map page
. In the *Network map* page, choose one of the following options:

* *Use an existing network map*: Select an existing network map from the list.
+
If you choose this option, a copy of this map is attached to your plan and your plan is the _owner_ of that copy. Any changes you make to your copy do not affect the original plan or any copies of it that other users have.

* *Use a new network map*: Allows you to create a new network map by supplying the following data. This map is attached to this plan, which will then be considered to be its owner.

** *Source network* : Select from the list.
** *Target network* : Select from the list.
+
If needed, click *Add mapping* to add an additional mapping.
** *Network map name*: Enter a name or let {project-short} automatically generate a name for the network map.

. Click *Next*.
+
// Storage map page
. In the *Storage map* page, choose one of the following options:

* *Use an existing storage map*: Select an existing storage map from the list. 
+
These are storage maps available for all plans. If you choose this option, a copy of this map is attached to your plan and your plan is the _owner_ of that copy. Any changes you make to your copy do not affect the original plan or any copies of it that other users have.

* *Use new storage map*: Allows you to create one or two new storage maps by supplying the following data. These maps are attached to this plan, which is then their owner. For each map, specify the following.

** *Source storage* : Select from the list.
** *Target storage* : Select from the list.
+
If needed, click *Add mapping* to add an additional mapping.
** *Storage map name*: Enter a name or let {project-short} automatically generate a name for the network map.

. Click *Next*.
+
// Other settings page
. In the *Other settings (optional)* page, you have the option to change the *Transfer network* of your migration plan. 
+
The transfer network is the network used to transfer the VMs to {virt}. This is the default transfer network of the provider. 

** Verify that the transfer network is in the selected target namespace.

** To choose a different transfer network, select a different transfer network from the list.
** Optional: To configure an additional {ocp-short} network in the {ocp-short} web console, click *Networking > NetworkAttachmentDefinitions*.
+
To learn more about the different types of networks {ocp-short} supports, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-version}/html-single/networking/index#additional-networks-provided_understanding-multiple-networks[Additional Networks in OpenShift Container Platform].

** To adjust the maximum transmission unit (MTU) of the {ocp-short} transfer network, you must also change the MTU of the VMware migration network. For more information, see xref:selecting-migration-network-for-vmware-source-provider_vmware[Selecting a migration network for a VMware source provider].

. Click *Next*.
+
// Hooks page
In the *Hooks (optional)* page, you can add a pre-migration hook, a post-migration hook, or both types of migration hooks. All are optional.

. To add a hook, select the appropriate *Enable hook* checkbox.
. Enter the *Hook runner image*.
. Enter the *Ansible playbook* of the hook in the window.
+
[NOTE]
====
You cannot include more than one pre-migration hook or more than one post-migration hook in a migration plan.
====

. Click *Next*.
+
// Review and create page
. In the *Review and Create* page, review the information displayed.
. Edit any item by doing the following:

.. Click its *Edit step* link.
+ The wizard opens to the page on which you defined the item.
.. Edit the item.
.. Either click *Next* to advance to the next page of the wizard or click *Skip to review* to return directly to the *Review and create* page.

. When you finish reviewing the details of the plan, click *Create plan*. {project-short} validates your plan. 
. After you correct all problems, click *Skip to review* and then click *Create plan*.
+
When your plan is validated, the *Plan details* page for your plan opens.
+ 
Your plan appears in the table in the *Plans* page and you can run it from that page.