// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-operator_{context}"]
ifdef::web[]
= Installing the {operator-name} by using the {ocp} web console

You can install the {operator-name} by using the {ocp} web console.
endif::[]
ifdef::cli[]
= Installing the {operator-name} from the command line interface

You can install the {operator-name} from the command line interface (CLI).

ifeval::["{build}" == "upstream"]
If you are installing {project-short} on a Kubernetes cluster, you should disable TLS when you create the `ForkliftController` CR.
endif::[]
endif::[]

.Prerequisites

ifeval::["{build}" == "downstream"]
* {virt} Operator installed.
endif::[]
ifeval::["{build}" == "upstream"]
* Operator Lifecycle Manager (OLM) installed.
+
OLM is installed by default on {ocp} 4. To install OLM on other Kubernetes deployments, see link:https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/install/install.md[Installing OLM].
endif::[]
* You must be logged in as a user with `cluster-admin` permissions.

.Procedure

ifdef::web[]
. In the {ocp} web console, click *Operators* -> *OperatorHub*.
. Use the *Filter by keyword* field to search for *{operator}*.
ifeval::["{build}" == "upstream"]
+
[NOTE]
====
The {operator-name} is a Community Operator. Red Hat does not support Community Operators.
====
endif::[]
. Click the {operator-name} and then click *Install*.
. On the *Install Operator* page, click *Install*.
. Click *Operators* -> *Installed Operators* to verify that the {operator-name} appears in the *{namespace}* project with the status *Succeeded*.
. Click the {operator-name}.
. Under *Provided APIs*, locate the *ForkliftController*, and click *Create Instance*.
. Click *Create*.
. Click *Workloads* -> *Pods* to verify that the {project-short} pods are running.
endif::[]
ifdef::cli[]

. Create the +{namespace}+ project:
+
[source,terminal,subs="attributes+"]
----
$ {oc} create namespace {namespace}
----

ifeval::["{build}" == "upstream"]
. Create a `CatalogSource` CR:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | kubectl apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: konveyor-forklift
  namespace: {namespace}
spec:
  displayName: Konveyor Forklift Operator
  publisher: Red Hat
  sourceType: grpc
  image: quay.io/konveyor/forklift-operator-index:latest
EOF
----
endif::[]

. Create an `OperatorGroup` CR:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
  namespace: {namespace}
spec:
  targetNamespaces:
    - {namespace}
EOF
----

. Create a `Subscription` CR for the Operator:
ifeval::["{build}" == "upstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {operator}
  namespace: {namespace}
spec:
  channel: development
  installPlanApproval: Automatic
  name: {operator}
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "konveyor-forklift-operator.v{project-z-version}"
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {operator}
  namespace: {namespace}
spec:
  channel: release-v{project-z-version}
  installPlanApproval: Automatic
  name: {operator}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "mtv-operator.v{project-z-version}"
EOF
----
endif::[]

. Create a `ForkliftController` CR:
ifeval::["{build}" == "upstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: {namespace}
spec:
  feature_ui: false <1>
  feature_validation: true <1>
  inventory_tls_enabled: false <1>
  validation_tls_enabled: false <1>
  ui_tls_enabled: false <1>
  olm_managed: true <2>
EOF
----
<1> Disable SSL/TLS for Kubernetes clusters.
<2> For {ocp} clusters.
endif::[]
ifeval::["{build}" == "downstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: {namespace}
spec:
  olm_managed: true
EOF
----
endif::[]

. Verify that the {project-short} pods are running:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get pods -n {namespace}
----
+
.Example output
----
NAME                                  READY  STATUS   RESTARTS  AGE
forklift-controller-788bdb4c69-mw268  2/2    Running  0         2m
forklift-operator-6bf45b8d8-qps9v     1/1    Running  0         5m
forklift-ui-7cdf96d8f6-xnw5n          1/1    Running  0         2m
----
endif::[]
