// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-operator_{context}"]
ifdef::web[]
= Installing the {operator-name} by using the {ocp} web console

You can install the {operator-name} by using the {ocp} web console.
endif::[]
ifdef::cli[]
= Installing the {operator-name} from the command line interface

You can install the {operator-name} from the command line interface (CLI).
endif::[]

.Prerequisites

* {ocp} {ocp-version} installed.
* {virt} Operator installed.
* You must be logged in as a user with `cluster-admin` permissions.

.Procedure

ifdef::web[]
. In the {ocp} web console, click *Operators* -> *OperatorHub*.
. Use the *Filter by keyword* field to search for *{operator}*.
ifeval::["{build}" == "upstream"]
+
[NOTE]
====
The {operator-name} is a Community Operator. Red Hat does not support Community Operators.
====
endif::[]
. Click the {operator-name} and then click *Install*.
. On the *Install Operator* page, click *Install*.
. Click *Operators* -> *Installed Operators* to verify that the {operator-name} appears in the *{namespace}* project with the status *Succeeded*.
. Click the {operator-name}.
. Under *Provided APIs*, locate the *ForkliftController*, and click *Create Instance*.
. Click *Create*.
. Click *Workloads* -> *Pods* to verify that the {project-short} pods are running.
endif::[]
ifdef::cli[]

. Create the {namespace} project:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {namespace}
EOF
----

. Create an `OperatorGroup` CR called `migration`:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
  namespace: {namespace}
spec:
  targetNamespaces:
    - {namespace}
EOF
----

. Create a `Subscription` CR for the Operator:
ifeval::["{build}" == "upstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {operator}
  namespace: {namespace}
spec:
  channel: development
  installPlanApproval: Automatic
  name: {operator}
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "konveyor-forklift-operator.v2.0.0-beta.0"
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {operator}
  namespace: {namespace}
spec:
  channel: release-v2.0.0-beta
  installPlanApproval: Automatic
  name: {operator}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "mtv-operator.v2.0.0-beta.1"
EOF
----
endif::[]

. Create a `ForkliftController` CR:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: {namespace}
spec:
  olm_managed: true
EOF
----

. Verify that the {project-short} pods are running:
+
[source,terminal,subs="attributes+"]
----
$ oc get pods -n {namespace}
----
+
.Example output
----
NAME                                  READY  STATUS   RESTARTS  AGE
forklift-controller-788bdb4c69-mw268  2/2    Running  0         2m
forklift-operator-6bf45b8d8-qps9v     1/1    Running  0         5m
forklift-ui-7cdf96d8f6-xnw5n          1/1    Running  0         2m
----
endif::[]
