// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="known-issues_{context}"]
= Known issues

This section describes known issues and mitigations.

.Network map displays a `Destination network not found` error

If the network map remains in a `NotReady` state and the `NetworkMap` CR manifest displays a `Destination network not found` error, the cause is a missing network attachment definition. You must create a link:https://docs.openshift.com/container-platform/{ocp-version}/virt/virtual_machines/vm_networking/virt-attaching-vm-multiple-networks.html#virt-creating-network-attachment-definition[network attachment definition] for each additional destination network before you create the network map. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1971259[*BZ#1971259*])

.Warm migration gets stuck during third precopy

Warm migration uses changed block tracking snapshots to copy data during the precopy stage. The snapshots are created at one-hour intervals by default. When a snapshot is created, its contents are copied to the destination cluster. However, when the third snapshot is created, the first snapshot is deleted and the block tracking is lost. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1969894[*BZ#1969894*])

You can do one of the following to mitigate this issue:

* Start the cutover stage no more than one hour after the precopy stage begins so that only one internal snapshot is created.
* Increase the snapshot interval in the `vm-import-controller-config` config map to `720` minutes:
+
[source,terminal]
----
$ oc patch configmap/vm-import-controller-config \
  -n openshift-cnv -p '{"data": \
  {"warmImport.intervalMinutes": "720"}}'
----

