// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="known-issues-2-9_{context}"]
= Known issues

{project-first} 2.9 has the following known issues:

.Persistent volume claim name template does not support the `shared` field
The persistent volume claim (PVC) name template in {project-short} user interface does not support the `shared` field to name volumes shared by multiple virtual machines. link:https://issues.redhat.com/browse/MTV-2721[(MTV-2721)]

.VMware guest virtual machines running Red Hat Enterprise Linux v6.0 cannot boot in {project-short}
VMware guest VMs running Red Hat Enterprise Linux (RHEL) v6.0 cannot boot into operating system (OS) because the `virtio` disk of RHEL 6.0 requires the `virtio-transitional` device. link:https://issues.redhat.com/browse/MTV-1895[(MTV-1895)]

For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12472621[Known Issues] in Jira.
