// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_mod-docs-content-type: REFERENCE
[id="known-issues-2-11_{context}"]
= Known issues

[role="_abstract"]
{project-first} 2.11 has the following known issues.

VMware migrations fail when the disk count exceeds the ESXi host LUN ID limit::

VMware migrations with many disks fail if the disk count exceeds the host limit for discoverable SCSI LUN IDs.
+ 
To work around this problem, increase the `Disk.MaxLUN` value on each ESXi host to support discovery of a higher number of LUN IDs during migrations.
+
link:https://issues.redhat.com/browse/MTV-4719[MTV-4719]

Live migration support limit in custom namespaces with host providers::

Host providers in custom namespaces have restricted permissions that prevent {project-short} from accessing live migration resources. As a consequence, {project-short} provides limited support for live migration in these namespaces.
+
To work around this problem, use the default host provider or create a provider with an appropriate access token.
+
link:https://issues.redhat.com/browse/MTV-3347[MTV-3347]

Forklift console plugin fails to load on IPv6-only {ocp-short} clusters::

When {project-short} is deployed on an IPv6-only {ocp-short} cluster, an incorrect API endpoint prevents the `forklift-console` plugin from serving a valid plugin manifest. The {project-short} extension to the {ocp} web console displays the error `Failed to get a valid plugin manifest from /api/plugins/forklift-console-plugins/`.
+
As a consequence, while the `forklift-ui-plugin` pod runs successfully, the console plugin cannot load. This prevents access to the {project-short} user interface in the {ocp-short} web console.
+
This issue applies to all IPv6-only cluster deployments with {ocp-short} 4.19.7 and CNV 4.19.1. This issue was first observed in {project-short} version 2.9.1 and continues to exist in {project-short} version 2.11.
+
To work around this problem, deploy {project-short} on dual-stack or IPv4 clusters.
+
link:https://issues.redhat.com/browse/MTV-3116[MTV-3116]

Incorrect labeling of inactive migration plans::

Inactive migration plans are incorrectly labeled as `Running` when `max_vms_inflight` exceeds the total number of disks per migration. As a consequence, all migration plans appear to be `Running` in the user interface.
+
No known workaround exists.
+
link:https://issues.redhat.com/browse/MTV-1736[MTV-1736]

Migration between {ocp-short} namespaces causes MAC address collisions::

During migration between {ocp-short} namespaces in a cluster, MAC address collisions occur. As a consequence, VM creation fails.
+
To work around this problem, disable the `KubeMacPool`. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/virtualization/networking#virt-managing-kubemacpool-cli_virt-using-mac-address-pool-for-vms[Managing KubeMacPool by using the CLI] in the {ocp-short} documentation.
+
link:https://issues.redhat.com/browse/MTV-2446[MTV-2446]

{vmw} vSphere 6 or 7 migration fails on FIPS-enabled clusters::

In {project-short} 2.11.0, an update to Golang 1.25 causes a connection failure. This occurs on FIPS-enabled clusters with {vmw} vSphere 6 or 7 due to unsupported TLS 1.2 with EMS. As a consequence, users cannot migrate {vmw} vSphere 6 or 7 VMs to a FIPS-compliant cluster.
+
To work around this problem, disable FIPS mode on the cluster. Alternatively, use a {vmw} vSphere version that supports TLS 1.2 with EMS to migrate VMs.
+
link:https://issues.redhat.com/browse/MTV-4411[MTV-4411]

Second migration plan with shared RDM disks fails when shared disk migration is disabled::

You might migrate two VMs with shared RDM disks by using `copyoffload` in separate migration plans. If you disable shared disk migration, the second migration plan fails at the `ImageConversion` step. This occurs after successfully migrating the first VM with shared disk migration enabled.
+
The second plan incorrectly creates two populate pods, one for the operating system disk and one for the shared RDM disk. The plan should create only the operating system disk populate pod. As a consequence, the second migration fails.
+
No known workaround exists.
+
link:https://issues.redhat.com/browse/MTV-4549[MTV-4549]

VDDK image only in `openshift-mtv` namespace::

When you upload a {vmw} Virtual Disk Development Kit (VDDK) init image, the image URL is located in the `openshift-mtv` namespace. If you create a provider in a different namespace, an error occurs when pulling the image. As a consequence, the image pull fails.
+
No known workaround exists.
+
link:https://issues.redhat.com/browse/MTV-3673[MTV-3673]

Fibre Channel (FC) protocol VM migration fails to identify existing FC host objects in Infinibox::

Fibre Channel (FC) protocol VM migration fails to identify existing FC host objects in Infinibox due to an incorrect adapter ID comparison. As a consequence, FC protocol VM migration fails to identify existing FC hosts, causing volume creation failure due to an incorrect `port_name`.
+
No known workaround exists.
+
link:https://issues.redhat.com/browse/MTV-4338[MTV-4338]

