// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="known-issues-2-7_{context}"]
= Known issues

{project-first} 2.7 has the following known issues:

.`Select Migration Network` from the endpoint type `ESXi` displays multiple incorrect networks

When you choose `Select Migration Network`, from the endpoint type of `ESXi`, multiple incorrect networks are displayed. link:https://issues.redhat.com/browse/MTV-1291[(MTV-1291)]

// secure boot issue - (MTV-1548)
include::snip_secure_boot_issue.adoc[]

include::snip_measured_boot_windows_vm.adoc[]

.Network and Storage maps in the UI are not correct when created from the command line

When creating *Network* and *Storage* maps from the UI, the correct names are not shown in the UI. link:https://issues.redhat.com/browse/MTV-1421[(MTV-1421)]

.Migration fails with module `network-legacy` configured in RHEL guests

Migration fails if the module configuration file is available in the guest and the `dhcp-client` package is not installed, returning a `dracut module 'network-legacy' will not be installed, because command 'dhclient' could not be found` error. link:https://issues.redhat.com/browse/MTV-1615[(MTV-1615)]
