// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="known-issues-2-9_{context}"]
= Known issues

{project-first} 2.9 has the following known issues:

.Persistent volume claim name template does not support the `shared` field


The persistent volume claim (PVC) name template in the {project-short} user interface does not support the `shared` field to name volumes shared by multiple virtual machines. link:https://issues.redhat.com/browse/MTV-2721[(MTV-2721)]

.VMware guest virtual machines running Red Hat Enterprise Linux v6.0 cannot boot in {project-short}

VMware guest VMs running Red Hat Enterprise Linux (RHEL) v6.0 cannot boot into the operating system (OS) because the `virtio` disk of RHEL 6.0 requires the `virtio-transitional` device. link:https://issues.redhat.com/browse/MTV-1895[(MTV-1895)]

.Migration plan of virtual machines with NVMe disks hangs in {project-short}

When you select virtual machines (VMs) that use non-volatile memory express (NVMe) disks for creating a migration plan, the plan does not display an error but the migration stalls after the *DiskAllocation* phase because the migration of VMs with NVMe disks is not currently supported. link:https://issues.redhat.com/browse/MTV-2703[(MTV-2703)]

.Source storage is not mapped in the {project-short} user interface for {ocp-short} to {ocp-short} migration

When you select the storage mapping in the plan for a virtual machine for an {ocp-short} to {ocp-short} migration, and update the source storage on the *Storage Maps* page, {project-short} displays a `SourceStorageNotValid` error. link:https://issues.redhat.com/browse/MTV-2784[(MTV-2784)]

.Migration of VMware virtual machine from {ocp-short} to {ocp-short} cluster stalls due to changed name 
When you migrate a VMware virtual machine (VM) to an {ocp-short} cluster, the VM name is modified. When you try to migrate the VM again from the {ocp-short} cluster to another {ocp-short} cluster, the plan hangs with an `invalid value` error for the VM name. link:https://issues.redhat.com/browse/MTV-2810[(MTV-2810)]

.TPM device of a virtual machine uses a different persistent-state PVC after {ocp-short} to {ocp-short} migration 

When you migrate a virtual machine (VM) with trusted platform module (TPM) from {ocp-short} to {ocp-short}, the VM uses a new persistent volume claim (PVC) that is created for the persistent-state TPM device after migration. link:https://issues.redhat.com/browse/MTV-2838[(MTV-2838)]

.{ocp-short} to {ocp-short} migration of virtual machines with pre-migration or post-migration hooks fail

Cold migration of virtual machines (VMs) from an {ocp-short} cluster to another {ocp-short} cluster fails if the migration plan contains a pre-migration or a post-migration hook. link:https://issues.redhat.com/browse/MTV-2894[(MTV-2894)]

.VDDK image upload failure prevents the creation of VMware provider in the {project-short} user interface 

When you upload a VMware virtual disk development kit (VDDK) image to the service inventory in the {project-short} user interface (UI), the upload fails with a `Forbidden` error. This prevents you from creating a VDDK directly in the UI. You can create a VDDK for virtual disk transfers by following the instructions in link:https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.8/html/installing_and_using_the_migration_toolkit_for_virtualization/prerequisites_mtv#creating-vddk-image_mtv[Creating a VDDK image]. link:https://issues.redhat.com/browse/MTV-2888[(MTV-2888)]

For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12472621[Known Issues] in Jira.
