// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="known-issues-2-8_{context}"]
= Known issues

{project-first} 2.8 has the following known issues:

.Ubuntu 20.04 NIC name mapped to VMware virtual machines changes after migration

After migrating Ubuntu 20.04 VMware virtual machines (VM) to {virt} 4.15.6 using {project-short}, the  network interface card (NIC) name of the VMs is not preserved. This results in no network connectivity for the VM because the network interface gets a new name post migration to which the static IP address that you configured in the network plan is not assigned. link:https://issues.redhat.com/browse/MTV-1607[(MTV-1607)]

.PVCs are populated by incorrect disks
In cold migrations of virtual machines that have various bus interfaces (SATA, SCSI, IDE), the persistent volumes are not attached to the correct disk. This causes larger disks getting mapped to smaller persistent volumes. link:https://issues.redhat.com/browse/MTV-2093[(MTV-2093)]

.Error message says VM was not run, but it actually just does not have any static ip
. link:https://issues.redhat.com/browse/MTV-1458[(MTV-458)]