// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="known-issues-2-8_{context}"]
= Known issues

{project-first} 2.8 has the following known issues:

.The Ubuntu 20.04 NIC name mapped to VMware virtual machines changes after MTV migration

After migrating Ubuntu 20.04 VMware virtual machines (VM) to {virt} 4.15.6 using {project-short}, the  network interface card (NIC) name of the VMs is not preserved. This results in no network connectivity for the VM because the static IP address that you configured in the network plan is not assigned to the network interface that gets assigned a new name. link:https://issues.redhat.com/browse/MTV-1607[(MTV-1607)]

.VMNetworksNotMapped error occurs after creating a plan from the UI with the source provider set to OpenShift Virtualization

For migration plans created in the {project-short} web console, the name and type attributes of the bridge network is not populated in the network mapping YAML. This causes the migration plan to fail with `VMNetworksNotMapped` error.  

Workaround: Add the bridge network `name` and `type` values for the source provider in the network mapping YAML. link:https://issues.redhat.com/browse/MTV-1201[(MTV-1201)]

.Migration Plan for OCPv to OCPv missing the source namespace causing VMNetworkNotMapped

When you run migration plans created in the {project-short} web console for {virt} virtual machine migration, the source provider namespace is not generated in the network mapping YAML. This causes the migration plan to fail with `VMNetworksNotMapped` error. 
 
Workaround: Add the source provider `namespace` in the network mapping YAML. link:https://issues.redhat.com/browse/MTV-1297[(MTV-1297)]