// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_live-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="live-migration-workflow_{context}"]
= Live migration workflow

[role="_abstract"]
Live migration follows a unique workflow. Understanding how {project-first} orchestrates with {virt} helps you troubleshoot migration issues.

. Start: When you click *Start plan*, {project-short} initiates the migration plan. 
. PreHook: If you added a pre-migration hook, {project-short} runs it now.
. Create empty `DataVolumes`: {project-short} creates empty target `DataVolumes` in the target {virt} cluster. {virt} uses `KubeVirt` to handle the actual storage migration.
. Ensure resources: {project-short} copies all secrets or config maps that are mounted by a source VM to the target namespace.
. Create target VMs: {project-short} creates target VMs in a running state and creates a `VirtualMachineInstanceMigration` resource on each cluster. The VMs have a special `KubeVirt` annotation indicating to start them in migration target mode.
. Wait for state transfer: {project-short} waits for `KubeVirt` to handle the state transfer and for the destination VMs to report as ready. `KubeVirt` also handles the shutdown of the source VMs after the state transfer.
. PostHook: If you added a post-migration hook, {project-short} runs it now.
. Completed: {project-short} indicates that the migration is finished.
