// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_live-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="live-migration-limitations_{context}"]
= Limitations of live migration

[role="_abstract"]
Perform a live migration works to migrate virtual machines (VMs) between {virt} clusters or between namespaces on the same {virt} cluster with a minimum of downtime.

Limitations::

* Live migration is available *_only_* for migrations between {virt} clusters or between namespaces on the same {virt} cluster. It is not available for any other source provider, whether the provider is supported by {project-first} or not.
* Live migration does not establish connectivity between {virt} clusters. Establishing such connectivity is the responsibility of the cluster administrator.
* Live migration does not migrate resources unrelated to VMs, such as services, routes, or other application components, that may be necessary for application availability after a migration.

