// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="migration-plan-options-ui_{context}"]
= Migration plan options

On the *Plans for virtualization* page of the {ocp} web console, you can click the {kebab} beside a migration plan to access the following options:

* *Edit Plan*: Edit the details of a migration plan. You cannot edit a migration plan while it is running or after it has completed successfully.
* *Start migration*: Active only if relevant.
* *Restart migration*: Restarts a migration that was interrupted. Before choosing this option, make sure there are no error messages. If there are, you need to edit the plan.
* *Cutover*: Warm migrations only. Active only if relevant.
* *Cancel scheduled cutover*: Cancel a scheduled cutover migration for a warm migration plan. Active only if relevant.

* *Duplicate Plan*: Create a new migration plan with the same virtual machines (VMs), parameters, mappings, and hooks as an existing plan. You can use this feature for the following tasks:

** Migrate VMs to a different namespace.
** Edit an archived migration plan.
** Edit a migration plan with a different status, for example, failed, canceled, running, critical, or ready.

* *Archive Plan*: Delete the logs, history, and metadata of a migration plan. The plan cannot be edited or restarted. It can only be viewed.
+
[NOTE]
====
*Archive Plan* is irreversible. However, you can duplicate an archived plan.
====

* *Delete Plan*: Permanently remove a migration plan. You cannot delete a running migration plan.
+
[NOTE]
====
*Delete Plan* is irreversible.

Deleting a migration plan does not remove temporary resources. To remove temporary resources, archive the plan first before deleting it.
====


