// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="mtv-overview-page_{context}"]
= The MTV Overview page

If you have Administrator privileges, you can access the *Overview* page by clicking *Migration for Virtualization > Overview* in the {ocp} web console.

The *Overview* page has 4 tabs:

* Overview
* YAML
* Health
* Settings

[id="overview-tab_{context}"]
== Overview tab

The *Overview* tab is designed to let you create providers quickly and to make it easier for you to find system-wide information:

* In the upper-right pane, following the *Welcome* message, are buttons that let you open the *Create provider* UI for each vendor ({vmw}, {rhv-full}, OpenStack, OVA, and {virt}).

//Confirm time and list or kebab
* In the center-left pane is a "donut" chart named *Virtual machines*. This chart shows the number of running, failed, and succeeded virtual machine migrations that {project-short} ran for the time interval that you select. You can choose a different interval by clicking the list in the upper-right corner of the pane. You can choose a different interval by clicking the list. Options: 7 days, 31 days, 24 hours.

* In the center-right pane is an area chart named *Migration history*. This chart shows the number of migrations that succeeded, failed, or were running during the interval shown in the title of the chart. You can choose a different interval by clicking the {kebab} in the upper-right corner of the pane. Options: 7 days, 31 days, 24 hours.

//Confirm time and list or kebab
* In the lower-left pane is a "donut" chart named *Migration plans*. By default, this chart shows the number of running, failed, succeeded, or canceled migration plans that {project-short} ran for the time interval that you select. You can choose a different interval by clicking the list in the upper-right corner of the pane. List options are: 7 days, 31 days, 24 hours. You can also see the number of plans that were not started, cannot be started, are incomplete, archived, paused, or have an unknown status by clicking the *Show all plans* link.

[NOTE]
====
Since a single migration might involve many virtual machines, the number of migrations performed using {project-short} might vary significantly from the number of migrated virtual machines.
====

* In the lower-right pane is a table named *{project-short} health*. This table lists all of the {project-short} pods, starting with the most important one, `forklift-controller`. The remaining pods are listed in alphabetical order. If there are more pods than can be displayed, the *View all* link is active. Clicking the link opens the *Health* tab. For each pod, the status and creation time of the pod are listed and there is a link to the logs of the pod.


[id="overview-yaml-tab_{context}"]
== YAML tab

The *YAML* tab displays the `ForkliftController` custom resource (CR) that defines the operation of the {project-short} Operator. You can modify the CR in this tab.

[id="overview-health-tab_{context}"]
== Health tab

The *Health* tab has two panes:

* In the upper pane, there is a table named *MTV Health*. It lists all the {project-short} pods, starting with the most important one, `forklift-controller`. The remaining pods are listed in alphabetical order. For each pod, the status and creation time of the pod are listed and there is a link to the logs of the pod.

* In the lower pane, is a table named *Conditions*. It lists the following possible statuses of the {project-short} Operator, whether the status is true or false, a brief description, and the last time the condition was updated. A green checkmark is used if a status is true, a red minus sign is used if it is false.

** Failure: Last failure. A red minus sign means that no failure occurred since deployment.
** Running: Whether the Operator is currently running and waiting for the next reconciliation.
** Success: Last successful reconciliation.

[id="overview-settings-tab_{context}"]
== Settings tab

The table that follows describes the settings that are visible in the *Settings* tab, their default values, and other possible values which can be set or chosen, if needed.

[cols="1,1,1,1",options="header"]
.{project-short} settings
|===
|Setting |Description |Default value |Additional values

|Maximum concurrent VM migrations
a|Varies with provider as follows:

* For all migrations except OVA or VMware migrations: The maximum number of disks that {project-short} can transfer simultaneously.
* For OVA migrations: The maximum number of VMs that {project-short} can migrate simultaneously.
* For VMware migrations, the setting has the following meanings:
** Cold migration:

*** To local {virt}: VMs for each ESXi host that can migrate simultaneously.
*** To remote {virt}: Disks for each ESXi host that can migrate simultaneously.

** Warm migration: Disks for each ESXi host that can migrate simultaneously.
+
See xref:max-concurrent-vms_{context}[Configuring the controller_max_vm_inflight parameter] for a detailed explanation of this setting.
|20
|Adjustable by clicking the *+* and *-* keys to set a different value.

|Controller CPU limit
|The CPU limit that is allocated to the main controller container, in milliCPUs (m).
|500 m.
|Adjustable by choosing another value from the list. Options: 200 m, 500 m, 2000 m, 8000 m.

|Controller memory limit
|The memory limit that is allocated to the main controller container in mebibytes (Mi).
|800 Mi.
|Adjustable by choosing another value from the list. Options: 200 Mi, 500 Mi, 2000 Mi, 8000 Mi.

|Precopy internal
|The interval in minutes at which a new snapshot is requested before initiating a warm migration.
|60 minutes.
|Adjustable by choosing another value from the list. Options: 5 minutes, 30 minutes, 60 minutes, 60 minutes.

|Snapshot polling interval
|The interval in seconds between which the system checks the status of snapshot creation or removal during a warm migration.
|10 seconds.
|Adjustable by choosing another value from the list. Options: 1 second, 5 seconds, 10 seconds, 60 seconds.

// Not included in the mockup provided to me. Verifying its status.
// |Must gather cleanup after (hours)
// |The duration for retaining `must gather` reports before they are automatically deleted.
// |Disabled
|===









