// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_troubleshooting-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="mtv-workflow_{context}"]
= High-level migration workflow

[role="_abstract"]
The high-level workflow shows the migration process from the point of view of the user:

// ifeval::["{build}" == "downstream"]
// .High-level workflow
// image::136_OpenShift_Migration_Toolkit_0121_mtv-workflow.svg[{project-short} workflow]
// endif::[]
// ifeval::["{build}" == "upstream"]
// .High-level workflow
// image::136_Upstream_Migration_Toolkit_0121_mtv-workflow.svg[{project-short} workflow]
// endif::[]

// The workflow describes the following steps:

. You create a source provider, a target provider, a network mapping, and a storage mapping.
. You create a `Plan` custom resource (CR) that includes the following resources:

* Source provider
* Target provider, if {project-short} is not installed on the target cluster
* Network mapping
* Storage mapping
* One or more virtual machines (VMs)

. You run a migration plan by creating a `Migration` CR that references the `Plan` CR.
+
If you cannot migrate all the VMs for any reason, you can create multiple `Migration` CRs for the same `Plan` CR until all VMs are migrated.

. For each VM in the `Plan` CR, the `Migration Controller` service records the VM migration progress in the `Migration` CR.
. Once the data transfer for each VM in the `Plan` CR completes, the `Migration Controller` service creates a `VirtualMachine` CR.
+
When all VMs have been migrated, the `Migration Controller` service updates the status of the `Plan` CR to `Completed`. The power state of each source VM is maintained after migration.
