// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="source-vm-prerequisites_{context}"]
= Source virtual machine prerequisites

The following prerequisites apply to all migrations:

* ISO images and CD-ROMs are unmounted.
* Each NIC contains either an IPv4 address or an IPv6 address, although a NIC may use both.
* The operating system of each VM is certified and supported as a guest operating system for conversions.

[NOTE]
====
You can check that the operating system is supported by referring to the table in link:https://access.redhat.com/articles/1351473[Converting virtual machines from other hypervisors to KVM with virt-v2v]. See the columns of the table that refer to RHEL 8 hosts and RHEL 9 hosts.
====

* VMs that you want to migrate with MTV 2.6._z_ run on RHEL 8.
* VMs that you want to migrate with MTV 2.7._z_ run on RHEL 9.
* The name of a VM must not contain a period (`.`). {project-first} changes any period in a VM name to a dash (`-`).
* The name of a VM must not be the same as any other VM in the {virt} environment.
+
include::snip_dualboot_vm.adoc[]
+
[NOTE]
====
{project-full} automatically assigns a new name to a VM that does not comply with the rules.

{project-full} makes the following changes when it automatically generates a new VM name:

* Excluded characters are removed.
* Uppercase letters are switched to lowercase letters.
* Any underscore (`_`) is changed to a dash (`-`).

This feature allows a migration to proceed smoothly even if someone enters a VM name that does not follow the rules.
====

include::snip_secure_boot_issue.adoc[]

include::snip_measured_boot_windows_vm.adoc[]
