// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="about-rego-files_{context}"]
= About Rego files

Validation rules are written in link:https://www.openpolicyagent.org/docs/latest/policy-language/[Rego], the Open Policy Agent (OPA) native query language. The rules are stored as `.rego` files in the `/usr/share/opa/policies/io/konveyor/forklift/<provider>` directory of the `Validation` pod.

Each validation rule is defined in a separate `.rego` file and tests for a specific condition. If the condition evaluates as `true`, the rule adds a `{“category”, “label”, “assessment”}` hash to the `concerns`. The `concerns` content is added to the `concerns` key in the inventory record of the VM. The web console displays the content of the `concerns` key for each VM in the provider inventory.

The following `.rego` file example checks for distributed resource scheduling enabled in the cluster of a VMware VM:

.drs_enabled.rego example
[source,terminal]
----
package io.konveyor.forklift.vmware <1>

has_drs_enabled {
    input.host.cluster.drsEnabled <2>
}

concerns[flag] {
    has_drs_enabled
    flag := {
        "category": "Information",
        "label": "VM running in a DRS-enabled cluster",
        "assessment": "Distributed resource scheduling is not currently supported by OpenShift Virtualization. The VM can be migrated but it will not have this feature in the target environment."
    }
}
----
<1> Each validation rule is defined within a package. The package namespaces are `io.konveyor.forklift.vmware` for VMware and `io.konveyor.forklift.ovirt` for {rhv-full}.
<2> Query parameters are based on the `input` key of the `Validation` service JSON.
