// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: context
[id="mtv-resources-and-services_{context}"]
= {project-short} custom resources and services

{The} {project-first} is provided as an {ocp} Operator. It creates and manages the following custom resources (CRs) and services.

.{project-short} custom resources

* `Provider` CR stores attributes that enable {project-short} to connect to and interact with the source and target providers.
* `NetworkMapping` CR maps the networks of the source and target providers.
* `StorageMapping` CR maps the storage of the source and target providers.
* `Plan` CR contains a list of VMs with the same migration parameters and associated network and storage mappings.
* `Migration` CR runs a migration plan.
+
Only one `Migration` CR per migration plan can run at a given time. You can create multiple `Migration` CRs for a single `Plan` CR.

.{project-short} services

* The `Inventory` service performs the following actions:
** Connects to the source and target providers.
** Maintains a local inventory for mappings and plans.
** Stores VM configurations.
** Runs the `Validation` service if a VM configuration change is detected.

* The `Validation` service checks the suitability of a VM for migration by applying rules.
* The `Migration Controller` service orchestrates migrations.
+
When you create a migration plan, the `Migration Controller` service validates the plan and adds a status label. If the plan fails validation, the plan status is `Not ready` and the plan cannot be used to perform a migration. If the plan passes validation, the plan status is `Ready` and it can be used to perform a migration. After a successful migration, the `Migration Controller` service changes the plan status to `Completed`.

* The `Populator Controller` service orchestrates disk transfers using Volume Populators.

* The `Kubevirt Controller` and `Containerized Data Import (CDI) Controller` services handle most technical operations.

