// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="mtv-resources-and-services_{context}"]
= {project-short} custom resources and services

{The} {project-first} is provided as an {ocp} Operator. It creates and manages the following custom resources (CRs) and services.

.{project-short} custom resources

* `Provider` CR stores attributes that enable {project-short} to connect to and interact with the source and target providers.
* `NetworkMapping` CR maps the networks of the source and target providers.
* `StorageMapping` CR maps the storage of the source and target providers.
* `Provisioner` CR stores the configuration of the storage provisioners, such as supported volume and access modes.
* `Plan` CR contains a list of VMs with the same migration parameters and associated network and storage mappings.
* `Migration` CR runs a migration plan.
+
Only one `Migration` CR per migration plan can run at a given time. You can create multiple `Migration` CRs for a single `Plan` CR.

.{project-short} services

* `Provider Inventory` service:
** Connects to the source and target providers.
** Maintains a local inventory for mappings and plans.
** Stores VM configurations.
** Runs the `Validation` service if a VM configuration change is detected.

* `Validation` service checks the suitability of a VM for migration by applying rules.

:FeatureName: The Validation service
include::technology-preview.adoc[leveloffset=+1]

* `User Interface` service:
** Enables you to create and configure {project-short} CRs.
** Displays the status of the CRs and the progress of a migration.

* `Migration Controller` service orchestrates migrations.
+
When you create a migration plan, the Migration Controller service validates the plan and adds a status label. If the plan fails validation, the plan status is `Not ready` and the plan cannot be used to perform a migration. If the plan passes validation, the plan status is `Ready` and it can be used to perform a migration. After a successful migration, the Migration Controller changes the plan status to `Completed`.

* `Virtual Machine Import Controller`, `Kubevirt Controller`, and `Containerized Data Import (CDI) Controller` services handle most technical operations.
