// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="mtv-workflow_{context}"]
= High-level migration workflow

The high-level workflow shows the migration process from the point of view of the user.

ifeval::["{build}" == "downstream"]
.High-level workflow
image::136_OpenShift_Migration_Toolkit_0121_mtv-workflow.svg[{project-short} workflow]
endif::[]

ifeval::["{build}" == "upstream"]
.High-level workflow
image::136_Upstream_Migration_Toolkit_0121_mtv-workflow.svg[{project-short} workflow]
endif::[]

The workflow describes the following steps:

. You create a source provider, a target provider, a network mapping, and a storage mapping.
. You create a migration plan that includes the following resources:
* Source provider
* Target provider
* Network mapping
* Storage mapping
* One or more VMs

. You run a migration plan by creating a `Migration` CR that references the migration plan. If a migration is incomplete, you can run a migration plan multiple times until all VMs are migrated.
. For each VM in the migration plan, the Migration Controller creates a `VirtualMachineImport` CR and monitors its status. When all VMs have been migrated, the Migration Controller sets the status of the migration plan to `Completed`. The power state of a source VM is maintained after migration.
