// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="mtv-performance-recommendation_{context}"]
= {project-short} performance recommendations

The purpose of this section is to share recommendations for efficient and effective migration of virtual machines (VMs) using {project-first}, based on findings observed through testing.

include::snip_performance.adoc[]

[id="mtv-performance-storage-network_{context}"]
== Ensure fast storage and network speeds

Ensure fast storage and network speeds, both for VMware and {ocp} (OCP) environments.

* To perform fast migrations, VMware must have fast read access to datastores.  Networking between VMware ESXi hosts should be fast, ensure a 10 GiB network connection, and avoid network bottlenecks.

** Extend the VMware network to the OCP Workers Interface network environment.

** It is important to ensure that the VMware network offers high throughput (10 Gigabit Ethernet) and rapid networking to guarantee that the reception rates align with the read rate of the ESXi datastore.

** Be aware that the migration process uses significant network bandwidth and that the migration network is utilized. If other services utilize that network, it may have an impact on those services and their migration rates.

** For example, 200 to 325 MiB/s was the average network transfer rate from the `vmnic` for each ESXi host associated with transferring data to the OCP interface.

[id="mtv-performance-datastore-read_{context}"]
== Ensure fast datastore read speeds to ensure efficient and performant migrations

Datastores read rates impact the total transfer times, so it is essential to ensure fast reads are possible from the ESXi datastore to the ESXi host.  


Example in numbers: 200 to 300 MiB/s was the average read rate for both vSphere and ESXi endpoints for a single ESXi server. When multiple ESXi servers are used, higher datastore read rates are possible.

[id="mtv-performance-endpoint-types_{context}"]
== Endpoint types 

{project-short} 2.6 allows for the following vSphere provider options:

* ESXi endpoint (inventory and disk transfers from ESXi), introduced in {project-short} 2.6

* vCenter Server endpoint; no networks for the ESXi host (inventory and disk transfers from vCenter)

* vCenter endpoint and ESXi networks are available (inventory from vCenter, disk transfers from ESXi).

When transferring many VMs that are registered to multiple ESXi hosts, using the vCenter endpoint and ESXi network is suggested.

[NOTE]
====
As of vSphere 7.0, ESXi hosts can label which network to use for NBD transport. This is accomplished by tagging the desired virtual network interface card (NIC) with the appropriate `vSphereBackupNFC` label.  When this is done, {project-short} will be able to utilize the ESXi interface for network transfer to Openshift as long as the worker and ESXi host interfaces are reachable.  This is especially useful when migration users may not have access to the ESXi credentials yet would like to be able to control which ESXi interface is used for migration. 

For more details, see: link:https://issues.redhat.com/browse/MTV-1230[({project-short}-1230)]
====

You can use the following ESXi command, which designates interface `vmk2` for NBD backup:

[source,terminal]
----
esxcli network ip interface tag add -t vSphereBackupNFC -i vmk2
----

[id="mtv-performance-bios-profile_{context}"]
== Set ESXi hosts BIOS profile and ESXi Host Power Management for High Performance

Where possible, ensure that hosts used to perform migrations are set with BIOS profiles related to maximum performance.  Hosts which use Host Power Management controlled within vSphere should check that `High Performance` is set.

Testing showed that when transferring more than 10 VMs with both BIOS and host power management set accordingly, migrations had an increase of 15 MiB in the average datastore read rate.

[id="mtv-performance-network-loads_{context}"]
== Avoid additional network load on VMware networks

You can reduce the network load on VMware networks by selecting the migration network when using the ESXi endpoint.

By incorporating a virtualization provider, {project-short} enables the selection of a specific network, which is accessible on the ESXi hosts, for the purpose of migrating virtual machines to OCP.  Selecting this migration network from the ESXi host in the {project-short} UI will ensure that the transfer is performed using the selected network as an ESXi endpoint.

It is imperative to ensure that the network selected has connectivity to the OCP interface, has adequate bandwidth for migrations, and that the network interface is not saturated.

In environments with fast networks, such as 10GbE networks, migration network impacts can be expected to match the rate of ESXi datastore reads.

[id="mtv-performance-concurrent-disk_{context}"]
== Control maximum concurrent disk migrations per ESXi host

Set the `MAX_VM_INFLIGHT MTV` variable to control the maximum number of concurrent VMs transfers allowed for the ESXi host. 

{project-short} allows for concurrency to be controlled using this variable; by default, it is set to 20.

When setting `MAX_VM_INFLIGHT`, consider the number of maximum concurrent VMs transfers are required for ESXi hosts. It is important to consider the type of migration to be transferred concurrently. Warm  migrations, which are defined by migrations of a running VM that will be migrated over a scheduled time.

Warm migrations use snapshots to compare and migrate only the differences between previous snapshots of the disk.  The migration of the differences between snapshots happens over specific intervals before a final cut-over of the running VM to {ocp-short} occurs. 

In {project-short} 2.6, `MAX_VM_INFLIGHT` reserves one transfer slot per VM, regardless of current migration activity for a specific snapshot or the number of disks that belong to a single vm. The total set by `MAX_VM_INFLIGHT` is used to indicate how many concurrent VM tranfers per ESXi host is allowed.

.Examples

* `MAX_VM_INFLIGHT = 20` and 2 ESXi hosts defined in the provider mean each host can transfer 20 VMs.

[id="mtv-performance-multiple-vms-concurrently_{context}"]
== Migrations are completed faster when migrating multiple VMs concurrently

When multiple VMs from a specific ESXi host are to be migrated, starting concurrent migrations for multiple VMs leads to faster migration times. 

Testing demonstrated that migrating 10 VMs (each containing 35 GiB of data, with a total size of 50 GiB) from a single host is significantly faster than migrating the same number of VMs sequentially, one after another. 

It is possible to increase concurrent migration to more than 10 virtual machines from a single host, but it does not show a significant improvement. 

.Examples

* *1 single disk VMs took 6 minutes, with migration rate of 100 MiB/s*

* *10 single disk VMs took 22 minutes, with migration rate of 272 MiB/s*

* *20 single disk VMs took 42 minutes, with migration rate of 284 MiB/s*

[NOTE]
====
From the aforementioned examples, it is evident that the migration of 10 virtual machines simultaneously is three times faster than the migration of identical virtual machines in a sequential manner.

The migration rate was almost the same when moving 10 or 20 virtual machines simultaneously.
====

[id="mtv-performance-multiple-hosts_{context}"]
== Migrations complete faster using multiple hosts

Using multiple hosts with registered VMs equally distributed among the ESXi hosts used for migrations leads to faster migration times.

Testing showed that when transferring more than 10 single disk VMS, each containing 35 GiB of data out of a total of 50G total, using an additional host can reduce migration time.

.Examples

* *80 single disk VMs, containing 35 GiB of data each, using a single host took 2 hours and 43 minutes, with a migration rate of 294 MiB/s.*

* *80 single disk VMs, containing 35 GiB of data each, using 8 ESXi hosts took 41 minutes, with a migration rate of 1,173 MiB/s.*

[NOTE]
====
From the aforementioned examples, it is evident that migrating 80 VMs from 8 ESXi hosts, 10 from each host, concurrently is four times faster than running the same VMs from a single ESXi host. 

Migrating a larger number of VMs from more than 8 ESXi hosts concurrently could potentially show increased performance. However, it was not tested and therefore not recommended.
====

[id="mtv-performance-multiple-migration-plans_{context}"]
== Multiple migration plans compared to a single large migration plan

The maximum number of disks that can be referenced by a single migration plan is 500. For more details, see link:https://issues.redhat.com/browse/MTV-1203[(MTV-1203)]. 

When attempting to migrate many VMs in a single migration plan, it can take some time for all migrations to start.  By breaking up one migration plan into several migration plans, it is possible to start them at the same time.

Comparing migrations of:

* 500 VMs using 8 ESXi hosts in 1 plan, `max_vm_inflight=100`, took 5 hours and 10 minutes.

* 800 VMs using 8 ESXi hosts with 8 plans, `max_vm_inflight=100`, took 57 minutes.

Testing showed that by breaking one single large plan into multiple moderately sized plans, for example, 100 VMS per plan, the total migration time can be reduced.

[id="mtv-performance-max-values-cold_{context}"]
== Maximum values tested for cold migrations

* Maximum number of ESXi hosts tested: 8
* Maximum number of VMs in a single migration plan: 500
* Maximum number of VMs migrated in a single test: 5000
* Maximum number of migration plans performed concurrently: 40
* Maximum single disk size migrated: 6 TB disk, which contained 3 TB of data
* Maximum number of disks on a single VM migrated: 50
* Highest observed single datastore read rate from a single ESXi server:  312 MiB/second
* Highest observed multi-datastore read rate using eight ESXi servers and two datastores: 1,242 MiB/second
* Highest observed virtual NIC transfer rate to an {ocp-name} worker: 327 MiB/second
* *Maximum migration transfer rate of a single disk: 162 MiB/second (rate observed when transferring nonconcurrent migration of 1.5 TB utilized data)*
* *Maximum cold migration transfer rate of the multiple VMs (single disk) from a single ESXi host: 294 MiB/s (concurrent migration of 30 VMs, 35/50 GiB used, from Single ESXi)*
* *Maximum cold migration transfer rate of the multiple VMs (single disk) from multiple ESXi hosts: 1173MB/s (concurrent migration of 80 VMs, 35/50 GiB used, from 8 ESXi servers, 10 VMs from each ESXi)*

[id="mtv-warm-migration-recommendations_{context}"]
== Warm migration recommendations

The following recommendations are specific to warm migrations:

[id="mtv-warm-migration-recommendations-disks-in-parallel_{context}"]
=== Migrate up to 400 disks in parallel

Testing involved migrating 200 VMs in parallel, with 2 disks each using 8 ESXi hosts, for a total of 400 disks. No tests were run on migration plans migrating over 400 disks in parallel, so it is not recommended to migrate over this number of disks in parallel.

[id="mtv-warm-migration-recommendations-effects-of-precopy-speed_{context}"]
=== Migrate up to 200 disks in parallel for the fastest rate

Testing was successfully performed on parallel disk migrations with 200, 300, and 400 disks. There was a decrease in the precopy migration rate, approximately 25%, between the tests migrating 200 disks and those migrating 300 and 400 disks.

Therefore, it is recommended to perform parallel disk migrations in groups of 200 or fewer, instead of 300 to 400 disks, unless a decline of 25% in precopy speed does not affect your cutover planning.

[id="mtv-warm-migration-recommendations-set-cutover-time_{context}"]
=== When possible, set cutover time to be immediately after a migration plan starts

To reduce the overall time of warm migrations, it is recommended to set the cutover to occur immediately after the migration plan is started. This causes {project-short} to run *only one* precopy per VM. This recommendation is valid, no matter how many VMs are in the migration plan.

[id="mtv-warm-migration-recommendations-increase-precopy-intevals_{context}"]
=== Increase precopy intervals between snapshots

If you are creating many migration plans with a single VM and have enough time between the migration start and the cutover, increase the value of the `controller_precopy_interval` parameter to between 120 and 240 minutes, inclusive. The longer setting will reduce the total number of snapshots and disk transfers per VM before the cutover.

[id="mtv-performance-max-values-warm_{context}"]
== Maximum values tested for warm migrations

* Maximum number of ESXi hosts tested: 8
* Maximum number of worker nodes: 12
* Maximum number of VMs in a single migration plan: 200
* Maximum number of total parallel disk transfers: 400, with 200 VMs, 6 ESXis, and a transfer rate of 667 MB/s
* Maximum single disk size migrated: 6 TB disk, which contained 3 TB of data
* Maximum number of disks on a single VM migrated: 3
* Maximum number of parallel disk transfers per ESXi host: 68
* *Maximum transfer rate observed of a single disk with no concurrent migrations: 76.5 MB/s*
* *Maximum transfer rate observed of multiple disks from a single ESXi host: 253 MB/s (concurrent migration of 10 VMs, 1 disk each, 35/50 GiB used per disk)*
* *Total transfer rate observed of multiple disks (210) from 8 ESXi hosts: 802 MB/s (concurrent migration of 70 VMs, 3 disks each, 35/50 GiB used per disk)*

[id="mtv-precommendations-vms-large-disks_{context}"]
== Recommendations for migrating VMs with large disks

The following recommendations are suggested for VMs with data on disk totaling to 1 TB or greater for each individual disk:

* Schedule appropriate maintenance windows for migrating large disk virtual machines (VMs). Such migrations are sensitive operations and may require careful planning of maintenance windows and downtime, especially during periods of lower storage and network activity.

* Check that no other migration activities or other heavy network or storage activities are run during those large virtual machine (VM) migrations. You should treat these large virtual machine migrations as a special case. During those migrations, prioritize {project-short} activities. Plan to migrate those VMs to a time when there are fewer activities on those VMs and related datastore.

* For large VMs with a high churn rate, which means data is frequently changed in amounts of 100 GB or more between snapshots, consider reducing the warm migration `controller_precopy_interval` from the default, which is 60 minutes. It is important to ensure that this process is started at least 24 hours before the scheduled cutover to allow for multiple successful precopy snapshots to complete. When scheduling the cutover, ensure that the maintenance window allows for sufficient time for the last snapshot of changes to be copied over and that the cutover process begins at the beginning of that maintenance window.

* In cases of particularly large single-disk VMs, where some downtime is possible, select cold migrations rather than warm migrations, especially in the case of large VM snapshots.

* Consider splitting data on particularly large disks to multiple disks, which enables parallel disk migration with {project-short} when warm migration is used.

* If you have large database disks with continuous writes of large amounts of data, where downtime and VM snapshots are not possible, it may be necessary to consider database vendor-specific replication options of the database data to target these specific migrations outside {project-short}. Please consult the vendor-specific options of your database if this case applies.

