// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_cold-warm-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="mtv-migration-speed-comparison_{context}"]
= Migration speed comparison

[role="_abstract"]
Compare cold and warm migration speeds to choose the best migration type for your workload. Both have similar transfer speeds, but warm migration runs in the background with hourly snapshots while cold migration requires VM shutdown.

Comparison::

* The observed speeds for the warm migration single disk transfer and disk conversion are approximately the same as for the cold migration.
* The benefit of warm migration is that the transfer of the snapshot happens in the background while the VM is powered *_on_*.
* The default snapshot time is taken every 60 minutes. If VMs change substantially, more data needs to be transferred than in cold migration when the VM is powered *_off_*.
* The cutover time, meaning the shutdown of the VM and last snapshot transfer, depends on how much the VM has changed since the last snapshot.

[NOTE]
====
Live migration reduces downtime even further than warm migration, but live migration is available only for migration between {virt} clusters or between namespaces on the same {virt} cluster. Therefore it is not included in the comparison above.
====
