// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="mtv-overview-page_{context}"]
= The MTV Overview page

The {project-first} *Overview* page displays system-wide information about migrations and a list of *Settings* you can change.

If you have Administrator privileges, you can access the *Overview* page by clicking *Migration* -> *Overview* in the {ocp} web console.

The *Overview* page has 3 tabs:

* Overview
* YAML
* Metrics

[id="overview-tab_{context}"]
== Overview tab

The *Overview* tab lets you see:

* Operator: The namespace on which the {project-short} Operator and the status of the Operator
* Pods: The name, status, and creation time of each pod
* Conditions: Status of the {project-short} Operator:

** Failure: Last failure. `False` indicates no failure since deployment.
** Running: Whether the Operator is currently running and waiting for the next reconciliation.
** Successful: Last successful reconciliation.

[id="yaml-tab_{context}"]
== YAML tab

The last manifest created or retrieved by the CLI is displayed. You can save, reload, or cancel your changes.

[id="metrics-tab_{context}"]
== Metrics tab

The *Metrics* tab lets you see:

* Migrations: The number of migrations performed using {project-short}:

** Total
** Running
** Failed
** Succeeded
** Canceled

* Virtual Machine Migrations:  The number of VMs migrated using {project-short}:

** Total
** Running
** Failed
** Succeeded
** Canceled

* Chart showing the number of running, failed, and succeeded migrations performed using {project-short} for each of the last 7 days

* Chart showing the number of running, failed, and succeeded virtual machine migrations performed using {project-short} for each of the last 7 days




