// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="known-issues-2-7_{context}"]
= Known issues

{project-first} 2.7 has the following known issues:

.`Select Migration Network` from the endpoint type `ESXi` displays multiple incorrect networks

When you choose `Select Migration Network`, from the endpoint type of `ESXi`, multiple incorrect networks are displayed. link:https://issues.redhat.com/browse/MTV-1291[(MTV-1291)]

// secure boot issue - (MTV-1548)
include::snip_secure_boot_issue.adoc[]

include::snip_measured_boot_windows_vm.adoc[]

.Migration of a VM with Secure Boot enabled VM migration results in a VM with Secure Boot disabled

When migrating a virtual machine (VM) with *Secure Boot* enabled, the VM has *Secure Boot* as `disabled` after being migrated. This issue has been resolved in {project-short} 2.7.7. link:https://issues.redhat.com/browse/MTV-1632[(MTV-1632)]

.OVN secondary network is not functioning as expected with the Multus default network override

The secondary network of Open Virtual Network (OVN) does not function as expected with the Multus default network override. link:https://issues.redhat.com/browse/MTV-1645[(MTV-1645)]

.Network and Storage maps in the UI are not correct when created from the command line

When creating *Network* and *Storage* maps from the UI, the correct names are not shown in the UI. link:https://issues.redhat.com/browse/MTV-1421[(MTV-1421)]

.Migration fails with module `network-legacy` configured in RHEL guests

Migration fails if the module configuration file is available in the guest and the `dhcp-client` package is not installed, returning a `dracut module 'network-legacy' will not be installed, because command 'dhclient' could not be found` error. link:https://issues.redhat.com/browse/MTV-1615[(MTV-1615)]

.Harden grub2-mkconfig to avoid overwriting `/boot/efi/EFI/redhat/grub.cfg`

In Red Hat Enterprise Linux (RHEL) 9, there has been a significant change in how GRUB is handled on UEFI systems. Previously, the GRUB configuration file, `/boot/efi/EFI/redhat/grub.cfg`, was used on UEFI systems. However, in RHEL 9, this file now serves as a stub that dynamically redirects to the GRUB configuration, located at `/boot/grub2/grub.cfg`. This behavior is expected in RHEL 9.4, but has been resolved in RHEL 9.5. link:https://issues.redhat.com/browse/RHEL-32099[(RHEL-32099)]

.Migration fails for VMs backed by vSAN without VDDK

Migrations for virtual machines (VMs) that are backed by VMware vSAN must use a Virtual Disk Development Kit (VDDK) image. Without a VDDK image, these migrations fail. link:https://issues.redhat.com/browse/MTV-2203[(MTV-2203)]

.Migrated VMs that use the diskBus:scsi option fail to boot

VMs that are migrated in migration plans by using the `plan.spec.diskBus:scsi` option fail to boot after migration as follows:

* All Windows VMs fail to boot.
* Some Linux VMs fail to boot.

VMs that use the `plan.spec.diskBus:sata` and `plan.spec.diskBus:virtio` options successfully boot after migration. link:https://issues.redhat.com/browse/MTV-2199[(MTV-2199)]

