// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="network-prerequisites_{context}"]
= Network prerequisites

[role="_abstract"]
The following network prerequisites apply to all migrations:

* IP addresses, VLANs, and other network configuration settings must not be changed before or during migration. The MAC addresses of the virtual machines are preserved during migration.
* The network connections between the source environment, the {virt} cluster, and the replication repository must be reliable and uninterrupted.
* If you are mapping more than one source and destination network, you must create a network attachment definition for each additional destination network. For more information, see {ocp-doc}/virtualization/index#virt-creating-vms-from-rh-images-overview[Creating virtual machines from Red Hat images overview].

[id="ports_{context}"]
== Ports

The firewalls must enable traffic over the following ports:

// ANDY: The comments are for later, when I separate the ports by vendor.
// ifdef::wmware[]
[cols="1,1,1,1,2a",options="header"]
.Network ports required for migrating from VMware vSphere
|===
|Port |Protocol |Source |Destination |Purpose

|443
|TCP
|OpenShift nodes
|VMware vCenter
|VMware provider inventory

Disk transfer authentication

|443
|TCP
|OpenShift nodes
|VMware ESXi hosts
|Disk transfer authentication

|902
|TCP
|OpenShift nodes
|VMware ESXi hosts
|Disk transfer data copy
|===
// endif::[]

// ifdef::rhv[]
[cols="1,1,1,1,2a",options="header"]
.Network ports required for migrating from {rhv-full}
|===
|Port |Protocol |Source |Destination |Purpose

|443
|TCP
|OpenShift nodes
|{rhv-short} Engine
|{rhv-short} provider inventory

Disk transfer authentication

|54322
|TCP
|OpenShift nodes
|{rhv-short} hosts
|Disk transfer data copy
|===
// endif::[]
