
[id="new-features-and-enhancements-2-7_{context}"]
= New features and enhancements

{project-first} 2.7 introduces the following features and enhancements:

* In {project-short} 2.7.0, warm migration is now based on RHEL 9 inheriting features and bug fixes.

// https://issues.redhat.com/browse/MTV-2039 and https://issues.redhat.com/browse/MTV-2199
* In {project-short} 2.7.10, you can specify the `plan.spec.diskBus` which will be on all disks during the creation.
+
Possible options are:
* SCSI
* SATA
* VirtIO

[NOTE]
====
Virtual machines (VMs) that are migrated in migration plans by using the `diskBus:scsi` option fail to boot after migration as follows:

* All Windows VMs fail to boot.
* Some Linux VMs fail to boot.

VMs that use the `plan.spec.diskBus:sata` and `plan.spec.diskBus:virtio` options successfully boot after migration.
====


// https://issues.redhat.com/browse/MTV-2029
* In {project-short} 2.7.11, you can now migrate shared disks from VMware vSphere by using a new parameter named `migrateSharedDisks` in `Plan` CRs.
+
The parameter can be set to `true` or `false`:

** When set to `true,` {project-short} migrates all shared disks in the CR. 
** When set to `false`, {project-short} does not migrate the shared disks. 

[NOTE]
====
`migrateSharedDisks` applies only to cold migrations. Warm migration of shared disks is not supported. 
====

