// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_content-type: CONCEPT
[id="new-features-and-enhancements-2-10_{context}"]
= New features and enhancements

[role="_abstract"]
{project-first} 2.10 introduces the following features and enhancements:

* {project-short} 2.10.0 standardizes the API for `ForkliftController` global settings, now accepting only string values for feature flags, for example "true" and "false". This standard ensures consistency, clarity, and improved error handling, preventing errors caused by using boolean values instead of string values only for feature flags.
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* In the {project-short} 2.10.0 UI, the Virtual Machines tab on the Plan Details page provides improved visibility of migration progress with a clearer page title label and a display of key events in logical order. You can also hide migration resources for a cleaner UI to assess the progress of your migration. 
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* In {project-short} 2.10.0, you can optimize the asynchronous input/output (AIO) buffer configuration for the VMware disk development kit (VDDK) directly in the MTV UI for cold migrations. AIO buffer configuration is deactivated by default, but you can activate the feature and customize the configuration in YAML to improve storage I/O operations and reduce latency when working with VDDK. link:https://issues.redhat.com/browse/MTV-2188[(MTV-2188)]

* In {project-short} 2.10.0, you can create network maps directly in the MTV UI by adding a source and target network on the Create network map page instead of writing a YAML file. 
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* In the {project-short} 2.10.0 UI, the Virtual Machines table in the Create migration plan wizard is enhanced to simplify navigation and provide a clearer view of selected VMs. With this update, you can bulk select VMs from the Virtual Machines table toolbar, switch between views of selected and unselected VMs, filter VMs by location, and manage columns. link:https://issues.redhat.com/browse/MTV-3058[(MTV-3058)]

* In {project-short} 2.10.0, you can find the status of cutover dates for warm migrations in the MTV UI. The cutover button is an icon in the UI for your migration plan that changes state when you set the date for a cutover so that you can easily identify if a cutover date is set.
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* In {project-short} 2.10.0, the Migrations section on the Plan Details page is relabelled as Migration history. The Migration history section contains tooltips to provide contextual information and make the section more useful for migration monitoring and troubleshooting. 
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* {project-short} 2.10.0 introduces a formatting feature for VMware system serial numbers. System administrators can use the formatting feature for consistent and error-free system serial numbers and easier system identification during migrations and configurations. 
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* In {project-short} 2.10.0, you can customize the `nodeSelector` field and options for importer pods in the MTV UI, enhancing resource allocation, scheduling, and application performance. You can customize pod scheduling policies for importer pods to ensure that importer pods are scheduled on specific nodes for enhanced resource management and stability.
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* {project-short} 2.10.0 supports the migration of Linux Unified Key Setup (LUKS) encrypted VMs by using Network Bound Disk Encryption (NBDE) with Clevis. With this update, you can migrate LUKS-encrypted VMs without rebooting the VMs to obtain a decryption key from the Clevis server. The Clevis server must be accessible from OpenShift. link:https://issues.redhat.com/browse/MTV-3395[(MTV-3395)]

* In {project-short} 2.10.0, the `insecureSkipVerify` flag is set by default for ESXi hosts in the MTV UI, simplifying migrations in environments with self-signed certificates. With this setting, the migration process bypasses SSL certificate validation, reducing potential errors caused by certificates while maintaining security.
//link:https://issues.redhat.com/browse/MTV-XXXX[(MTV-XXXX)]

* In {project-short} 2.10.0, you can configure VM scheduling preferences for migration plans in the MTV UI or the `Plan` Custom Resource (CR). You can add custom labels to migrated VMs, apply VM scheduling to specific nodes based on node labels, and implement affinity or anti-affinity rules for VMs against workloads or nodes. With this update, you can use the `TargetLabels`, `TargetNodeSelector`, and `TargetAffinity` fields to manage VM placement during migrations, improving resource utilization and operational compliance. 
link:https://issues.redhat.com/browse/MTV-2768[(MTV-2768)]

* In {project-short} 2.10.0, a `PreFlightInspection` during warm migration enables early detection of issues during guest conversion. If an issue is detected, the warm migration fails before VM shutdown, and users can adjust VM settings or skip guest conversion. Potential errors during the `PreFlightInspection` include the following:
+
** Missing LUKS passwords
** Unsupported OS
** Unsupported FS 
+
link:https://issues.redhat.com/browse/MTV-2427[(MTV-2427)] 

* *Technology Preview:* In {project-short} 2.10.0, you can import Open Virtual Appliances (OVAs) directly from local machines to {virt} by uploading the OVAs to NFS through the web browser in the MTV UI. link:https://issues.redhat.com/browse/MTV-3371[(MTV-3371)]

* In {project-short} 2.10.0, you can set `useCompatibilityMode` to `true` or `false` in the Raw Copy Mode settings in the MTV UI. With this update, you can use compatibility devices when migrating source VMs, such as SATA bus, E1000E NICs, or USB, or you can use pre-installed VirtIO devices on source VMs. link:https://issues.redhat.com/browse/MTV-3006[(MTV-3006)]  

* In {project-short} 2.10.0, you can migrate VMs to existing user-defined networks (UDNs). With this update, you can create UDNs and map a VM's source network to the UDN, and you can preserve the static IP addresses of source VMs that have assigned IPs. link:https://issues.redhat.com/browse/MTV-2856[(MTV-2856)]  

* *Technology Preview:* In {project-short} 2.10.0, you can live migrate VMs from one OpenShift (OCP) cluster to another, minimizing downtime with the continuous availability of VMs during the migration process. With this update, MTV creates and maps resources from the source to the destination cluster and triggers the live migration, and {virt} CNV migrates the running VM. link:https://issues.redhat.com/browse/MTV-2040[(MTV-2040)]  

* In {project-short} 2.10.0, the Storage Offload Copy feature is *Developer Preview* for warm migrations and *Technology Preview* for cold migrations. Storage Offload Copy accelerates disk transfer in the storage array by bypassing the network. With this update, you can create a snapshot and then copy the base disk while the VM is running. You can copy delta changes from a snapshot over the network after the base disk storage offload copy, minimizing the requirement for VM shutdowns. link:https://issues.redhat.com/browse/MTV-2637[(MTV-2637)] 

* In the {project-short} 2.10.0 UI, you can automate the creation of VMware Virtual Disk Development Kit (VDDK) images from provided `s/tat.gz/tar.gz/` files to accelerate the transfer of virtual disks. link:https://issues.redhat.com/browse/MTV-1616[(MTV-1616)]

