// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="obtaining-console-url_{context}"]
= Getting the {project-short} web console URL

You can get the {project-short} web console URL by using either the {ocp} web console, or the command line.

ifeval::[{context} == "mtv"]
.Prerequisites

* You must have the {virt} Operator installed.
* You must have the {operator-name} installed.
* You must be logged in as a user with `cluster-admin` privileges.
endif::[]

.Procedure

* If you are using the {ocp} web console, follow these steps:
. Log in to the {ocp} web console.
. Click *Networking* -> *Routes*.
. Select the +{namespace}+ project in the *Project:* list.
+
The URL for the `forklift-ui` service that opens the login page for the {project-short} web console is displayed.
+
Click the URL to navigate to the {project-short} web console.

* If you are using the command line: get the {project-short} web console URL with the following command:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get route virt -n {namespace} \
  -o custom-columns=:.spec.host
----
+
The URL for the `forklift-ui` service that opens the login page for the {project-short} web console is displayed.
+
.Example output
[source,terminal,subs="attributes+"]
----
https://virt-{namespace}.apps.cluster.openshift.com.
----

Launch a browser and navigate to the {project-short} web console.
