// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="openstack-prerequisites_{context}"]
= OpenStack prerequisites

The following prerequisites apply to {osp} migrations:

* You must use a xref:compatibility-guidelines_{context}[compatible version] of {osp}.

[IMPORTANT]
====
Migration using {osp} source providers is a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs) and
might not be functionally complete. Red Hat does not recommend using them
in production. These features provide early access to upcoming product
features, enabling customers to test functionality and provide feedback during
the development process.
For more information about the support scope of Red Hat Technology Preview
features, see https://access.redhat.com/support/offerings/techpreview/.
====

[NOTE]
====
Migration using {osp} source providers only supports VMs that use only Cinder volumes.
====
