// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="osh-adding-source-provider_{context}"]
= Adding an {osp} source provider

You can add an {osp} source provider by using the {ocp} web console.

[NOTE]
====
Migration using {osp} source providers only supports VMs that use only Cinder volumes.
====

.Procedure

. In the {ocp} web console, click *Migration* -> *Providers for virtualization*.
. Click *Create Provider*.

. Select *Red Hat OpenStack Platform* from the *Provider type* list.
. Specify the following fields:

* *Provider name*: Name to display in the list of providers
* *{osp} Identity server URL*: {osp} Identity (Keystone) endpoint, for example, `http://controller:5000/v3`
* *{osp} username*: For example, `admin`
* *{osp} password*:
* *Domain*:
* *Project*:
* *Region*:

.  To allow a migration without validating the provider's CA certificate, select the *Skip certificate validation* check box. By default, the checkbox is cleared, meaning that the certificate will be validated.
. If you did not select *Skip certificate validation*, the *CA certificate* field is visible. Drag the CA certificate used to connect to the source environment to the text box or browse for it and click *Select*.  If you did select the check box, the *CA certificate* text box is not visible.
. Click *Create* to add and save the provider.
+
The source provider appears in the list of providers.
