// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_prerequisites-for-migration.adoc

:_mod-docs-content-type: REFERENCE
[id="ova-prerequisites_{context}"]
= Open Virtual Appliance (OVA) prerequisites

[role="_abstract"]
Open Virtual Appliance (OVA) migrations to {virt} require VMware vSphere files in NFS-shared directories. OVA files can be compressed Open Virtualization Format (OVF) packages with `.ova` extensions or extracted packages. {project-first} scans root and first-level subfolders for compressed packages, and up to second-level subfolders for extracted packages.

[NOTE]
====
Migration of OVA files that were not created by {vmw} vSphere but are compatible with vSphere might succeed. However, migration of such files is not supported by {project-short}. {project-short} supports only OVA files created by {vmw} vSphere. For third-party vendor appliances (for example, networking or security appliances), use the vendor's native `.qcow2` or KVM image instead of the OVA migration path.
====

add/incorporate

*Target scope:* OVA import is intended for migrating supported guest operating systems exported from VMware vSphere.
*Vendor appliances:* Do not use OVA import for third-party vendor appliances (e.g. F5, Cisco, Netscaler); they often fail virt-v2v conversion. Use vendor-provided QCOW2 or KVM-native images instead.
*Support:* Converting a vendor OVA may invalidate vendor support agreements.

Prerequisites::

* The NFS share is writable by the QEMU group (GID 107) if you plan to use the web upload feature for OVA files.
* The OVA files are in one or more folders under an NFS shared directory in one of the following structures:
** In one or more compressed OVF packages that hold all the VM information.
+
The filename of each compressed package *must* have the `.ova` extension. Several compressed packages can be stored in the same folder.
+
When this structure is used, {project-short} scans the root folder and the first-level subfolders for compressed packages.
+
For example, if the NFS share is `/nfs`, then:
+
*** The folder `/nfs` is scanned.
+
*** The folder `/nfs/subfolder1` is scanned.
+
*** However, `/nfs/subfolder1/subfolder2` is not scanned.
** In extracted OVF packages.
+
When this structure is used, {project-short} scans the root folder, first-level subfolders, and second-level subfolders for extracted OVF packages.
+
However, there can be only one `.ovf` file in a folder. Otherwise, the migration will fail.
+
For example, if the NFS share is `/nfs`, then:
+
*** The OVF file `/nfs/vm.ovf` is scanned.
+
*** The OVF file `/nfs/subfolder1/vm.ovf` is scanned.
+
*** The OVF file `/nfs/subfolder1/subfolder2/vm.ovf` is scanned.
+
*** However, the OVF file `/nfs/subfolder1/subfolder2/subfolder3/vm.ovf` is not scanned.

* If you plan to upload OVA files using the web browser, ensure that each .ova file has a unique filename.

[NOTE]
====
You can optionally configure OVA file upload by web browser to upload OVA files directly to the NFS share. For more information, see xref:proc_configuring-ova-web-upload_ova[Configuring OVA file upload by web browser].
====


