// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="proc_storage-copy-offload-ui_{context}"]
= Migrating {vmw} vSphere VMs in the UI by using storage copy offload

[role="_abstract"]
You can use the storage copy offload feature of {project-first} to migrate {vmw} vSphere virtual machines (VMs) faster than by other methods.

.Prerequisites

In addition to the regular link:https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.10/html/planning_your_migration_to_red_hat_openshift_virtualization/assembly_provider-specific-requirements-for-migration_mtv#vmware-prerequisites_mtv[{vmw} prerequisites], storage copy offload has the following additional prerequisites:

* A Hitachi Vantara or NetApp ONTAP storage system or one of the following:
** A configured Dell PowerFlex Storage Data Client (SDC) or 
** A configured Internet Small Computer System Interface (iSCSI) storage system
** A configured Fibre Channel storage system
* A working Container Storage Interface (CSI) driver connected to the above and to {virt}
* A configured {vmw} vSphere provider
* vSphere users must have a role that includes thw following privileges (suggested name: `StorgeOffloader`):

** Global
*** Settings
** Datastore
*** Browse datastore
*** Low level file operations
** Host Configuration
*** Advanced settings
*** Query patch
*** Storage partition configuration

.Procedure

. In the {project-short} Operator, set the value of `feature_copy_offload` to `true` in `forklift-controller` by running the following command:
+
[source, terminal]
----
oc patch forkliftcontrollers.forklift.konveyor.io forklift-controller --type merge -p '{"spec": {"feature_copy_offload": "true"}}' -n openshift-mtv
----

. Create a `Secret` in the namespace in which the migration provider is set up, usually `openshift-mtv`. Include the credentials from the appropriate vendor in your `Secret`.
+
include::snip_storage-copy-offload-secret-tables.adoc[]
+
. In the UI complete the following steps:

.. Create an ownerless storage map by using the procedure in link:https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.10/html/planning_your_migration_to_red_hat_openshift_virtualization/assembly_planning-migration-vmware_mtv#creating-form-based-storage-maps-ui-vmware_vmware[Creating ownerless storage maps using the form page of the {project-short} UI]. Use the *Offload plugin* named `vSphere XCOPY`.
.. Create a migration plan by using the procedure in link:https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.10/html/planning_your_migration_to_red_hat_openshift_virtualization/assembly_planning-migration-vmware_mtv#creating-plan-wizard-vmware_vmware[Creating a VMware vSphere migration plan by using the MTV wizard].
