// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-rhv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-ova.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-hyperv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-aws.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-osp.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-cnv.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-virt-destination-provider_{context}"]
= Adding {a-virt} destination provider

[role="_abstract"]
You can use a Red Hat {virt} provider as both source and destination provider. You can migrate virtual machines (VMs) from the cluster that {project-first} is deployed on to another cluster or from a remote cluster to the cluster that {project-short} is deployed on.

.Prerequisites

* You must have {a-virt} link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/authentication_and_authorization/using-service-accounts[service account token] with `cluster-admin` privileges.

.Procedure

. Access the *Create {virt} provider* interface by doing one of the following:

.. In the {ocp} web console, click *Migration for Virtualization > Providers*.
... Click *Create Provider*.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.
... Click *{virt}*.

.. If you have Administrator privileges, in the {ocp} web console, click *Migration for Virtualization > Overview*.
... In the *Welcome* pane, click *{virt}*.
+
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page, and click *{virt}* when the *Welcome* pane opens.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.

. Specify the following fields:

* *Provider resource name*: Name of the source provider
* *URL*: URL of the endpoint of the API server
* *Service account bearer token*: Token for a service account with `cluster-admin` privileges
+
If both *URL* and *Service account bearer token* are left blank, the local {ocp-short} cluster is used.
+
. Choose one of the following options for validating CA certificates:
+
** *Use a custom CA certificate*: Migrate after validating a custom CA certificate.
** *Use the system CA certificate*: Migrate after validating the system CA certificate.
** *Skip certificate validation* : Migrate without validating a CA certificate.
+
.. To use a custom CA certificate, leave the *Skip certificate validation* switch toggled to the left, and _either_ drag the CA certificate to the text box _or_ browse for it and click *Select*.
.. To use the system CA certificate, leave the *Skip certificate validation* switch toggled to the left, and leave the *CA certificate* text box empty.
.. To skip certificate validation, toggle the *Skip certificate validation* switch to the right.
+
. Optional: Ask {project-short} to fetch a custom CA certificate from the provider's API endpoint URL.
+
.. Click *Fetch certificate from URL*. The *Verify certificate* window opens.
.. If the details are correct, select the *I trust the authenticity of this certificate* checkbox and then click *Confirm*. If not, click *Cancel* and then enter the correct certificate information manually.
+
Once confirmed, the CA certificate will be used to validate subsequent communication with the API endpoint.

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.
