// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="proc_storage-copy-offload_{context}"]
= Migrating {vmw} vSphere VMs by using storage copy offload

[role="_abstract"]
You can use the storage copy offload feature of {project-first} to migrate {vmw} vSphere virtual machines (VMs) faster than by other methods. 

.Prerequisites

In addition to the regular xref:vmware-prerequisites_mtv[{vmw} prerequisites], storage copy offload has the following additional prerequisites: 

* A configured Dell PowerFlex Storage Data Client (SDC) or one of the following:
** A configured Internet Small Computer System Interface (iSCSI) storage systdem
** A configured Fibre Channel storage system
* A working Container Storage Interface (CSI) driver connected to the above and to {virt}
* A configured {vmw} vSphere provider
* vSphere users must have a role that includes thw following privileges (suggested name: `StorgeOffloader`):

** Global
*** Settings
** Datastore
*** Browse datastore
*** Low level file operations
** Host Configuration
*** Advanced settings
*** Query patch
*** Storage partition configuration

.Procedure

. In the {project-short} Operator, set the value of `feature_copy_offload` to `true` in `forklift-controller` by running the following command:
+
[source, terminal]
----
oc patch forkliftcontrollers.forklift.konveyor.io forklift-controller --type merge -p '{"spec": {"feature_copy_offload": "true"}}' -n openshift-mtv
----

. Create a `Secret` in the namespace in which the migration provider is set up, usually `openshift-mtv`. Include the following credentials in the `Secret`. Note that Hitachi has a different set of credentials:
+
[cols="4", options="header"]
.Credentials for a non-Hitachi storage copy offload Secret
|===
|Key| Description| Mandatory?| Default

| `STORAGE_HOSTNAME`
| IP or URL of the host (string)
| Yes
| NA

| `STORAGE_USERNAME`
| The user's name (string)
| Yes
| NA

| `STORAGE_PASSWORD`
| The user's password (string)
| Yes
| NA

| `STORAGE_SKIP_SSL_VERIFICATION`
| If set to `true`, SSL verification is not performed (`true`, `false`).
| No
|`false`
|===
+
[cols="4", options="header"]
.Credentials for a Hitachi storage copy offload Secret
|===
|Key| Description| Mandatory?| Default

| `GOVMOMI_HOSTNAME`
| hostname or URL of the vSphere API (string)
| Yes
| NA

| `GOVMOMI_USERNAME`
| User name of the vSphere API (string)
| Yes
| NA

| `GOVMOMI_PASSWORD`
| Password of the vSphere API (string)
| Yes
| NA

| `STORAGE_HOSTNAME`
| The hostname or URL of the storage vendor API (string)
| Yes
| NA

| `STORAGE_USERNAME`
| The username of the storage vendor API (string)
| Yes
| NA

| `STORAGE_PASSWORD`
| The password of the storage vendor API (string)
| Yes
| NA

| `STORAGE_PORT`
| The port of the storage vendor API (string)
| Yes
| NA

| `STORAGE_ID`
| Storage array serial number (string)
| Yes
| NA

| `HOSTGROUP_ID_LIST`
| List of IO ports and host group IDs, for example. `CL1-A,1:CL2-B,2:CL4-A,1:CL6-A,1`
| Yes
| NA
|===

. In either the UI or the CLI, create a storage map:

.. In the CLI, create a `StorageMap` custom resource (CR) according to the following example:
+
[source,yaml,subs="attributes+"]
----
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: copy-offload
  namespace: openshift-mtv
spec:
  map:
  - destination:
      accessMode: ReadWriteMany
      storageClass: <storage_class> <1>
    offloadPlugin: 
      vsphereXcopyConfig:
        secretRef: <Secret_for_the_storage_vendor_product> <2>
        storageVendorProduct: <storage_vendor_product> <3>
    source:
      id: <datastore_ID> <4>
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
      uid: <ID_of_provider_host>
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: <name_of_vSphere_provider>
      namespace: openshift-mtv
      uid: <ID_of_vSphere_provider>
----
<1> The storage class for the target Persistent Volume Container (PVC) of the VM.
<2> `Secret` that contains the storage provider credentials.
<3> String that identifies the storage product. Valid strings are listed in the table that follows this CR.
<4> Datastore ID as set by {vmw} vSphere.
+
[cols="1,1",options="header"]
.Supported storage vendors and their identifying strings in the CLI  
|===
|Vendor
|Identifying string (Value of `storageVendorProduct` label)

|Hitachi Vantara
|`vantara`

|NetApp
|`ontap`

|Hewlett Packard Enterprise
|`primera3par`

|Pure Storage
|`pureFlashArray`

| Dell (PowerFlex)
|`powerflex`

| Dell (PowerMax)
|`powermax`

| Dell (PowerStore)
|`powerstore`

| Infinidat
|`infinibox`

| IBM
|`flashsystem`
|===

.. In the UI, create an ownerless storage map by doing the following:
m
... In the {ocp} web console, click *Migration for Virtualization* > *Storage maps*.
... Click *Create storage map* > *Create with YAML*.
... Copy-paste the above `StorageMap` CR into the text box. 
... Click *Create*.

. In the UI, create a migration plan using the procedure in xref:creating-plan-wizard-vmware_vmware[Creating a VMware vSphere migration plan by using the MTV wizard].
. In the CLI, create a migration plan using the procedure in link:https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.10/html/migrating_your_virtual_machines_to_red_hat_openshift_virtualization/assembly_migrating-from-vmware_mtv#proc_migrating-virtual-machines-cli_vmware[Running a {vmw} vSphere migration from the command-line]. In the `Plan` CR, modify the `spec:map:storage` portion of the Cr as follows:
+
[source,yaml,subs="attributes+"]
----
  spec:
    map:
      storage:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: StorageMap
        name: <storage_map_in_StorageMap_CR>
        namespace: <namespace>
----
