// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-aws.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_creating-form-based-storage-maps-ui-aws_{context}"]
= Creating ownerless storage maps from the form page in the {project-short} UI

[role="_abstract"]
You can add ownerless storage maps from the form page in the {project-first} UI. Later, you can add these maps to a migration plan by using the *Use an existing storage map* option in the *Storage map* page of the {project-short} wizard.

Storage maps define the mapping between {aws} EBS volume types and OpenShift storage classes that use the EBS CSI driver.

For more information about network and storage maps in {project-short}, see link:{mtv-plan}assembly_mapping-networks-storage_mtv[Mapping networks and storage in migration plans].

[IMPORTANT]
====
You must map EBS volumes to storage classes that use the {aws} EBS CSI driver.
====

.Prerequisites

* Have an {aws} {ec2} source provider and {a-virt} destination provider. For more information, see xref:proc_adding-source-provider_aws[Adding an {aws} {ec2} source provider] or xref:proc_adding-virt-destination-provider_dest_aws[Adding {a-virt} destination provider].
* EBS CSI driver installed and configured on the target cluster.
* Storage classes configured to use the EBS CSI driver.

.Procedure

. In the {ocp} web console, click *Migration for Virtualization* > *Storage maps*.
. Click *Create storage map* > *Create with form*.
. Specify the following:

* *Map name*: Name of the storage map.
* *Project*: Select from the list.
* *Source provider*: Select the {aws} {ec2} source provider from the list.
* *Target provider*: Select the {virt} destination provider from the list.
* *Source storage*: Select the EBS volume type from the list.
* *Target storage*: Select a storage class that uses the EBS CSI driver from the list.

. Optional: Click *Add mapping* to create additional storage maps, including mapping multiple storage sources to a single target storage class.
. Click *Create*.
+
Your map appears in the list of storage maps.

