// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-cnv.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-source-provider_{context}"]
= Adding a Red Hat {virt} source provider

[role="_abstract"]
You can use a Red Hat {virt} provider as both source and destination provider. You can migrate VMs from the cluster that {project-first} is deployed on to another cluster, or from a remote cluster to the cluster that {project-short} is deployed on.

[NOTE]
====
The {ocp} cluster version of the source provider must be 4.16 or later.
====

.Procedure

. Access the *Create provider* interface {virt} by doing one of the following:

.. In the {ocp} web console, click *Migration for Virtualization > Providers*.
... Click *Create Provider*.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.
... Click *{virt}*.

.. If you have Administrator privileges, in the {ocp} web console, click *Migration for Virtualization > Overview*.
... In the *Welcome* pane, click *{virt}*.
+
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page, and click *{virt}* when the *Welcome* pane opens.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.
. Specify the following fields:

* *Provider resource name*: Name of the source provider
* *URL*: URL of the endpoint of the API server
* *Service account bearer token*: Token for a service account with `cluster-admin` privileges
+
If both *URL* and *Service account bearer token* are left blank, the local {ocp-short} cluster is used.
+
. Choose one of the following options for validating CA certificates:
+
** *Use a custom CA certificate*: Migrate after validating a custom CA certificate.
** *Use the system CA certificate*: Migrate after validating the system CA certificate.
** *Skip certificate validation* : Migrate without validating a CA certificate.
+
.. To use a custom CA certificate, leave the *Skip certificate validation* switch toggled to the left, and _either_ drag the CA certificate to the text box _or_ browse for it and click *Select*.
.. To use the system CA certificate, leave the *Skip certificate validation* switch toggled to the left, and leave the *CA certificate* text box empty.
.. To skip certificate validation, toggle the *Skip certificate validation* switch to the right.
+
. Optional: Ask {project-short} to fetch a custom CA certificate from the provider's API endpoint URL.
+
.. Click *Fetch certificate from URL*. The *Verify certificate* window opens.
.. If the details are correct, select the *I trust the authenticity of this certificate* checkbox and then click *Confirm*. If not, click *Cancel* and then enter the correct certificate information manually.
+
Once confirmed, the CA certificate will be used to validate subsequent communication with the API endpoint.

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.

. Optional: Add access to the UI of the provider:
.. On the *Providers* page, click the provider.
+
The *Provider details* page opens.
.. Click the *Edit* icon under *External UI web link*.
.. Enter the link and click *Save*.
+
[NOTE]
====
If you do not enter a link, {project-short} attempts to calculate the correct link.

* If {project-short} succeeds, the hyperlink of the field points to the calculated link.
* If {project-short} does not succeed, the field remains empty.
====
