// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_migrating-from-aws.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_migrating-vms-cli-aws_{context}"]

= Running an {aws} {ec2} migration from the command-line

[role="_abstract"]
You can migrate from an {aws} {ec2} source provider by using the command-line interface (CLI).

.Prerequisites

* {virt} destination provider configured
* {ec2} instances must be stopped before migration

// Does anything need to be changed in the Secret and Provider manifests for AWS EC2?
// Does anything need to be changed in the NetworkMap manifest for AWS EC2?
// Does anything need to be changed in the StorageMap manifest for AWS EC2?
// Does anything need to be changed in the Plan manifest for AWS EC2?

.Procedure

. Create a `Secret` manifest for the source provider credentials:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: <secret>
  namespace: <namespace>
  ownerReferences:
    - apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: <provider_name>
      uid: <provider_uid>
  labels:
    createdForProviderType: ec2
    createdForResourceType: providers
type: Opaque
stringData:
  accessKeyId: <aws_access_key_id>
  secretAccessKey: <aws_secret_access_key>
EOF
----
+
where:
+
`<secret>`::
Specifies the name of the `Secret` CR.
+
`<namespace>`::
Specifies the namespace for the resource. Use +{namespace}+ for the {project-short} namespace, or specify a custom namespace if you have configured providers in a different project.
+
`ownerReferences`::
Is an optional section in which you can specify a provider's `name` and `uid`.
+
`<provider_name>`::
Specifies the name of the provider that owns this secret.
+
`<provider_uid>`::
Specifies the unique identifier of the provider.
+
`<aws_access_key_id>`::
Specifies the {aws} access key ID.
+
`<aws_secret_access_key>`::
Specifies the {aws} secret access key.

. Create a `Provider` manifest for the source provider:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: Provider
metadata:
  name: <source_provider>
  namespace: <namespace>
spec:
  type: ec2
  url: <aws_region>
  secret:
    name: <secret>
    namespace: <namespace>
EOF
----
+
where:
+
`<namespace>`::
Specifies the namespace for the resource. Use +{namespace}+ for the {project-short} namespace, or specify a custom namespace if you have configured providers in a different project.
+
`<source_provider>`::
Specifies the name of the source provider.
+
`<aws_region>`::
Specifies the {aws} region where your {ec2} instances are located, for example, `us-east-1` or `us-east-2`. This must be the same region as your {rosa} or OSD cluster.
+
`<secret>`::
Specifies the name of the provider `Secret` CR.

. Create a `NetworkMap` manifest to map the source and destination networks:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: <network_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        name: <network_name>
        type: pod
      source:
        id: <source_subnet_id>
    - destination:
        name: <network_attachment_definition>
        namespace: <network_attachment_definition_namespace>
        type: multus
      source:
        id: <source_subnet_id>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
+
where:
+
`<network_map>`::
Specifies the name of the network map.
+
`<namespace>`::
Specifies the namespace for the resource. Use +{namespace}+ for the {project-short} namespace, or specify a custom namespace if you have configured providers in a different project.
+
`<source_subnet_id>`::
Specifies the {aws} subnet ID (for example, `subnet-abc123def456`).
+
`type`::
Specifies the network type. Allowed values are `pod` and `multus`.
+
`<network_attachment_definition>`::
Specifies a network attachment definition (NAD) for each additional {virt} network.
+
`<network_attachment_definition_namespace>`::
Specifies the namespace of the {virt} NAD. Required only when `type` is `multus`.

. Create a `StorageMap` manifest to map source and destination storage:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
      source:
        id: <source_volume_type>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
+
where:
+
`<storage_map>`::
Specifies the name of the storage map.
+
`<storage_class>`::
Specifies the {virt} storage class that uses the {aws} EBS CSI driver.
+
`<source_volume_type>`::
Specifies the EBS volume type (for example, `gp2`, `gp3`, `io1`).

. Create a `Plan` manifest for the migration:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: Plan
metadata:
  name: <plan>
  namespace: <namespace>
spec:
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
  map:
    network:
      name: <network_map>
      namespace: <namespace>
    storage:
      name: <storage_map>
      namespace: <namespace>
  targetNamespace: <target_namespace>
  vms:
    - id: <source_vm1>
    - name: <source_vm2>
      hooks:
        - hook:
            namespace: <namespace>
            name: <hook>
          step: <step>
EOF
----
+
where:
+
`<namespace>`::
Specifies the namespace for the resource. Use +{namespace}+ for the {project-short} namespace, or specify a custom namespace if you have configured providers in a different project.
+
`<plan>`::
Specifies the name of the `Plan` CR.
+
`map`::
Specifies only one network map and one storage map per plan.
+
`network`::
Specifies a network mapping, even if the VMs to be migrated are not assigned to a network. The mapping can be empty in this case.
+
`<network_map>`::
Specifies the name of the `NetworkMap` CR.
+
`storage`::
Specifies a storage mapping, even if the VMs to be migrated are not assigned with disk images. The mapping can be empty in this case.
+
`<storage_map>`::
Specifies the name of the `StorageMap` CR.
+
`<target_namespace>`::
Specifies the target namespace in {virt} where the migrated VMs will be created.
+
`vms`::
Specifies the source VMs. Accepts either the `id` or the `name` parameter to specify the source VMs.
+
`<source_vm1>`::
Specifies the {ec2} instance ID.
+
`hooks`::
Specifies up to two hooks for a VM. Each hook must run during a separate migration step. This is an optional label.
+
`<hook>`::
Specifies the name of the `Hook` CR.
+
`<step>`::
Specifies the type of hook. Allowed values are `PreHook`, before the migration plan starts, or `PostHook`, after the migration is complete.

. Create a `Migration` manifest to run the `Plan` CR:
+
[source,yaml,subs="attributes+"]
----
$ cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: Migration
metadata:
  name: <name_of_migration_cr>
  namespace: <namespace>
spec:
  plan:
    name: <name_of_plan_cr>
    namespace: <namespace>
EOF
----
+
where:
+
`<name_of_migration_cr>`::
Specifies the name of the `Migration` CR.
+
`<name_of_plan_cr>`::
Specifies the name of the `Plan` CR to execute.

. Monitor the migration progress:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get migration/<name_of_migration_cr> -n <namespace> -o yaml
----
+
This shows the migration status and progress.

. View detailed migration information:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get vmimports -n <namespace>
----
+
This shows the detailed phases of the VM import process.

.Additional resources

* link:{mtv-plan}assembly_planning-migration-aws_mtv[Planning a migration of virtual machines from {aws} {ec2}]
