// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-hyperv.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_creating-yaml-based-storage-maps-ui-hyperv_{context}"]
= Creating ownerless storage maps by using YAML or JSON definitions in the {project-short} UI

[role="_abstract"]
Use YAML or JSON to create ownerless storage maps in the {project-first} UI. You can select these maps later when creating a migration plan.

For more information about network and storage maps in {project-short}, see link:{mtv-plan}assembly_mapping-networks-storage_mtv[Mapping networks and storage in migration plans].

.Prerequisites

* Have a Microsoft Hyper-V source provider and {a-virt} destination provider. For more information, see xref:proc_adding-source-provider_hyperv[Adding a Microsoft Hyper-V source provider] or xref:proc_adding-source-provider_dest_hyperv[Adding {a-virt} destination provider].

.Procedure

. In the {ocp} web console, go to *Migration for Virtualization* > *Storage maps* > *Create storage map* > *Create with YAML*.
. Enter the YAML or JSON definitions into the editor, or drag and drop a file.
. If you enter YAML definitions, use the following:
+
[source,yaml,subs="attributes+"]
----
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: <storage_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        storageClass: <storage_class>
        accessMode: <access_mode>
      source:
        id: <source_storage_id>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
----
+
* `accessMode`: `ReadWriteOnce` or `ReadWriteMany`.
* `source`: The Hyper-V storage identifier (file path, volume GUID path, or storage pool name). For example, `C:\VHDs\disk.vhdx`. To retrieve these identifiers, see xref:proc_retrieving-hyperv-ids_{context}[Retrieving Microsoft Hyper-V network and storage identifiers].

. Optional: To download your input, click *Download*.
. Click *Create*.
+
Your map appears in the list of storage maps.

