// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_creating-yaml-based-network-maps-ui-vmware_{context}"]
= Creating ownerless network maps by using YAML or JSON definitions in the {project-short} UI

[role="_abstract"]
You can add ownerless network maps by using YAML or JSON definitions in the YAML page of the {project-first} UI to map source networks to {virt} networks. Later, you can add these maps to a migration plan by using the *Use an existing network map* option in the *Network map* page of the {project-short} wizard.

For more information about network and storage maps in {project-short}, see link:{mtv-plan}assembly_mapping-networks-storage_mtv[Mapping networks and storage in migration plans].

.Prerequisites

* Have a {vmw} source provider and {a-virt} destination provider. For more information, see xref:proc_adding-source-provider_vmware[Adding a VMware vSphere source provider] or xref:proc_adding-source-provider_dest_vmware[Adding {a-virt} destination provider].

.Procedure

. In the {ocp} web console, click *Migration for Virtualization* > *Network maps*.
. Click *Create network map* > *Create with YAML*.
. Enter the YAML or JSON definitions into the editor, or drag and drop a file into the editor.
. If you enter YAML definitions, use the following:
+
[source,yaml,subs="attributes+"]
----
$  cat << EOF | {oc} apply -f -
apiVersion: forklift.konveyor.io/v1beta1
kind: NetworkMap
metadata:
  name: <network_map>
  namespace: <namespace>
spec:
  map:
    - destination:
        name: <network_name>
        type: pod
      source:
        id: <source_network_id>
        name: <source_network_name>
    - destination:
        name: <network_attachment_definition>
        namespace: <network_attachment_definition_namespace>
        type: multus
      source:
        id: <source_network_id>
        name: <source_network_name>
  provider:
    source:
      name: <source_provider>
      namespace: <namespace>
    destination:
      name: <destination_provider>
      namespace: <namespace>
EOF
----
+
* `type`: Allowed values are `pod`, `multus`, and `ignored`. Use `ignored` to avoid attaching VMs to this network for this migration.
* `source`: You can use either the `id` or the `name` parameter to specify the source network. For `id`, specify the VMware vSphere network Managed Object Reference (moRef). For more information about retrieving the moRef, see link:{mtv-mig}assembly_migrating-from-vmware_mtv#proc_retrieving-vmware-moref_vmware[Retrieving a {vmw} vSphere moRef] in _{migrating-guide-title}_.
* `<network_attachment_definition>`: Specify a network attachment definition for each additional {virt} network.
* `<network_attachment_definition_namespace>`: Required only when `type` is `multus`. Specify the namespace of the {virt} network attachment definition.

. Optional: To download your input, click *Download*.
. Click *Create*.
+
Your map appears in the list of network maps.

