// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-osp.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-source-provider_{context}"]
= Adding an {osp} source provider

[role="_abstract"]
You can add an {osp} source provider by using the {ocp} web console.

[IMPORTANT]
====
When you migrate an image-based virtual machine (VM) from an {osp} provider, {project-short} creates a snapshot of the image attached to the source VM and copies the snapshot data to the target VM. This means that the target VM has the same state as the source VM at the time {project-short} created the snapshot.
====

.Procedure

. Access the *Create provider* page for {osp} by doing one of the following:

.. In the {ocp} web console, click *Migration for Virtualization > Providers*.
... Click *Create Provider*.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.
... Click *{osp}*.

.. If you have Administrator privileges, in the {ocp} web console, click *Migration for Virtualization > Overview*.
... In the *Welcome* pane, click *{osp}*.
+
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page, and click *{osp}* when the *Welcome* pane opens.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.

. Specify the following fields:

* *Provider resource name*: Name of the source provider.
* *URL*: URL of the {osp} Identity (Keystone) endpoint. For example, `http://controller:5000/v3`.
* *Authentication type*: Choose one of the following methods of authentication and supply the information related to your choice. For example, if you choose *Application credential ID* as the authentication type, the *Application credential ID* and the *Application credential secret* fields become active, and you need to supply the ID and the secret.

** *Application credential ID*
*** *Application credential ID*: {osp} application credential ID
*** *Application credential secret*: {osp} application credential `Secret`

** *Application credential name*
*** *Application credential name*: {osp} application credential name
*** *Application credential secret*: {osp} application credential `Secret`
*** *Username*: {osp} username
*** *Domain*: {osp} domain name

** *Token with user ID*
*** *Token*: {osp} token
*** *User ID*: {osp} user ID
*** *Project ID*:  {osp} project ID

** *Token with user Name*
*** *Token*: {osp} token
*** *Username*: {osp} username
*** *Project*: {osp} project
*** *Domain name*: {osp} domain name

** *Password*
*** *Username*: {osp} username
*** *Password*: {osp} password
*** *Project*: {osp} project
*** *Domain*: {osp} domain name
+
. Choose one of the following options for validating CA certificates:
+
** *Use a custom CA certificate*: Migrate after validating a custom CA certificate.
** *Use the system CA certificate*: Migrate after validating the system CA certificate.
** *Skip certificate validation* : Migrate without validating a CA certificate.
+
.. To use a custom CA certificate, leave the *Skip certificate validation* switch toggled to the left, and _either_ drag the CA certificate to the text box _or_ browse for it and click *Select*.
.. To use the system CA certificate, leave the *Skip certificate validation* switch toggled to the left, and leave the *CA certificate* text box empty.
.. To skip certificate validation, toggle the *Skip certificate validation* switch to the right.
+
. Optional: Ask {project-short} to fetch a custom CA certificate from the provider's API endpoint URL.
+
.. Click *Fetch certificate from URL*. The *Verify certificate* window opens.
.. If the details are correct, select the *I trust the authenticity of this certificate* checkbox and then click *Confirm*. If not, click *Cancel* and then enter the correct certificate information manually.
+
Once confirmed, the CA certificate will be used to validate subsequent communication with the API endpoint.

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.

. Optional: Add access to the UI of the provider:
.. On the *Providers* page, click the provider.
+
The *Provider details* page opens.
.. Click the *Edit* icon under *External UI web link*.
.. Enter the link and click *Save*.
+
[NOTE]
====
If you do not enter a link, {project-short} attempts to calculate the correct link.

* If {project-short} succeeds, the hyperlink of the field points to the calculated link.
* If {project-short} does not succeed, the field remains empty.
====
