// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_migrating-vms-web-console.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_renaming-vms-for-migration_{context}"]

= Renaming virtual machines for migration

[role="_abstract"]
Rename source VMs in the MTV UI to resolve naming conflicts and ensure Kubernetes naming compliance. VM names must be DNS-compliant: lowercase alphanumeric characters and hyphens only, no leading or trailing hyphens, no consecutive hyphens, and 63 characters maximum.

.Examples of VM naming conflicts 
[cols="30%a,40%a,30%a",options="header",]
|===
|Source VM name |Naming conflict | New target VM name

|`App_VM_01` | Contains uppercase letters and underscores | `app-vm-01`

|`-app-server` | Starts with a hyphen | `app-server`

|`app--server` | Contains consecutive hyphens | `app-server`

|`long-name-for-server-that-contains-more-than-sixty-three-characters` | Exceeds the 63-character length limit | `db-server-prod-01`
|===

.Procedure
. In the Red Hat OpenShift web console, click *Migration for Virtualization* > *Migration plans*.
. Open the *Plan Details* page for your migration plan.
. Click the *Virtual Machines* tab to view a table of all VMs from the configured source provider.
. If the *Target name* column does not already show in the VM table, click *Manage columns* to select *Target name* and display the column.
. Identify non-conformant names in the list of VMs by checking the alerts in the *Concerns* column.
. To rename a VM, click the *More* icon at the end of the row for the VM, and click *Edit target name*.
. Enter and save a new name for the VM. Ensure that the new name consists only of alphanumeric characters (a-z, 0-9) and hyphens. Ensure that the name does not start or end with a hyphen or contain consecutive hyphens and is less than 63 characters long.


