// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-ova.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-source-provider_{context}"]
= Adding an Open Virtual Appliance (OVA) source provider

[role="_abstract"]
You can add Open Virtual Appliance (OVA) files that were created by {vmw} vSphere as a source provider by using the {ocp} web console.

.Procedure

. Access the *Create provider* page for Open Virtual Appliance by doing one of the following:

* *From the Providers page:* In the {ocp} web console, click *Migration for Virtualization > Providers*, click *Create Provider*, select a *Project* from the list, and then click *Open Virtual Appliance*.

* *From the Overview page (Administrators only):* In the {ocp} web console, click *Migration for Virtualization > Overview*, click *Open Virtual Appliance* in the *Welcome* pane, and select a *Project* from the list.
+
[NOTE]
====
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page.
====
+
The default project depends on the active {project-short} project (if *All projects* is active, the default is `+{namespace}+`). Administrators can view all projects; authorized non-administrators see only their assigned projects.

. Enter the provider details:
+
* *Provider resource name*: Name of the source provider
* *URL*: URL of the Network File System (NFS) file share that serves the OVA
+
[NOTE]
====
After creating the provider, you can optionally configure OVA file upload by web browser to upload OVA files directly to the NFS share. For more information, see xref:proc_configuring-ova-web-upload_{context}[Configuring OVA file upload by web browser].
====

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.
+
[NOTE]
====
An error message might appear that states that an error has occurred. You can ignore this message.
====
