// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_configuring-ova-web-upload_{context}"]

= Configuring OVA file upload by web browser

[role="_abstract"]
You can configure Open Virtual Appliance (OVA) file upload by web browser to upload an OVA file directly to an NFS share. To configure OVA file upload, you first enable OVA appliance management in the `ForkliftController` custom resource (CR) and then enable OVA upload for each OVA provider. When you enable OVA upload for an OVA provider, the *Upload local OVA files* option appears on the provider’s *Details* page in the MTV UI.

You cannot upload OVA files with duplicate file names.

.Prerequisites

* You have an NFS share to point the OVA provider at.
* You have enough storage space in your NFS share.
* You have a valid .ova file to upload.

.Procedure
. In the Red Hat OpenShift web console, click *Operators* > *Installed Operators*.
. Click *Migration Toolkit for Virtualization Operator*.
+
The Operator Details page opens in the *Details* tab.
. Click the *ForkliftController* tab, and open the `forklift-controller` resource.
. Click the `forklift-controller` YAML tab, and add the `feature_ova_appliance_management` field to the `spec` section of the `forklift-controller` custom resource (CR):
+
Example:
+
----
spec:
  ...
  feature_ova_appliance_management: 'true'
----

. In the Red Hat OpenShift web console, click *Migration for Virtualization* > *Providers*.
. Click the provider, and then click the provider’s *YAML* tab. 
+
For information about creating a provider, see xref:adding-source-provider_ova[Adding an Open Virtual Appliance (OVA) source provider].
. Scroll down the provider’s YAML file to `spec.settings.applianceManagement`, and set `applianceManagement` to 'true':
+
Example:
+
----
spec:
  secret:
    ...
  settings:
    applianceManagement: 'true'
  type: ova
  ...
----
+
* A temporary 'ConnectionTestFailed' error message displays while the update is processing. You can ignore the error message.
. Click the provider’s *Details* tab, and scroll down to the *Conditions* section to verify that ApplianceManagementEnabled shows as True in the list of conditions.
. In the *Upload local OVA files* section, click *Browse* to find a valid .ova file, and then click *Upload*.
+
A ‘success’ message confirms the file upload, and after several seconds, the number of virtual machines increases under the *Provider inventory* section.
+
* If your OVA appliance is very large, you might receive a ‘request timeout’ error message.  


