// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-aws.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-source-provider_{context}"]
= Adding an {aws} {ec2} source provider

[role="_abstract"]
You can add an {aws} {ec2} source provider to migrate {ec2} instances to {virt} on Red Hat OpenShift Service on {aws} ({rosa}) or OpenShift Dedicated (OSD) on {aws}.

[IMPORTANT]
====
Importing VMs from Amazon {ec2} is a Technology Preview feature only. Technology Preview features are not supported with Red{nbsp}Hat production service level agreements (SLAs) and might not be functionally complete. Red{nbsp}Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red{nbsp}Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

.Prerequisites

* {aws} credentials with required Identity and Access Management (IAM) permissions. For more information, see xref:ref_aws-ec2-prerequisites_mtv[{aws} {ec2} prerequisites].
* Elastic Block Store (EBS) Container Storage Interface (CSI) driver installed on the target cluster.

.Procedure

. Access the *Create provider* page for {aws} {ec2} by doing one of the following:

.. In the {ocp} web console, click *Migration for Virtualization > Providers*.
... Click *Create Provider*.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.
... Click *Amazon {ec2}*.

.. If you have Administrator privileges, in the {ocp} web console, click *Migration for Virtualization > Overview*.
... In the *Welcome* pane, click *Amazon {ec2}*.
+
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page, and click *Amazon {ec2}* when the *Welcome* pane opens.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.

. Specify the following fields:
+
* *Provider resource name*: Name of the source provider.
* *{aws} region*: The {aws} region where your {ec2} instances are located, for example, `us-east-1`. This must be the same region as your {rosa} or OSD cluster.
+
. Specify the provider credentials:
+
* *Access key ID*: {aws} access key ID for authenticating to the {ec2} API.
* *Secret access key*: {aws} secret access key for authenticating to the {ec2} API.
+
. Configure target settings:
+
* *Auto-detect target settings*: Select this checkbox to automatically fetch target {aws} credentials from the cluster and detect the target availability zone from worker nodes. This option is selected by default.
+
* *Use cross-account credentials*: Select this checkbox if the target {aws} account is different from the source account. When selected, you must provide the following:
+
** *Target access key ID*: {aws} access key ID for the target account.
** *Target secret access key*: {aws} secret access key for the target account.

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.
+
[NOTE]
====
It might take a few minutes for the provider to move to the `Ready` status.
====
