// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_renaming-vms-for-migration_{context}"]

= Renaming virtual machines for migration

[role="_abstract"]
You can rename source virtual machines (VMs) in the MTV UI to address naming conflicts. Renaming VMs ensures conformity with the Kubernetes-based naming conventions of Red Hat OpenShift Virtualization.

In the OpenShift platform, all resource names, including VMs, must have DNS-compliant names. Valid names consist only of lowercase alphanumeric characters (a-z, 0-9) and hyphens (-). Names must not start or end with a hyphen or contain consecutive hyphens, and the length of a name is limited to 63 characters. The OpenShift API rejects noncompliant source VM names during the creation of the target VM.

.Examples of VM naming conflicts 
[cols="30%a,40%a,30%a",options="header",]
|===
|Source VM name |Naming conflict | New target VM name

|`App_VM_01` | Contains uppercase letters and underscores | `app-vm-01`

|`-app-server` | Starts with a hyphen | `app-server`

|`app--server` | Contains consecutive hyphens | `app-server`

|`long-name-for-server-that-contains-more-than-sixty-three-characters` | Exceeds the 63-character length limit | `db-server-prod-01`
|===

.Procedure
. In the Red Hat OpenShift web console, click *Migration for Virtualization* > *Migration plans*.
. Open the *Plan Details* page for your migration plan.
. Click the *Virtual Machines* tab to view a table of all VMs from the configured source provider.
. If the *Target name* column does not already show in the VM table, click *Manage columns* to select *Target name* and display the column.
. Identify non-conformant names in the list of VMs by checking the alerts in the *Concerns* column.
. To rename a VM, click the *More* icon at the end of the row for the VM, and click *Edit target name*.
. Enter and save a new name for the VM. Ensure that the new name consists only of alphanumeric characters (a-z, 0-9) and hyphens. Ensure that the name does not start or end with a hyphen or contain consecutive hyphens, and it is less than 63 characters long.


