// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-ova.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-source-provider_{context}"]
= Adding an Open Virtual Appliance (OVA) source provider

[role="_abstract"]
You can add Open Virtual Appliance (OVA) files that were created by {vmw} vSphere as a source provider by using the {ocp} web console.

.Procedure

. Access the *Create provider* page for Open Virtual Appliance by doing one of the following:

.. In the {ocp} web console, click *Migration for Virtualization > Providers*.
... Click *Create Provider*.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.
... Click *Open Virtual Appliance*.

.. If you have Administrator privileges, in the {ocp} web console, click *Migration for Virtualization > Overview*.
... In the *Welcome* pane, click *Open Virtual Appliance*.
+
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page, and click *Open Virtual Appliance* when the *Welcome* pane opens.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.

. Specify the following fields:

* *Provider resource name*: Name of the source provider
* *URL*: URL of the Network File System (NFS) file share that serves the OVA
+
[NOTE]
====
After creating the provider, you can optionally configure OVA file upload by web browser to upload OVA files directly to the NFS share. For more information, see xref:proc_configuring-ova-web-upload_ova[Configuring OVA file upload by web browser].
====

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.
+
[NOTE]
====
An error message might appear that states that an error has occurred. You can ignore this message.
====
