// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-hyperv.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_retrieving-hyperv-ids_{context}"]
= Retrieving Microsoft Hyper-V network and storage identifiers

[role="_abstract"]
When you create YAML-based network maps or storage maps for Microsoft Hyper-V migrations, you need to specify the identifiers for Hyper-V networks and storage. You can retrieve these identifiers from the {project-short} Inventory service after you add your Hyper-V source provider.

.Prerequisites

* You have added a Microsoft Hyper-V source provider and the provider status is `Ready`. For more information, see xref:proc_adding-source-provider_hyperv[Adding a Microsoft Hyper-V source provider].

.Procedure

. Retrieve the routes for the project:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get route -n {namespace}
----

. Retrieve the `Inventory` service route:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get route <inventory_service> -n {namespace}
----

. Retrieve the access token:
+
[source,terminal,subs="attributes+"]
----
$ TOKEN=$({oc} whoami -t)
----

. Retrieve the list of Hyper-V providers:
+
[source,terminal]
----
$ curl -H "Authorization: Bearer $TOKEN" https://<inventory_service_route>/providers/hyperv -k
----
+
Note the `id` of your Hyper-V provider from the output.

. Retrieve the networks of the Hyper-V source provider:
+
[source,terminal]
----
$ curl -H "Authorization: Bearer $TOKEN" https://<inventory_service_route>/providers/hyperv/<provider_id>/networks/ -k
----
+
* Example output: In this example, the network ID is the virtual switch GUID in 8-4-4-4-12 hexadecimal format, and the `name` is the virtual switch friendly name.
+
[source,json]
----
[
  {
    "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    "name": "External Switch",
    "path": "/External Switch",
    "revision": 1,
    "selfLink": "providers/hyperv/01278af6-e1e4-4799-b01b-d5ccc8dd0201/networks/a1b2c3d4-e5f6-7890-abcd-ef1234567890"
  },
  {
    "id": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    "name": "Internal Switch",
    "path": "/Internal Switch",
    "revision": 1,
    "selfLink": "providers/hyperv/01278af6-e1e4-4799-b01b-d5ccc8dd0201/networks/b2c3d4e5-f6a7-8901-bcde-f12345678901"
  }
]
----
+
Use the `id` value (GUID format) or the `name` value (friendly name) when creating network maps.

. Retrieve the storage of the Hyper-V source provider:
+
[source,terminal]
----
$ curl -H "Authorization: Bearer $TOKEN" https://<inventory_service_route>/providers/hyperv/<provider_id>/storages/ -k
----
+
* Example output: In this example, the storage identifiers include file paths to virtual hard drives, volume GUID paths, or storage pool names.
+
[source,json]
----
[
  {
    "id": "C:\\VHDs\\Production",
    "name": "Production VHDs",
    "path": "C:\\VHDs\\Production",
    "revision": 1,
    "selfLink": "providers/hyperv/01278af6-e1e4-4799-b01b-d5ccc8dd0201/storages/C:\\VHDs\\Production"
  },
  {
    "id": "\\\\?\\Volume{a1b2c3d4-e5f6-7890-abcd-ef1234567890}\\",
    "name": "Volume GUID Path",
    "path": "\\\\?\\Volume{a1b2c3d4-e5f6-7890-abcd-ef1234567890}\\",
    "revision": 1,
    "selfLink": "providers/hyperv/01278af6-e1e4-4799-b01b-d5ccc8dd0201/storages/\\\\?\\Volume{a1b2c3d4-e5f6-7890-abcd-ef1234567890}\\"
  }
]
----
+
Use the `id` value when creating storage maps.

[role="_additional-resources"]
.Additional resources

* xref:proc_creating-yaml-based-network-maps-ui-hyperv_{context}[Creating ownerless network maps by using YAML or JSON definitions in the {project-short} UI]
* xref:proc_creating-yaml-based-storage-maps-ui-hyperv_{context}[Creating ownerless storage maps by using YAML or JSON definitions in the {project-short} UI]
