// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-source-provider_{context}"]
= Adding a {vmw} vSphere source provider

[role="_abstract"]
You can migrate {vmw} vSphere virtual machines (VMs) from {vmw} vCenter or from a {vmw} ESX/ESXi server without going through vCenter.

Considerations::

* {project-short} disables EMS enforcement for migrations with {vmw} vSphere source providers to enable migrations from versions of vSphere that {project-full} supports but that do not comply with the 2023 FIPS requirements. Therefore, you should consider whether migrations from vSphere source providers risk your compliance with FIPS. See xref:ref_compatibility-guidelines_mtv[Software compatibility guidelines] for supported versions of vSphere.
* Remove anti-virus software from source VMs before migration to prevent migration failures.
* {project-short} does not support migrating VMware Non-Volatile Memory Express (NVMe) disks.
* If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:proc_creating-plan-wizard-vmware_vmware[Creating a {vmw} vSphere migration plan using the {project-short} wizard].

.Prerequisites

* Create a {vmw} Virtual Disk Development Kit (VDDK) image in a secure registry that is accessible to all clusters to accelerate migrations and reduce the risk of migration plan failures. If you are not using VDDK and a plan fails, retry with VDDK installed. For more information, see xref:proc_creating-vddk-image_mtv[Creating a VDDK image].

[WARNING]
====
Virtual machine (VM) migrations do not work without VDDK when a VM is backed by {vmw} vSAN.
====

.Procedure

. Access the *Create provider* page for {vmw} by doing one of the following:

.. In the {ocp} web console, click *Migration for Virtualization > Providers*.
... Click *Create Provider*.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.

... Click *{vmw}*.

.. If you have Administrator privileges, in the {ocp} web console, click *Migration for Virtualization > Overview*.
... In the *Welcome* pane, click *{vmw}*.
+
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page, and click *{vmw}* when the *Welcome* pane opens.
... Select a *Project* from the list. The default project shown depends on the active project of {project-short}.
+
If the active project is *All projects*, then the default project is +{namespace}+. Otherwise, the default project is the same as the active project.
+
If you have Administrator privileges, you can see all projects. Otherwise, you can see only the projects you are authorized to work with.

. Specify the following fields:
+
.. *Provider details*

* *Provider resource name*: Name of the source provider.
* *Endpoint type*: Select the vSphere provider endpoint type. Options: *vCenter* or *ESXi*. You can migrate virtual machines from vCenter, an ESX/ESXi server that is not managed by vCenter, or from an ESX/ESXi server that is managed by vCenter but does not go through vCenter.
* *URL*: URL of the SDK endpoint of the vCenter that hosts the source VM. Ensure that the URL includes the `sdk` path, usually `/sdk`. For example, `https://vCenter-host-example.com/sdk`. If you specify a certificate for FQDN, the value of this field must match the FQDN in the certificate.
* *VDDK init image*: `VDDKInitImage` path. Create a VDDK init image to accelerate migrations. For more information, see xref:proc_creating-vddk-image_mtv[Creating a VDDK image].
+
Do one of the following:

** Select the *Skip {vmw} Virtual Disk Development Kit (VDDK) SDK acceleration (not recommended)*.

** Enter the path in the *VDDK init image* text box. Format: `<registry_route_or_server_path>/vddk:<tag>`.

** Upload a VDDK archive and build a VDDK init image from the archive by doing the following:

*** Click *Browse* next to the *VDDK init image archive* text box, select the desired file, and click *Select*.

*** Click *Upload*.
+
The *VDDK init image archive* text box displays the URL of the uploaded archive.

.. *Provider credentials*

* *Username*: vCenter user or ESXi user. For example, `user@vsphere.local`.
* *Password*: vCenter user password or ESXi user password.

[start=3]
. Choose one of the following options for validating CA certificates:
+
** *Use a custom CA certificate*: Migrate after validating a custom CA certificate.
** *Use the system CA certificate*: Migrate after validating the system CA certificate.
** *Skip certificate validation* : Migrate without validating a CA certificate.
+
.. To use a custom CA certificate, leave the *Skip certificate validation* switch toggled to the left, and _either_ drag the CA certificate to the text box _or_ browse for it and click *Select*.
.. To use the system CA certificate, leave the *Skip certificate validation* switch toggled to the left, and leave the *CA certificate* text box empty.
.. To skip certificate validation, toggle the *Skip certificate validation* switch to the right.
+
. Optional: Ask {project-short} to fetch a custom CA certificate from the provider's API endpoint URL.
+
.. Click *Fetch certificate from URL*. The *Verify certificate* window opens.
.. If the details are correct, select the *I trust the authenticity of this certificate* checkbox and then click *Confirm*. If not, click *Cancel* and then enter the correct certificate information manually.
+
Once confirmed, the CA certificate will be used to validate subsequent communication with the API endpoint.

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.
+
[NOTE]
====
It might take a few minutes for the provider to move to the `Ready` status.
====

. Optional: Add access to the UI of the provider:
.. On the *Providers* page, click the provider.
+
The *Provider details* page opens.
.. Click the *Edit* icon under *External UI web link*.
.. Enter the link and click *Save*.
+
[NOTE]
====
If you do not enter a link, {project-short} attempts to calculate the correct link.

* If {project-short} succeeds, the hyperlink of the field points to the calculated link.
* If {project-short} does not succeed, the field remains empty.
====
