// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="proc_storage-copy-offload_{context}"]
= Migrating {vmw} vSphere VMs by using storage copy offload

[role="_abstract"]
You can use the storage copy offload feature of {project-first} to migrate {vmw} vSphere virtual machines (VMs) faster than by other methods. 

.Prerequisites

In addition to the regular xref:vmware-prerequisites_mtv[{vmw} prerequisites], storage copy offload has the following additional prerequisites: 

* A Hitachi Vantara or NetApp ONTAP storage system or one of the following:
** A configured Dell PowerFlex Storage Data Client (SDC) or 
** A configured Internet Small Computer System Interface (iSCSI) storage system
** A configured Fibre Channel storage system
* A working Container Storage Interface (CSI) driver connected to the above and to {virt}
* A configured {vmw} vSphere provider
* vSphere users must have a role that includes thw following privileges (suggested name: `StorgeOffloader`):

** Global
*** Settings
** Datastore
*** Browse datastore
*** Low level file operations
** Host Configuration
*** Advanced settings
*** Query patch
*** Storage partition configuration

.Procedure

. In the {project-short} Operator, set the value of `feature_copy_offload` to `true` in `forklift-controller` by running the following command:
+
[source, terminal]
----
oc patch forkliftcontrollers.forklift.konveyor.io forklift-controller --type merge -p '{"spec": {"feature_copy_offload": "true"}}' -n openshift-mtv
----

. Create a `Secret` in the namespace in which the migration provider is set up, usually `openshift-mtv`. Include the credentials from the appropriate vendor in your `Secret`.
+
include::snip_storage-copy-offload-secret-tables.adoc[]
+
. In either the UI or the CLI, complete the following steps:

.. In the UI, complete the following steps:

... Create an ownerless storage map by using the procedure in xref:creating-form-based-storage-maps-ui-vmware_vmware[Creating ownerless storage maps using the form page of the {project-short} UI]. Use the *Offload plugin* named `vSphere XCOPY`.
... Create a migration plan by using the procedure in xref:creating-plan-wizard-vmware_vmware[Creating a VMware vSphere migration plan by using the MTV wizard].


.. In the CLI, complete the following steps:

... Create a `StorageMap` custom resource (CR) according to the following example:
+
[source,yaml,subs="attributes+"]
----
apiVersion: forklift.konveyor.io/v1beta1
kind: StorageMap
metadata:
  name: copy-offload
  namespace: openshift-mtv
spec:
  map:
  - destination:
      accessMode: ReadWriteMany <1>
      storageClass: <storage_class> <2>
    offloadPlugin: 
      vsphereXcopyConfig:
        secretRef: <Secret_for_the_storage_vendor_product> <3>
        storageVendorProduct: <storage_vendor_product> <4>
    source:
      id: <datastore_ID> <5>
  provider:
    destination:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: host
      namespace: openshift-mtv
      uid: <ID_of_provider_host>
    source:
      apiVersion: forklift.konveyor.io/v1beta1
      kind: Provider
      name: <name_of_vSphere_provider>
      namespace: openshift-mtv
      uid: <ID_of_vSphere_provider>
----
<1> Optional label.
<2> The storage class for the target Persistent Volume Claim (PVC) of the VM.
<3> `Secret` that contains the storage provider credentials.
<4> String that identifies the storage product. Valid strings are listed in the table that follows this CR.
<5> Datastore ID as set by {vmw} vSphere.
+
[cols="1,1",options="header"]
.Supported storage vendors and their identifying strings in the CLI  
|===
|Vendor
|Identifying string (Value of `storageVendorProduct` label)

|Hitachi Vantara
|`vantara`

|NetApp
|`ontap`

|Hewlett Packard Enterprise
|`primera3par`

|Pure Storage
|`pureFlashArray`

| Dell (PowerFlex)
|`powerflex`

| Dell (PowerMax)
|`powermax`

| Dell (PowerStore)
|`powerstore`

| Infinidat
|`infinibox`

| IBM
|`flashsystem`
|===

... Create a migration plan using the procedure in link:https://docs.redhat.com/en/documentation/migration_toolkit_for_virtualization/2.10/html/migrating_your_virtual_machines_to_red_hat_openshift_virtualization/assembly_migrating-from-vmware_mtv#proc_migrating-virtual-machines-cli_vmware[Running a {vmw} vSphere migration from the command-line]. 
... In the `Plan` CR, modify the `spec:map:storage` portion of the CR as follows:
+
[source,yaml,subs="attributes+"]
----
  spec:
    map:
      storage:
        apiVersion: forklift.konveyor.io/v1beta1
        kind: StorageMap
        name: <storage_map_in_StorageMap_CR>
        namespace: <namespace>
----

