// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-rhv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-ova.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-hyperv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-aws.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-osp.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-cnv.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc_adding-virt-destination-provider_{context}"]
= Adding {a-virt} destination provider

[role="_abstract"]
You can use a Red Hat {virt} provider as both source and destination provider. You can migrate virtual machines (VMs) from the local cluster (where {project-short} is deployed) to a remote cluster, or from a remote cluster to the local cluster.

.Prerequisites

* You must have {a-virt} link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/authentication_and_authorization/using-service-accounts[service account token] with `cluster-admin` privileges.

.Procedure

. Access the *Create {virt} provider* page by doing one of the following:

* *From the Providers page:* In the {ocp} web console, click *Migration for Virtualization > Providers*, click *Create Provider*, select a *Project* from the list, and then click *{virt}*.

* *From the Overview page (Administrators only):* In the {ocp} web console, click *Migration for Virtualization > Overview*, click *{virt}* in the *Welcome* pane, and select a *Project* from the list.
+
[NOTE]
====
If the *Welcome* pane is not visible, click *Show the welcome card* in the upper-right corner of the page.
====
+
The default project depends on the active {project-short} project. If *All projects* is active, the default is +{namespace}+. Administrators can view all projects; authorized non-administrators see only their assigned projects.

. Enter the provider details:
+
* *Provider resource name*: Name of the destination provider
* *URL*: URL of the endpoint of the API server
* *Service account bearer token*: Token for a service account with `cluster-admin` privileges
+
If both *URL* and *Service account bearer token* are left blank, the local {ocp-short} cluster is used.
+
. Choose one of the following options for validating CA certificates:
+
** *Use a custom CA certificate*: Keep *Skip certificate validation* toggled left and provide the certificate:
+
*** *Upload file:* Drag the certificate to the text box, or click *Browse* and click *Select*.
*** *Fetch from URL:* Click *Fetch certificate from URL*, select *I trust the authenticity of this certificate*, and click *Confirm*.

** *Use the system CA certificate*: Keep *Skip certificate validation* toggled left and leave the *CA certificate* text box empty.

** *Skip certificate validation*: Toggle *Skip certificate validation* to the right.

. Click *Create provider* to add and save the provider.
+
The provider appears in the list of providers.
