// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_migrating-from-vmware.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: REFERENCE

[id="ref_network-name-template-variables-vmware_{context}"]
= Network name template variables

[role="_abstract"]
When creating a migration plan, you can use template variables to customize the names of network interfaces for migrated virtual machines. The template follows Go template syntax.

== Available variables

The `networkNameTemplate` field has access to the following variables:

* `.NetworkName`: If the target network is `multus`, add the name of the Multus Network Attachment Definition. Otherwise, leave this variable empty.
* `.NetworkNamespace`: If the target network is `multus`, add the namespace where the Multus Network Attachment Definition is located.
* `.NetworkType`: Specifies the network type. Options: `multus` or `pod`.
* `.NetworkIndex`: Sequential index of the network interface (0-based).

[IMPORTANT]
====
Generated names cannot exceed 63 characters. VM names generated by templates must not include uppercase letters or violate RFC 1123 rules. These rules apply to a network name template, a PVC name template, a VM name template, and a volume name template.

{project-short} does not validate VM names generated by the templates described here. Migrations that include VMs whose names include uppercase letters or that violate RFC 1123 rules fail automatically. To avoid failures, you might want to run a Go script that uses the `sprig` methods that {project-short} supports. For tables documenting the methods that {project-short} supports, see link:{mtv-mig}assembly_migrating-from-vmware_mtv#mtv-template-utility_vmware[{project-short} template utility for {vmw} VM names].
====

== Examples

* `"net-{{.NetworkIndex}}"`
* `"{{if eq .NetworkType \"pod\"}}pod{{else}}multus-{{.NetworkIndex}}{{end}}"`
