// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_mod-docs-content-type: REFERENCE
[id="ref_resolved-issues-2-11-3_{context}"]
= Resolved issues 2.11.3

[role="_abstract"]
Review the resolved issues in this release of {project-short}.

Storage copy offload: Unclear error message for PowerMax migrations replaced::
Before this update, if an ESXi host's Fibre Channel or iSCSI initiators were not registered as a host object in Dell PowerMax during a storage copy offload migration, the migration proceeded with an empty `hostID` value. As a  consequence, the system displayed an unclear `CreateMaskingView` error message.
+
With this update, the system validates the initiator registration. As a result, if the initiators are not registered, the system displays the following message to help you resolve the problem:
+
`Can't find a host on Symmetrix %s with initiators matching %v. Ensure the ESXi host has a corresponding host object in PowerMax with the correct FC/iSCSI initiators registered.`
+
link:https://issues.redhat.com/browse/MTV-4873[MTV-4873]

Storage copy offload: Pure Storage FlashArray HTTP client timeout is configurable::
Before this update, the timeout for a Pure Storage FlashArray HTTP client was hard-coded to 30 seconds. As a consequence, during migrations of VMs with many disks, simultaneous `CopyVolume` requests to the Pure Storage FlashArray timed out, leaving PVCs stuck in `Pending` status.
+
With this update, you can configure the timeout by setting the new `STORAGE_HTTP_TIMEOUT_SECONDS` key and value in the Pure Storage FlashArray `Secret`. As a result, migrations complete successfully without timing out. Note that the key's default value is 30 seconds.
+
link:https://issues.redhat.com/browse/MTV-5004[MTV-5004]

The `fstrim` stage of `virt-v2v` is now skipped for warm migrations::
Before this update, large (multi-terabyte) warm migrations took a long time during the `fstrim` stage of `virt-v2v`.
+
With this update, {project-short} uses the `--no-fstrim` option for `virt-v2v`. As a result, large warm migrations run correctly. The converted guest might use more space after the conversion.
+
link:https://issues.redhat.com/browse/MTV-4941[MTV-4941]
