// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_provider-specific-requirements-for-migration.adoc

:_mod-docs-content-type: REFERENCE
[id="ref_vmware-prerequisites_{context}"]
= {vmw} prerequisites

[role="_abstract"]
Verify that your {vmw} vSphere environment meets the requirements for migrating virtual machines (VMs) to {virt}. Understanding these prerequisites helps you prepare your source environment and avoid migration failures.

Create a VDDK image to accelerate migrations. For more information, see xref:proc_creating-vddk-image_mtv[Creating a VDDK image].

Limitations::
* Virtual machine (VM) migrations fail without a VDDK image when a VM is backed by {vmw} vSAN.
* {project-first} cannot migrate {vmw} vSphere 6 and {vmw} vSphere 7 VMs to a FIPS-compliant {virt} cluster.
* {project-first} does not support migrating hibernated VMs.

Prerequisites::
* You must use a compatible version of {vmw} vSphere. For more information, see xref:ref_compatibility-guidelines_{context}[Compatibility guidelines].
* You must be logged in as a user with at least the minimal set of {vmw} privileges. For more information, see xref:ref_vmware-privileges_{context}[VMware privileges].
* The target namespace must have network connectivity to the {vmw} source environment. `NetworkPolicies` that block egress connections from the target namespace will cause the migration to fail.
* The VM operating system must be certified and supported for use as a guest operating system with {virt} and for conversion to KVM with `virt-v2v`. For more information, see link:https://access.redhat.com/articles/973163#ocpvirt[Guest operating systems supported on {virt}] and link:https://access.redhat.com/articles/1351473[Supported virtual machine guest operating systems for conversions].
* Disable hibernation on the source VMs. If hibernation is disabled, VM data might be lost if there is a power outage.
* VMware Tools must be installed on the source VM to run a warm migration or to access the VM using a pre-migration hook. For more information, see link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Tools].
* If you are running a warm migration, you must enable changed block tracking (CBT) on the VMs and on the VM disks. For more information, see link:https://kb.vmware.com/s/article/1020128[Changed Block Tracking (CBT) on virtual machines].
* If you are migrating more than 10 VMs from an ESXi host in the same migration plan, you must increase the Network File Copy (NFC) service memory of the host.
* A default `MigController` instance must be present. This instance is required for the Storage Migration option in the {ocp} web console in certain {ocp-name} versions. For steps to create the default `MigController` instance, see link:https://access.redhat.com/solutions/7136894[Storage Migration Option Missing for Virtual Machines in OpenShift 4.20 Despite Availability in 4.18].

Considerations::
* *Warm migrations of Microsoft Windows VMs:* For warm migrations of Microsoft Windows virtual machines from {vmw}, the following Windows services must be running or enabled on the source VM:
+
** *Volume Shadow Copy Service (VSS)*: Used to quiesce the file system and applications during snapshot creation.
** *{vmw} Snapshot Provider*: Requests VSS to start the shadow copy when a snapshot is created with `Quiesce guest file system` enabled.
+
If these services are not running or are disabled, snapshot creation during warm migration fails with an error similar to: `An error occurred while taking a snapshot: Failed to restart the virtual machine.` If you set the VSS service to `Manual`, it starts automatically when a snapshot creation with `Quiesce guest file system = yes` is triggered. The {vmw} Snapshot Provider service requests VSS to start the shadow copy in the background.
