// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_migrating-from-vmware.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: REFERENCE

[id="ref_network-name-template-variables-vmware_{context}"]
= Network name template variables

[role="_abstract"]
When creating a migration plan, you can use template variables to customize the names of network interfaces for migrated virtual machines. The template follows Go template syntax.

Network interface names generated by this template must be DNS-compliant, following the same naming rules that apply to VM names: they must consist of lowercase alphanumeric characters or hyphens (`-`), start with an alphanumeric character, and not exceed 63 characters. {project-short} does not validate the `networkNameTemplate` when you create a migration plan. If the resulting network interface names are not DNS-compliant, the migration fails. For template functions to help ensure valid names, see link:{mtv-mig}assembly_migrating-from-vmware_mtv#mtv-template-utility_vmware[{project-short} template utility for {vmw}].

== Available variables

The `networkNameTemplate` field has access to the following variables:

* `.NetworkName`: If the target network is `multus`, add the name of the Multus Network Attachment Definition. Otherwise, leave this variable empty.
* `.NetworkNamespace`: If the target network is `multus`, add the namespace where the Multus Network Attachment Definition is located.
* `.NetworkType`: Specifies the network type. Options: `multus` or `pod`.
* `.NetworkIndex`: Sequential index of the network interface (0-based).

== Examples

* `"net-{{.NetworkIndex}}"`
* `"{{if eq .NetworkType \"pod\"}}pod{{else}}multus-{{.NetworkIndex}}{{end}}"`
