// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_mod-docs-content-type: REFERENCE
[id="ref_technical-changes-2-11_{context}"]
= Technical changes

[role="_abstract"]
Review the technical changes in this release of {project-short}.

Storage copy offload for Infinidat InfiniBox (Developer Preview)::
{project-first} provides storage copy offload for Infinidat InfiniBox for both cold and warm migrations as a Developer Preview.
+
[IMPORTANT]
====
Storage copy offload for Infinidat InfiniBox is Developer Preview software only. Developer Preview software is not supported by Red{nbsp}Hat in any way and is not functionally complete or production-ready. Do not use Developer Preview software for production or business-critical workloads. Developer Preview software provides early access to upcoming product software in advance of its possible inclusion in a Red{nbsp}Hat product offering. Customers can use this software to test functionality and provide feedback during the development process. This software might not have any documentation, is subject to change or removal at any time, and has received limited testing. Red{nbsp}Hat might provide ways to submit feedback on Developer Preview software without an associated SLA.

For more information about the support scope of Red{nbsp}Hat Developer Preview software, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====

Storage copy offload supports VIB version 0.3.0::
The vSphere Installation on Bundle (VIB) is updated to version 0.3.0. If you set up storage copy offload by using a VIB, manually install VIB version 0.3.0 or configure your system automation to install it.
+
link:https://redhat.atlassian.net/browse/MTV-5321[MTV-5321]
