// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_prerequisites-for-migration.adoc

:_mod-docs-content-type: REFERENCE
[id="rhv-prerequisites_{context}"]
= {rhv-full} prerequisites

[role="_abstract"]
The following prerequisites apply to {rhv-full} migrations:

* To create a source provider, you must have at least the `UserRole` and `ReadOnlyAdmin` roles assigned to you. These are the minimum required permissions, however, any other administrator or superuser permissions will also work.

[IMPORTANT]
====
You must keep the `UserRole` and `ReadOnlyAdmin` roles until the virtual machines of the source provider have been migrated. Otherwise, the migration will fail.
====

* To migrate virtual machines:
** You must have one of the following:
*** {rhv-short} admin permissions. These permissions allow you to migrate any virtual machine in the system.
*** `DiskCreator` and `UserVmManager` permissions on every virtual machine you want to migrate.

** You must use a xref:compatibility-guidelines_{context}[compatible version] of {rhv-full}.
** You must have the {manager} CA certificate, unless it was replaced by a third-party certificate, in which case, specify the {manager} Apache CA certificate.
+
You can obtain the {manager} CA certificate by navigating to https://<engine_host>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA in a browser.

** If you are migrating a virtual machine with a direct logical unit number (LUN) disk, ensure that the nodes in the {virt} destination cluster that the VM is expected to run on can access the backend storage.

[NOTE]
====
* Unlike disk images that _are copied_ from a source provider to a target provider, LUNs are _detached_, _but not removed_, from virtual machines in the source provider and then attached to the virtual machines (VMs) that are created in the target provider.

* LUNs are not removed from the source provider during the migration in case fallback to the source provider is required. However, before re-attaching the LUNs to VMs in the source provider, ensure that the LUNs are not used by VMs on the target environment at the same time, which might lead to data corruption.
====

