// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="rhv-prerequisites_{context}"]
= {rhv-full} prerequisites

The following prerequisites apply to {rhv-full} migrations:

* You must have the {rhv-short} admin permissions to be able to migrate any virtual machines. Alternatively, you need to have at least the `DiskCreator` and `UserVmManager` permissions granted by an `admin` user per each individual virtual machine you want to migrate.
* You must use a xref:compatibility-guidelines_{context}[compatible version] of {rhv-full}.
* You must have the {manager} CA certificate, unless it was replaced by a third-party certificate, in which case, specify the {manager} Apache CA certificate.
+
You can obtain the {manager}  CA certificate by navigating to https://<engine_host>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA in a browser.

* If you are migrating a virtual machine with a direct LUN disk, ensure that the nodes in the {virt} destination cluster that the VM is expected to run on can access the backend storage.

include::snip-migrating-luns.adoc[]
