// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_mod-docs-content-type: REFERENCE
[id="rhv-prerequisites_{context}"]
= {rhv-full} prerequisites

The following prerequisites apply to {rhv-full} ({rhv-short}) migrations:

* To create a source provider, you must have at least the `UserRole` and `ReadOnlyAdmin` roles assigned to you. These are the minimum required permissions, however, any other administrator or superuser permissions will also work.

[IMPORTANT]
====
You must keep the `UserRole` and `ReadOnlyAdmin` roles until the virtual machines of the source provider have been migrated. Otherwise, the migration will fail.
====

* To migrate virtual machines:
** You must have one of the following:
*** {rhv-short} admin permissions. These permissions allow you to migrate any virtual machine in the system.
*** `DiskCreator` and `UserVmManager` permissions on every virtual machine you want to migrate.

** You must use a xref:compatibility-guidelines_mtv[compatible version] of {rhv-full}.
** You must have the {manager} CA certificate, unless it was replaced by a third-party certificate, in which case, specify the {manager} Apache CA certificate.
+
You can obtain the {manager} CA certificate by navigating to https://<engine_host>/ovirt-engine/services/pki-resource?resource=ca-certificate&format=X509-PEM-CA in a browser.

** If you are migrating a virtual machine with a direct LUN disk, ensure that the nodes in the {virt} destination cluster that the VM is expected to run on can access the backend storage.

include::snip-migrating-luns.adoc[]
