// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-28-resolved-issues_{context}"]
= Resolved issues

{project-first} 2.8 has the following resolved issues:

[id="resolved-issues-2-8-1_{context}"]
== Resolved issues 2.8.1

.Cancelling the migration of a virtual machine causes the Plan controller to loop forever
In earlier releases of {project-short}, if a the migration of a virtual machine (VM) was cancelled, the scheduler of the Plan controller would endlessly reschedule it for migration. This issue has been resolved in {project-short} 2.8.1. Now if the migration a VM is cancelled, the migration proceeds correctly. link: https://issues.redhat.com/browse/MTV-2287[(MTV-2287)]

.MTV fails to migrate VMs whose name contains multiple dots
In earlier releases of {project-short}, a VM whose name contained multiple periods (for example, `vm...` ) could not be migrated because its name did not comply with the application and support protocal RFC DNS1123. This issue has been resolved in {project-short} 2.8.1. Now, {project-short} automatically changes multiple periods in a VM name to a single period, making the compliant with RFC DNS1123. link: https://issues.redhat.com/browse/MTV-2308[(MTV-2308)]

[id="resolved-issues-2-8-0_{context}"]
== Resolved issues 2.8.0

.MTV does not preserve the gateway IP address of an NIC from a different subnet
In earlier releases of {project-short}, the gateway IP address of the virtual machine was not copied after migration if the IP address was out of the network interface subnet range. This issue affected migrations even if you enabled the `Preserve static IPs` setting. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-2018[(MTV-2018)]

.MTV displays an error in the migration plan for VMs without a static IP address
In earlier releases of {project-short}, for migration plans in which `Preserve static IPs` is enabled, {project-short} displayed an error message if you did not configure a static IP address for the guest VM. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-1458[(MTV-1458)]

.Disk counter does not update progress while migrating VMs with multiple disks
In earlier releases of {project-short}, the `Disk Counter` did not show real-time progress of disk transfer when migrating a VM with multiple disks. This issue has been resolved in {project-short} 2.8.0.  link:https://issues.redhat.com/browse/MTV-1718[(MTV-1718)]

.Incomplete migration plan error for VMs with shared disks before cold migration
In earlier releases of {project-short}, the migration plan for a VM with shared disks showed an error that did not list all VMs to be powered off before the cold migration. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-2206[(MTV-2206)]

.MTV runs a migration plan after a VMware VM in the plan is canceled 
In earlier releases of {project-short}, during warm migrations of multiple VMware VMs, {project-short} continued to run the migration plan after you canceled a VM in the plan. The initial plan was run after you successfully migrated the canceled VM through a second migration plan. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-1796[(MTV-1796)]

.Static IP address is not preserved for VMs with manual MAC address configuration
In earlier releases of {project-short}, the static IP address of a VMware VM was not preserved if you configured a MAC address with uppercase for the virtual network adapter of the VM. This issue affected migrations where the `Preserve static IPs` setting was enabled and has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-2285[(MTV-2285)] 