// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-26_{context}"]
= {project-full} 2.6

You can use {the-lc} {project-first} to migrate virtual machines from the following source providers to {virt} destination providers:

* VMware vSphere
* {rhv-full} ({rhv-short})
* {osp}
* Open Virtual Appliances (OVAs) that were created by VMware vSphere
* Remote {virt} clusters

The release notes describe technical changes, new features and enhancements, known issues, and resolved issues.

[id="technical-changes-26_{context}"]
== Technical changes

This release has the following technical changes:

.Redesigned the migration plan creation wizard and dialog

The user interface console has improved the process of creating a migration plan.
The new migration plan dialog enables faster creation of migration plans. 

It includes only the minimal settings that are required, while you can confirgure advanced settings separately. The new dialog also provides defaults for network and storage mappings, where applicable. The new dialog can also be invoked from the the `Provider` > `Virtual Machines` tab, after selecting the virtual machines to migrate. It also better aligns with the user experience in the OCP console.

.`virtual machine preferences` have replaced {ocp-name} templates

The `virtual machine preferences` have replaced {ocp-name} templates. {project-short} currently falls back to using {ocp-name} templates when a relevant preference is not available.

Custom mappings of guest operating system type to virtual machine preference can be configured using `config` maps. This is in order to use custom virtual machine preferences, or to support more guest operating system types.

.Full support for migration from OVA

{project-short} migration from OVA is now a fully supported feature, and no longer Technical Preview.

.The VM is posted with its desired `Running` state

{project-short} shows each VM's migration `Running` state during the migration. This single `Running` operation replaces two previous operations, `Create/Post VM` and Run VM`.  link:https://issues.redhat.com/browse/MTV-794[(MTV-794)]

.The `must-gather` logs can now be loaded only by using the CLI

The {product-short} web console can no longer download logs. With this update, you must download `must-gather` logs by using CLI commands. for more information, see link:https://github.com/openshift/must-gather-operator[Must Gather Operator].

.Migrated VMs can now be reviewed and configured

The {project-short} web console now displays the name and migration status of each virtual machine (VM). The migrated VMs have the `app: <vmname>` label to help further changes in {ocp-name} Virtualization.
 the console displayed those details also before this change. the only difference here is that the VM is set with the `app: <vmname>` labels that makes it easier to make further configurations related to the VM on the target cluster
link:https://issues.redhat.com/browse/MTV-843[(MTV-843)]



[id="new-features-and-enhancements-26_{context}"]
== New features and enhancements

This part provides features and enhancements introduced in {project-full} 2.6:

.Validation for RHEL 6 guest operating system is now available when migrating VMs with RHEL 6 guest operating system

Red Hat Enterprise Linux (RHEL) 9 does not support RHEL 6 as a guest operating system. Therefore, RHEL 6 is not supported in {ocp-name} Virtualization. With this update, a validation of RHEL 6 guest operating system was added to {ocp-name} Virtualization. link:https://issues.redhat.com/browse/MTV-413[(MTV413)]

.Migrations from {ocp-name} versions before 4.13 are now blocked

The `Export API` function in {ocp-name} Virtualization now exposes VM manifests from {ocp-name} 4.13. Therefore, source {ocp} clusters must be version 4.13 or later. link:https://issues.redhat.com/browse/MTV-734[(MTV-734)]


.Automatic retrieval of CA certificates for the provider's URL in the console

The ability to retrieve CA certificates, which was available in previous versions, has been restortes. The `vSphere Verify certificate` option is in the `add-provider` dialog. This option was removed in the transition to {ocp} console, and has now been added to the console. This functionality is also available for RHV, OpenStack and OpenShift providers now
link:https://issues.redhat.com/browse/MTV-737[(MTV-737)]


.{project-short} UI plugin now uses only a dynamic plugin for the SDK REST API `fetch` methods

The UI plugin now uses a dynamic plugin for the SDK REST API when using the `fetch` methods. link:https://issues.redhat.com/browse/MTV-616[(MTV-616)]



.Plans that failed to migrate VMs can now be edited

With this update, you can edit plans that have failed to migrate any VMs. Some plans fail or are canceled because of incorrect network and storage mappings. You can now edit these plans until they succeed. link:https://issues.redhat.com/browse/MTV-779[(MTV-779)]


[id="ova-provider-26_{context}"]
=== Open Virtual Appliance Provider

The following are new features for the {project-short} Open Virtual Appliance (OVA) provider. link:https://issues.redhat.com/browse/MTV-690[(MTV-690)]

.Get firmware detection by virt-v2v

A `virt-v2v` that converts a guest also produces an OFV with configuration based on the virtual disk, such as driver or firmware. `forklift-controller` processes the produced OFV's status of the conversion pod. link:https://issues.redhat.com/browse/MTV-759[(MTV-759)]





.OVA inventory watcher detects deleted files

The OVA inventory watcher detects changes in files, including deleted files. Updates from the `ova-provider-server` pod are now sent every five minutes to the `forklift-controller` pod that updates the inventory. link:https://issues.redhat.com/browse/MTV-733[(MTV-733)]

.Migration from OVA validation rules

VM migrations from OVA are validated according to vSphere. The migration can use a similar structure and inventory variable names as vSphere, of which the OVA model is a subset. The rules do not apply to clusters, hosts, the running state of the VMs, or any configuration that is not relevant for the OVA VMs. link:https://issues.redhat.com/browse/MTV-669[(MTV-669)]

.VM cannot find the bootable disk when source VMware provider uses VDDK 8

When migrating from a source provider that uses VDDK (VMware Virtual Disk Development Kit) version 8, the migration completes successfully, but the converted guest cannot boot. The guest cannot find the boot disk. 

For a complete list of all resolved issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12430274[Resolved Issues] in Jira.

[id="known-issues-26_{context}"]
== Known issues

This release has the following known issues:

.Deleting a migration plan does not remove temporary resources

Deleting a migration plan does not remove temporary resources. 

* Importer pods
* Conversion pods
* Config maps
* Secrets
* Failed VMs
* Data volumes. 

To clean up the the temporary resources, you must archive a migration plan before deleting it. link:https://bugzilla.redhat.com/show_bug.cgi?id=2018974[(BZ#2018974)]

.Unclear error status message appears for VM with no operating system

The error status message for a VM with no operating system on the *Plans* page of the web console does not describe the reason for the failure. link:https://bugzilla.redhat.com/show_bug.cgi?id=2008846[(BZ#22008846)]

.Migration of virtual machines with encrypted partitions fails during a conversion (vSphere only)

vSphere only: Migrations from {rhv-short} and OpenStack do not fail, but the encryption key might be missing on the target {ocp} cluster.

.Migration fails during precopy and cutover while a snapshot operation is performed on the source VM

Warm migrations from {rhv-short} fail if a snapshot operation is performed on the source VM. If you perform a snapshot operation on the source VM at the time when a migration snapshot is scheduled, the migration fails instead of waiting for your snapshot operation to finish. link:https://issues.redhat.com/browse/MTV-456[(MTV-456)]

.Unable to schedule migrated VM with multiple disks to more than one storage class of type hostPath

When migrating a VM with multiple disks to more than one storage classes of the type `hostPath`, a VM might not be scheduled. 

To enable migrating a VM with multiple disks, use a shared storage on the target {ocp} cluster.

.Non-supported guest operating systems in warm migrations

Warm migrations and migrations to remote {ocp} clusters from vSphere do not support the same guest operating systems that are supported in cold migrations and migrations to the local {ocp} cluster. RHEL 8 and RHEL 9 might cause this limitation. +
See link:https://access.redhat.com/articles/1351473[Converting virtual machines from other hypervisors to KVM with virt-v2v in RHEL 7, RHEL 8, and RHEL 9] for the list of supported guest operating systems.

.VMs from vSphere with RHEL 9 guest operating system might start with network interfaces that are down

When migrating VMs that are installed with RHEL 9 as a guest operating system from vSphere, the network interfaces of the VMs could be disabled when they start in {ocp-name} Virtualization. link:https://issues.redhat.com/browse/MTV-491[(MTV-491)]

.Import OVA: ConnectionTestFailed message appears when adding OVA provider

When adding an OVA provider, the error message `ConnectionTestFailed` can instantly appear, although the provider is created successfully. If the message does not disappear after a few minutes and the provider status does not move to `Ready`, this means that the `ova server pod creation` has failed. link:https://issues.redhat.com/browse/MTV-671[(MTV-671)]

.Left over `ovirtvolumepopulator` from failed migration causes plan to stop indefinitely in `CopyDisks` phase.

An earlier failed migration can leave an outdated `ovirtvolumepopulator` in the project of a new plan for the same VM. The `CreateDataVolumes` phase does not create populator PVCs when transitioning to `CopyDisks`, causing the `CopyDisks` phase to stay indefinitely. link:https://issues.redhat.com/browse/MTV-929[(MTV-929)]

.Unclear error message when Forklift fails to build/create a PVC

The migration fails to build the PVC when the destination storage class does not have a configured storage profile. The error logs lack clear information to identify the reason for the failure. link:https://issues.redhat.com/browse/MTV-928[(MTV-928)]

.Fail to migrate a VM with NVME disks from vSphere 

When migrating a VM with NVME disks from vSphere, the migration process fails and the Web Console shows that the `Convert image to kubevirt` stage is `running` but did not finish successfully. link:https://issues.redhat.com/browse/MTV-963[(MTV-963)]

.Import image-based VMs can fail

Migrating an image-based VM without the `virtual_size` field can fail on a block mode storage class. link:https://issues.redhat.com/browse/MTV-946[(MTV-644)]

For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12430275[Known Issues] in Jira. 

[id="resolved-issues-26_{context}"]
== Resolved issues

This release has the following resolved issues:

.Deleting a provider automatically also deletes the PV

Each OVA provider has an attached PV and PVC. The PVC is deleted automatically when the provider is deleted. {project-short} now also deletes the PV when the provider is deleted. link:https://issues.redhat.com/browse/MTV-848[(MTV-848)]

.Data loss is no longer possible when migrating VMware VMs with snapshots

In the previous versions of {product-short}, when migrating a VMware VM that had a snapshot, the VM that was created in {ocp-name} Virtualization contained the data in the snapshot, but not in the running VM that was migrated. This has been resolved in {product-short} 2.6.0.  link:https://issues.redhat.com/browse/MTV-447[(MTV-447)]

.Adding an OVA provider no longer displays the `ConnectionTestFailed` error message

In the previous versions of {product-short}, when adding an OVA provider, `The provider is not ready - ConnectionTestFailed` error message appeared, even though the provider was eventually created. The message disappeared after a few seconds. This has been resolved in {product-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-671[(MTV-671)]

.Canceling and deleting a failed migration plan does not clean up the `populate` pods and PVC

When a user cancels and deletes a failed migration plan after creating a PVC and spawning the `populate` pods, the `populate` pods and PVC are not deleted. You must delete the pods and PVC manually. link:https://issues.redhat.com/browse/MTV-678[(MTV-678)]

.{ocp} to {ocp} migrations require the cluster version to be 4.13 or later

When migrating from {ocp} to {ocp}, the version of the source provider cluster must be {ocp} version 4.13 or later. link:https://issues.redhat.com/browse/MTV-809[(MTV-809)]


.Get firmware detection by virt-v2v

A `virt-v2v` that converts a guest also produces an OFV with configuration based on the virtual disk, such as driver or firmware. `forklift-controller` processes the produced OFV's status of the conversion pod. link:https://issues.redhat.com/browse/MTV-759[(MTV-759)]



.Creating a host secret requires validating the secret before creating the host

When creating a host secret, you must validate the secret before creating the host. to create a host secret, follow these steps:

. Create a secret
. Create a host
. Update the secret owner reference

link:https://issues.redhat.com/browse/MTV-868[(MTV-868)]


.RHV provider `ConnectionTestSucceeded` True response from the wrong URL

The `ConnectionTestSucceeded` condition was set to `True` even when the URL was different than the API endpoint for the RHV Manager. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-740[(MTV-740)]


.`ForkliftController` status shows `Failure` after upgrading from {project-short} 2.4.2 to {project-short} 2.5.0

After upgrading {project-short} from version 2.4.2 to 2.5.0, the `ForkliftController` returned the `Failure` status and an error message. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-702[(MTV-702)]

.Migration does not fail when a vSphere Datacenter is nested inside a folder
 
Previously, migrating a vSphere Datacenter succeeded when it was directly under the `/vcenter`, but failed when it was stored inside a folder. As a result, the migration raised an error. This issue was resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-796[(MTV-796)]

.Migration of image-based VM from {osp} to `default` project no longer fails

The migration process now succeeds when migrating an image-based VM from {osp} to the `default` project. The conversion of a virtual machine snapshot as part of the migration runs with non-root privileges, and {name-ocp} does not automatically pick a non-root user for the pod that starts on the `default` project. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-964[(MTV-964)]

For a complete list of all resolved issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12430274[Resolved Issues] in Jira.
