// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-22_{context}"]
= {project-full} 2.2

You can migrate virtual machines (VMs) from VMware vSphere or {rhv-full} to {virt} with {the-lc} {project-first}.

The release notes describe new features and enhancements, known issues, and technical changes.

[id="technical-changes-22_{context}"]
== Technical changes

.Setting the precopy interval for warm migration

You can set the interval between snapshots during the precopy stage of warm migration.

[id="new-features-and-enhancements-22_{context}"]
== New features and enhancements

This release adds the following features and improvements.

.Downloading logs by using the web console

You can download logs for a migration plan or a migrated VM in the {project-full} web console.

.Duplicating a migration plan

You can duplicate a migration plan, including its VMs, mappings, and hooks, in order to edit the copy and run as a new migration plan.

.Archiving a migration plan by using the web console

You can archive a migration plan. Archived plans can be viewed or duplicated. They cannot be run, edited, or unarchived.

[id="known-issues-22_{context}"]
== Known issues

.QEMU guest agent is not installed on migrated VMs

The QEMU guest agent is not installed on migrated VMs. Workaround: Install the QEMU guest agent with a post-migration hook. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2018062[*BZ#2018062*])

.Missing resource causes error message in current.log file

If a resource does not exist, for example, if the `virt-launcher` pod does not exist because the migrated VM is powered off, its log is unavailable.

The following error appears in the missing resource's `current.log` file when it is downloaded from the web console or created with the `must-gather` tool: `error: expected 'logs [-f] [-p] (POD | TYPE/NAME) [-c CONTAINER]'.` (link:https://bugzilla.redhat.com/show_bug.cgi?id=2023260[*BZ#2023260*])

.Importer pod log is unavailable after warm migration

Retaining the `Importer` pod for debug purposes causes warm migration to hang during the precopy stage. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2016290[*BZ#2016290*])

As a temporary workaround, the `Importer` pod is removed at the end of the precopy stage so that the precopy succeeds. However, this means that the `Importer` pod log is not retained after warm migration is complete. You can only view the `Importer` pod log by using the `oc logs -f <cdi-importer_pod>` command during the precopy stage.

This issue only affects the `Importer` pod log and warm migration. Cold migration and the `virt-v2v` logs are not affected.

.Deleting migration plan does not remove temporary resources.

Deleting a migration plan does not remove temporary resources such as `Importer` pods, `Conversion` pods, config maps, secrets, failed VMs and data volumes. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2018974[*BZ#2018974*]) You must archive a migration plan before deleting it in order to clean up the temporary resources.

.Unclear error status message for VM with no operating system

The error status message for a VM with no operating system on the *Migration plan details* page of the web console does not describe the reason for the failure. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2008846[*BZ#2008846*])

.Network, storage, and VM names in the Plan CR are not displayed in the web console.

If a Plan CR references storage, network, or VMs by name instead of by ID, the resources do not appear in the {project-full} web console. The migration plan cannot be edited or duplicated. (link:https://bugzilla.redhat.com/show_bug.cgi?id=1986020[*BZ#1986020*])
