// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="resolved-issues-2-9-0_{context}"]
= Resolved issues 2.9.0

.{project-short} enabled vTPM for source Windows Server 2022 virtual machines without vTPM device
VMware only: In earlier releases of {project-short}, after warm migration of Windows Server 2022 VMs with UEFI settings, the virtual Trusted Platform Module (vTPM) device was added to the VMs even though the source VMs did not have the vTPM device. This issue has been resolved in {project-short} 2.9.0. link:https://issues.redhat.com/browse/MTV-2014[(MTV-2014)]

//resolved or known issue?
.{project-short} does not fully preserve VMware virtual machine UUID after migration
In earlier releases of {project-short}, the UUID of VMware VMs were not fully preserved after migration to {ocp-short}. This issue has been resolved through a warning when you create a migration plan that VM UUIDs are truncated to 20 characters for `virtio` disks. link:https://issues.redhat.com/browse/MTV-1368[(MTV-1368)]

.{project-short} does not preserve host name of guest virtual machines after migration
link:https://issues.redhat.com/browse/MTV-2364[(MTV-2364)]

.Cold migration of VMware ESXi virtual machines stalled due to IP address resolution failure
link:https://issues.redhat.com/browse/MTV-2153[(MTV-2153)]

.{project-short} displayed an internal log error
link:https://issues.redhat.com/browse/MTV-2234[(MTV-2234)]