// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-26_{context}"]
= {project-full} 2.6

Migrate virtual machines (VMs) from VMware vSphere or {rhv-full} or {osp} to {virt} with {the-lc} {project-first}.

The release notes describe technical changes, new features and enhancements, and known issues.

[id="technical-changes-26_{context}"]
== Technical changes

{project-short} {project-z-version} is a maintenance release. There are no technical changes.
This release has the following technical changes:

[id="new-features-and-enhancements-26_{context}"]
== New features and enhancements

// {project-short} {project-z-version} is a maitenance release. There are no new features.
This release has the following features and improvements:

.Cross-Provider Features

Cross-provider features. link:https://issues.redhat.com/browse/MTV-802[(MTV-802)]


[id="known-issues-26_{context}"]
== Known issues

This release has the following known issues:

For 

[id="resolved-issues-26_{context}"]
== Resolved issues

This release has the following resolved issues:

