// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-26_{context}"]
= {project-full} 2.6

Migrate virtual machines (VMs) from VMware vSphere or {rhv-full} or {osp} to {virt} with {the-lc} {project-first}.

The release notes describe technical changes, new features and enhancements, and known issues.

[id="technical-changes-26_{context}"]
== Technical changes

// {project-short} {project-z-version} is a maintenance release. There are no technical changes.

This release has the following technical changes:

.Migration from OpenStack moves to being a fully supported feature

In this version of {project-short}, migration using OpenStack source providers graduated from a Technology Preview feature to a fully supported feature.
// 
// .Disabling FIPS
// 
// EMS enforcement is disabled for migrations with VMware vSphere source providers to enable migrations from versions of vSphere that are supported by {project-short} but do not comply with the 2023 FIPS requirements.

.Integration of the create and update provider user interface

The user interface of create and update providers now aligns with the look and feel of the {ocp} web console and displays up-to-date data.

.Standalone UI

The old UI of MTV 2.3 cannot be enabled by setting `feature_ui: true` in ForkliftController anymore.

.Errors logged in populator pods are improved

In previous releases of {project-short} {project-version}, populator pods were always restarted on failure. This made it difficult to gather the logs from the failed pods. In {project-short} 2.5.3, the number of restarts of populator pods is limited to three times. On the third and final time, the populator pod remains in the fail status and its logs can then be easily gathered by must-gather and by forklift-controller to know this step has failed. link:https://issues.redhat.com/browse/MTV-818[(MTV-818)]

.`VirtualMachineClusterFlavor`and `VirtualMachineClusterFlavor` CRDs replace OpenShift templates

Virtual Machine Flavor API will replace OpenShift templates. MTV currently fall back to using OpenShift templates when a relevant preference is not available.

.Full support for migration from OVA moves

{project-short} {project-version} supports migration from OVA moves.

.OpenShift Console `Create/Edit` pages replace Forms and Wizards

Forms and Wizards that use @migtools/lib-ui` have not worked properly when running inside the plugin. The migtool library was built fo a standalone application. The `Create` and `Edit` pages in the OpenShift Console replace them. link:https://issues.redhat.com/browse/MTV-615[(MTV-615)]

.Scan OVA files in the root folder of an NFS share

Files held directly on the NFS share are scanned, not requiring a folder. link:https://issues.redhat.com/browse/MTV-680[(MTV-680)]


[id="new-features-and-enhancements-26_{context}"]
== New features and enhancements

// {project-short} {project-z-version} is a maitenance release. There are no new features.
This release has the following features and improvements:

.Cross-Provider Features

This is a collection of new features that provide functionality across different cloud profiders. link:https://issues.redhat.com/browse/MTV-802[(MTV-802)]

..Replace templates with falvors

Kubevirt API introduces `VirtualMachineClusterFlavor` and `VirtualMachineFlavor` CDIs. These are meant to replace Template, which is only available on OpenShift. link:https://issues.redhat.com/browse/MTV-206[MTV-206]

..Integrate volume populators in remote migrations

Integrate volume populator for `oVirt` and OpenStack, together with `virt-v2v` on `el9` intop a CDI to migrate remote OCP clusters. link::https://issues.redhat.com/browse/MTV-721[MTV-721]

..VM posted with `Running` state

{project-short} shows the VM's migration `Running` state during the migration. link:https://issues.redhat.com/browse/MTV-794[MTV-794]

..Review and configure migrated VMs

The {project-short} web console shows the name and migration status of each VM. link:https://issues.redhat.com/browse/MTV-843[MTV-843]
// 
// ..CNV InstanceTypes
// 
// This looks like it repeats MTV-206 above

.RH-SDL

{project-short} conforms with the Red Hat Secure Development Lifecycle (RH-SDL) for users to follow an implementation plan that adopts security controls during the product lifecycle. link:https://issues.redhat.com/browse/MTV-801[(MTV-801)]
// Do we have public links to these documents?
// Additional RH-SDL resources:
// * link:https://docs.google.com/document/d/1QMrM5ac2sbecmy7lYHA8S6p8L8ivVwHlgdcspy-Z4VE/edit#heading=h.66y4kqbj468a[Red Hat Secure Development Lifecycle Implementation Plan]
// * link:https://docs.google.com/presentation/d/1CnIq-MHgEoq_1QgaFU5uoOfZ7ZOnNzxPk9OdDUe4Me8/edit#slide=id.g1a5a54f838a_0_1509[Red Hat Secure Development Lifecycle Introduction]
// * Link:https://docs.google.com/presentation/d/19H3tSzZ1pSGGwhSoZn3CFgyLQcBWbePAK0_5J4NHUGw/edit#slide=id.g22dc74ad918_0_740[Red Hat Secure Development Lifecycle Planning and Schedule]
// * link:https://docs.google.com/presentation/d/1DOxSd5hpwNntypX5DUd3JRmP8wIJL_RVxOJfDo0Nxck/edit#slide=id.g13028f60288_0_0[Secure Development - Introduction to SSML]
// * link:https://gitlab.cee.redhat.com/users/auth/geo/sign_in[Closed link]
// * link:https://docs.engineering.redhat.com/display/PRODSEC/Secure+Development+training[Secure Development Training]

.OCP Provider

OCP (OpenShift Container Platform) provider. link:https://issues.redhat.com/browse/MTV-739[(MTV-739)]

.Console Plugin

Console plugin. link:https://issues.redhat.com/browse/MTV-736[(MTV-736)]

.OVA Provider

OVA provider. link:https://issues.redhat.com/browse/MTV-690[(MTV-690)]

[id="known-issues-26_{context}"]
== Known issues

This release has the following known issues:

.Deleting migration plan does not remove temporary resources

Deleting a migration plan does not remove temporary resources such as importer pods, conversion pods, config maps, secrets, failed VMs and data volumes. You must archive a migration plan before deleting it to clean up the temporary resources. link:https://bugzilla.redhat.com/show_bug.cgi?id=2018974[(BZ#2018974)]

.Unclear error status message for VM with no operating system

The error status message for a VM with no operating system on the *Plans* page of the web console does not describe the reason for the failure. link:https://bugzilla.redhat.com/show_bug.cgi?id=2008846[(BZ#22008846)]

.Migration of virtual machines with encrypted partitions fails during conversion

vSphere only: Migrations from {rhv-short} and OpenStack do not fail, but the encryption key may be missing on the target {ocp} cluster.


.Migration fails during precopy/cutover while a snapshot operation is performed on the source VM

Warm migration from {rhv-short} fails if a snapshot operation is performed on the source VM. If a user performs a snapshot operation on the source VM at the time when a migration snapshot is scheduled, the migration fails instead of waiting for the user’s snapshot operation to finish. link:https://issues.redhat.com/browse/MTV-456[(MTV-456)]

.Unable to schedule migrated VM with multiple disks to more than one storage classes of type hostPath

When migrating a VM with multiple disks to more than one storage classes of type `hostPath`, it might happen that a VM cannot be scheduled. Workaround: Use shared storage on the target {ocp} cluster.

.Non-supported guest operating systems in warm migrations

Warm migrations and migrations to remote {ocp} clusters from vSphere do not support all types of guest operating systems that are supported in cold migrations to the local {ocp} cluster. This is a consequence of using RHEL 8 in the former case and RHEL 9 in the latter case. +
See link:https://access.redhat.com/articles/1351473[Converting virtual machines from other hypervisors to KVM with virt-v2v in RHEL 7, RHEL 8, and RHEL 9] for the list of supported guest operating systems.

.VMs from vSphere with RHEL 9 guest operating system may start with network interfaces that are down

When migrating VMs that are installed with RHEL 9 as guest operating system from vSphere, the network interfaces of the VMs could be disabled when they start in {ocp-name} Virtualization. link:https://issues.redhat.com/browse/MTV-491[(MTV-491)]

.Import OVA: ConnectionTestFailed message appears when adding OVA provider

When adding an OVA provider, the error message `ConnectionTestFailed` may instantly appear, although the provider is created successfully. If the message does not disappear after a few minutes and the provider status does not move to `Ready`, this means that the `ova server pod creation` has failed. link:https://issues.redhat.com/browse/MTV-671[(MTV-671)]

For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12424645[Known Issues] in Jira. 

[id="resolved-issues-26_{context}"]
== Resolved issues

This release has the following resolved issues:

// empty comment

