// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-22_{context}"]
= {project-full} 2.2

You can migrate virtual machines (VMs) from VMware vSphere or {rhv-full} to {virt} with {the-lc} {project-first}.

The release notes describe new features and enhancements, known issues, and technical changes.

// [id="technical-changes-22_{context}"]
// == Technical changes
//
// .TBD
//
// TBD
//
// [id="new-features-and-enhancements-22_{context}"]
// == New features and enhancements
//
// This release adds the following features and improvements.
//
// .TBD
//
// TBD

[id="known-issues-22_{context}"]
== Known issues

.QEMU guest agent is not installed on migrated VMs

The QEMU guest agent is not installed on migrated VMs. Workaround: Install the QEMU guest agent with a post-migration hook. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2018062[*BZ#2018062*])

.Importer pod log is unavailable after warm migration

Retaining the `Importer` pod for debug purposes causes warm migration to hang during the precopy stage. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2016290[*BZ#2016290*])

As a temporary workaround, the `Importer` pod is removed at the end of the precopy stage so that the precopy succeeds. However, this means that the `Importer` pod log is not retained after warm migration is complete. You can only view the `Importer` pod log by using the `oc logs -f <cdi-importer_pod>` command during the precopy stage.

This issue only affects the `Importer` pod log and warm migration. Cold migration and the `virt-v2v` logs are not affected.

.Deleting migration plan does not remove temporary resources.

Deleting a migration plan does not remove temporary resources such as `Importer` pods, `Conversion` pods, config maps, secrets, failed VMs and data volumes. (link:https://bugzilla.redhat.com/show_bug.cgi?id=2018974[*BZ#2018974*]) You must archive a migration plan before deleting it in order to clean up the temporary resources.
