// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-26_{context}"]
= {project-full} 2.6

You can use {the-lc} {project-first} to migrate virtual machines from the following source providers to {virt} destination providers:

* VMware vSphere
* {rhv-full} ({rhv-short})
* {osp}
* Open Virtual Appliances (OVAs) that were created by VMware vSphere
* Remote {virt} clusters

The release notes describe technical changes, new features and enhancements, known issues, and resolved issues.

[id="technical-changes-26_{context}"]
== Technical changes

This release has the following technical changes:

.Simplified the creation of vSphere providers

In earlier releases of {project-short}, users had to specify a fingerprint when creating a vSphere provider. This required users to retrieve the fingerprint from the server that vCenter runs on. {project-short} no longer requires this fingerprint as an input, but rather computes it from the specified certificate in the case of a secure connection or automatically retrieves it from the server that runs vCenter/ESXi in the case of an insecure connection.

.Redesigned the migration plan creation dialog

The user interface console has improved the process of creating a migration plan. The new migration plan dialog enables faster creation of migration plans.

It includes only the minimal settings that are required, while you can confirgure advanced settings separately. The new dialog also provides defaults for network and storage mappings, where applicable. The new dialog can also be invoked from the the `Provider` > `Virtual Machines` tab, after selecting the virtual machines to migrate. It also better aligns with the user experience in the OCP console.

.`virtual machine preferences` have replaced {ocp-name} templates

The `virtual machine preferences` have replaced {ocp-name} templates. {project-short} currently falls back to using {ocp-name} templates when a relevant preference is not available.

Custom mappings of guest operating system type to virtual machine preference can be configured using `config` maps. This is in order to use custom virtual machine preferences, or to support more guest operating system types.

.Full support for migration from OVA

Migration from OVA moves from being a Technical Preview and is now a fully supported feature.

.The VM is posted with its desired `Running` state

{project-short} creates the VM with its desired `Running` state on the target provider, instead of creating the VM and then running it as an additional operation. link:https://issues.redhat.com/browse/MTV-794[(MTV-794)]

.The `must-gather` logs can now be loaded only by using the CLI

The {project-short} web console can no longer download logs. With this update, you must download `must-gather` logs by using CLI commands. For more information, see link:https://github.com/openshift/must-gather-operator[Must Gather Operator].

.{project-short} no longer runs `pvc-init` pods when migrating from vSphere

{project-short} no longer runs `pvc-init` pods during cold migration from a vSphere provider to the {ocp-name} cluster that {project-short} is deployed on. However, in other flows where data volumes are used, they are set with the `cdi.kubevirt.io/storage.bind.immediate.requested` annotation, and CDI runs first-consume pods for storage classes with volume binding mode `WaitForFirstConsumer`.


[id="new-features-and-enhancements-26_{context}"]
== New features and enhancements

This section provides features and enhancements introduced in {project-full} 2.6.


[id="new-features-and-enhancements-26-3_{context}"]
=== New features and enhancements 2.6.3

////
****Removed as a resolved issue in 2.6.4****
.Preservation of static IPs in migrations from vSphere

You can now preserve static IPs of VMs that are installed with a Windows operating system and are migrated from vSphere. link:https://issues.redhat.com/browse/MTV-1148[(MTV-1148)]
////

.Support for migrating LUKS-encrypted devices in migrations from vSphere

You can now perform cold migrations from a vSphere provider of VMs whose virtual disks are encrypted by Linux Unified Key Setup (LUKS). link:https://issues.redhat.com/browse/MTV-831[(MTV-831)]

//2.6.3
.Specifying the primary disk when migrating from vSphere

You can now specify the primary disk when you migrate VMs from vSphere with more than one bootable disk. This avoids {project-short} automatically attempting to convert the first bootable disk that it detects while it examines all the disks of a virtual machine. This feature is needed because the first bootable disk is not necessarily the disk that the VM is expected to boot from in {virt}. link:https://issues.redhat.com/browse/MTV-1079[(MTV-1079)]

//2.6.3
.Links to remote provider UIs

You can now remotely access the UI of a remote cluster when you create a source provider. For example, if the provider is a remote {rhv-full} {rhv-short} cluster, {project-short} adds a link to the remote {rhv-short} web console when you define the provider. This feature makes it easier for you to manage and debug a migration from remote clusters. link:https://issues.redhat.com/browse/MTV-1054[(MTV-1054)]

[id="new-features-and-enhancements-26-0_{context}"]
=== New features and enhancements 2.6.0
// 2.6.0
.Migration from vSphere over a secure connection

You can now specify a CA certificate that can be used to authenticate the server that runs vCenter or ESXi, depending on the specified SDK endpoint of the vSphere provider. link:https://issues.redhat.com/browse/MTV-530[(MTV-530)]

// 2.6.0
.Migration to or from a remote {ocp-name} over a secure connection

You can now specify a CA certificate that can be used to authenticate the API server of a remote {ocp-name} cluster. link:https://issues.redhat.com/browse/MTV-728[(MTV-728)]

.Migration from an ESXi server without going through vCenter

{project-short} enables the configuration of vSphere providers with the SDK of ESXi. You need to select ESXi as the Endpoint type of the vSphere provider and specify the URL of the SDK of the ESXi server. link:https://issues.redhat.com/browse/MTV-514[(MTV-514)]

.Migration of image-based VMs from {osp}

{project-short} supports the migration of VMs that were created from images in {osp}. link:https://issues.redhat.com/browse/MTV-644[(MTV-644)]

.Migration of VMs with Fibre Channel LUNs from {rhv-short}

{project-short} supports migrations of VMs that are set with Fibre Channel (FC) LUNs from {rhv-short}. As with other LUN disks, you need to ensure the {ocp-name} nodes have access to the FC LUNs. During the migrations, the FC LUNs are detached from the source VMs in {rhv-short} and attached to the migrated VMs in {ocp-name}. link:https://issues.redhat.com/browse/MTV-659[(MTV-659)]

.Preserve CPU types of VMs that are migrated from {rhv-short}

{project-short} sets the CPU type of migrated VMs in {ocp-name} with their custom CPU type in {rhv-short}. In addition, a new option was added to migration plans that are set with {rhv-short} as a source provider to preserve the original CPU types of source VMs. When this option is selected, {project-short} identifies the CPU type based on the cluster configuration and sets this CPU type for the migrated VMs, for which the source VMs are not set with a custom CPU. link:https://issues.redhat.com/browse/MTV-547[(MTV-547)]

.Validation for RHEL 6 guest operating system is now available when migrating VMs with RHEL 6 guest operating system

Red Hat Enterprise Linux (RHEL) 9 does not support RHEL 6 as a guest operating system. Therefore, RHEL 6 is not supported in {ocp-name} Virtualization. With this update, a validation of RHEL 6 guest operating system was added to {ocp-name} Virtualization. link:https://issues.redhat.com/browse/MTV-413[(MTV413)]

.Automatic retrieval of CA certificates for the provider's URL in the console

The ability to retrieve CA certificates, which was available in previous versions, has been restored. The `vSphere Verify certificate` option is in the `add-provider` dialog. This option was removed in the transition to the {ocp} console and has now been added to the console. This functionality is also available for {rhv-short}, {osp}, and {ocp-name} providers now. link:https://issues.redhat.com/browse/MTV-737[(MTV-737)]

.Validation of a specified VDDK image

{project-short} validates the availability of a VDDK image that is specified for a vSphere provider on the target {ocp-name} name as part of the validation of a migration plan. {project-short} also checks whether the `libvixDiskLib.so` symbolic link (symlink) exists within the image. If the validation fails, the migration plan cannot be started. link:https://issues.redhat.com/browse/MTV-618[(MTV-618)]

.Add a warning and partial support for TPM

{project-short} presents a warning when attempting to migrate a VM that is set with a TPM device from {rhv-short} or vSphere. The migrated VM in {ocp-name} would be set with a TPM device but without the content of the TPM device on the source environment. link:https://issues.redhat.com/browse/MTV-378[(MTV-378)]

.Plans that failed to migrate VMs can now be edited

With this update, you can edit plans that have failed to migrate any VMs. Some plans fail or are canceled because of incorrect network and storage mappings. You can now edit these plans until they succeed. link:https://issues.redhat.com/browse/MTV-779[(MTV-779)]

.Validation rules are now available for OVA

The validation service includes default validation rules for virtual machines from the Open Virtual Appliance (OVA). link:https://issues.redhat.com/browse/MTV-669[(MTV-669)]


[id="resolved-issues-26_{context}"]
== Resolved issues

This release has the following resolved issues:

[id="resolved-issues-26-7_{context}"]
=== Resolved issues 2.6.7

.Incorrect handling of quotes in ifcfg files

In earlier releases of {project-short}, there was an issue with the incorrect handling of double quotes in interface configuration (ifcfg) files, which control the software interfaces for individual network devices. This issue has been resolved in {project-short} 2.6.7, in order to cover additional IP configurations on Red Hat Enterprise Linux, CentOS, Rocky Linux and similar distributions. link:https://issues.redhat.com/browse/MTV-1439[(MTV-1439)]

.Failure to preserve netplan based network configuration

In earlier releases of {project-short}, there was an issue with the preservation of netplan-based network configurations. This issue has been resolved in {project-short} 2.6.7, so that static IP configurations are preserved if netplan (netplan.io) is used by using the netplan configuration files to generate udev rules for known mac-address and `ifname` tuples. link:https://issues.redhat.com/browse/MTV-1440[(MTV-1440)]

.Error messages corrupt in udev .rules files

In earlier releases of {project-short}, there was an issue with the accidental leakage of error messages into udev .rules files. This issue has been resolved in {project-short} 2.6.7, with a static IP persistence script added to the udev rule file. link:link:https://issues.redhat.com/browse/MTV-1441[(MTV-1441)]

[id="resolved-issues-26-6_{context}"]
=== Resolved issues 2.6.6

.Runtime error: invalid memory address or nil pointer dereference

In earlier releases of {project-short}, there was a runtime error of `invalid memory address` or `nil pointer dereference` caused by a pointer that was nil, and there was an attempt to access the value that it points to. This issue has been resolved in {project-short} 2.6.6. link:https://issues.redhat.com/browse/MTV-1353[(MTV-1353)]

.All Plan and Migration pods scheduled to same node causing the node to crash

In earlier releases of {project-short}, the scheduler could place all migration pods on a single node. When this happened, the node ran out of the resources. This issue has been resolved in {project-short} 2.6.6. link:https://issues.redhat.com/browse/MTV-1354[(MTV-1354)]

.Empty bearer token is sufficient for authentication

In earlier releases of {project-short}, a vulnerability was found in the Forklift Controller.  There is no verification against the authorization header, except to ensure it uses bearer authentication. Without an authorization header and a bearer token, a `401` error occurs. The presence of a token value provides a 200 response with the requested information. This issue has been resolved in {project-short} 2.6.6.

For more details, see link:https://access.redhat.com/security/cve/cve-2024-8509[(CVE-2024-8509)].

[id="resolved-issues-26-5_{context}"]
=== Resolved issues 2.6.5

.VMware Linux interface name changes during migration

In earlier releases of {project-short}, during the migration of Rocky Linux 8, CentOS 7.2 and later, and Ubuntu 22 virtual machines (VM) from VMware to {ocp} (OCP), the name of the network interfaces is modified, and the static IP configuration for the VM is no longer functional. This issue has been resolved for static IPs in Rocky Linux 8, Centos 7.2 and later, Ubuntu 22 in {project-short} 2.6.5. link:https://issues.redhat.com/browse/MTV-595[(MTV-595)]

[id="resolved-issues-26-4_{context}"]
=== Resolved issues 2.6.4

.Disks and drives are offline after migrating Windows virtual machines from RHV or VMware to OCP

Windows (Windows 2022) VMs configured with multiple disks, which are *Online* before the migration, are *Offline* after a successful migration from {rhv-short} or VMware to {ocp}, using {project-short}. Only the `C:\` primary disk is *Online*. This issue has been resolved for basic disks in {project-short} 2.6.4. link:https://issues.redhat.com/browse/MTV-1299[(MTV-1299)]

For details of the known issue of dynamic disks being *Offline* in Windows Server 2022 after cold and warm migrations from vSphere to container-native virtualization (CNV) with Ceph RADOS Block Devices (RBD), using the storage class `ocs-storagecluster-ceph-rbd`, see xref:mtv-1344[(MTV-1344)].

.Preserve IP option for Windows does not preserve all settings

In earlier releases of {project-short}, while migrating a Windows 2022 Server with a static IP address assigned, and selecting the *Preserve static IPs* option, after a successful Windows migration, while the node started and the IP address was preserved, the subnet mask, gateway, and DNS servers were not preserved. This resulted in an incomplete migration, and the customer was forced to log in locally from the console to fully configure the network. This issue has been resolved in {project-short} 2.6.4. link:https://issues.redhat.com/browse/MTV-1286[(MTV-1286)]

.`qemu-guest-agent` not being installed at first boot in Windows Server 2022

After a successful Windows 2022 server guest migration using {project-short} 2.6.1, the `qemu-guest-agent` is not completely installed. The Windows Scheduled task is being created, however it is being set to run 4 hours in the future instead of the intended 2 minutes in the future. link:https://issues.redhat.com/browse/MTV-1325[(MTV-1325)]


[id="resolved-issues-26-3_{context}"]
=== Resolved issues 2.6.3

.CVE-2024-24788: `golang: net` malformed DNS message can cause infinite loop

In earlier releases of {project-short}, there was a flaw was discovered in the `stdlib` package of the Go programming language, which impacts previous versions of {project-short}. This vulnerability primarily threatens web-facing applications and services that rely on Go for DNS queries. This issue has been resolved in {project-short} 2.6.3.

For more details, see link:https://access.redhat.com/security/cve/cve-2024-24788[(CVE-2024-24788)].

.Migration scheduling does not take into account that `virt-v2v` copies disks sequentially (vSphere only)

In earlier releases of {project-short}, there was a problem with the way {project-short} interpreted the `controller_max_vm_inflight` setting for vSphere to schedule migrations. This issue has been resolved in {project-short} 2.6.3. link:https://issues.redhat.com/browse/MTV-1191[(MTV-1191)]

.Cold migrations fail after changing the ESXi network (vSphere only)

In earlier versions of {project-short}, cold migrations from a vSphere provider with an ESXi SDK endpoint failed if any network was used except for the default network for disk transfers. This issue has been resolved in {project-short} 2.6.3. link:https://issues.redhat.com/browse/MTV-1180[(MTV-1180)]

.Warm migrations over an ESXi network are stuck in `DiskTransfer` state (vSphere only)

In earlier versions of {project-short}, warm migrations over an ESXi network from a vSphere provider with a vCenter SDK endpoint were stuck in `DiskTransfer` state because {project-short} was unable to locate image snapshots. This issue has been resolved in {project-short} 2.6.3. link:https://issues.redhat.com/browse/MTV-1161[(MTV-1161)]

.Leftover PVCs are in `Lost` state after cold migrations

In earlier versions of {project-short}, after cold migrations, there were leftover PVCs that had a status of `Lost` instead of being deleted, even after the migration plan that created them was archived and deleted. Investigation showed that this was because importer pods were retained after copying, by default, rather than in only specific cases. This issue has been resolved in {project-short} 2.6.3. link:https://issues.redhat.com/browse/MTV-1095[(MTV-1095)]

.Guest operating system from vSphere might be missing (vSphere only)

In earlier versions of {project-short}, some VMs that were imported from vSphere were not mapped to a template in {ocp-short} while other VMs, with the same guest operating system, were mapped to the corresponding template. Investigations indicated that this was because vSphere stopped reporting the operating system after not receiving updates from VMware tools for some time. This issue has been resolved in {project-short} 2.6.3 by taking the value of the operating system from the output of the investigation that `virt-v2v` performs on the disks. link:https://issues.redhat.com/browse/MTV-1046[(MTV-1046)]


[id="resolved-issues-26-2_{context}"]
=== Resolved issues 2.6.2

.CVE-2023-45288: Golang `net/http, x/net/http2`: unlimited number of `CONTINUATION` frames can cause a denial-of-service (DoS) attack

A flaw was discovered with the implementation of the `HTTP/2` protocol in the Go programming language, which impacts previous versions of {project-short}. There were insufficient limitations on the number of CONTINUATION frames sent within a single stream. An attacker could potentially exploit this to cause a denial-of-service (DoS) attack. This flaw has been resolved in {project-short} 2.6.2.

For more details, see link:https://access.redhat.com/security/cve/cve-2023-45288[(CVE-2023-45288)].

.CVE-2024-24785: `mtv-api-container`: Golang `html/template: errors` returned from `MarshalJSON` methods may break template escaping

A flaw was found in the `html/template` Golang standard library package, which impacts previous versions of {project-short}. If errors returned from `MarshalJSON` methods contain user-controlled data, they may be used to break the contextual auto-escaping behavior of the HTML/template package, allowing subsequent actions to inject unexpected content into the templates. This flaw has been resolved in {project-short} 2.6.2.

For more details, see link:https://access.redhat.com/security/cve/cve-2024-24785[(CVE-2024-24785)].

.CVE-2024-24784: `mtv-validation-container`: Golang `net/mail`: comments in display names are incorrectly handled

A flaw was found in the `net/mail` Golang standard library package, which impacts previous versions of {project-short}. The `ParseAddressList` function incorrectly handles comments, text in parentheses, and display names. As this is a misalignment with conforming address parsers, it can result in different trust decisions being made by programs using different parsers. This flaw has been resolved in {project-short} 2.6.2.

For more details, see link:https://access.redhat.com/security/cve/cve-2024-24784[(CVE-2024-24784)].

.CVE-2024-24783: `mtv-api-container`: Golang `crypto/x509`: Verify panics on certificates with an unknown public key algorithm

A flaw was found in the `crypto/x509` Golang standard library package, which impacts previous versions of {project-short}. Verifying a certificate chain that contains a certificate with an unknown public key algorithm causes `Certificate.Verify` to panic. This affects all `crypto/tls` clients and servers that set `Config.ClientAuth` to `VerifyClientCertIfGiven` or `RequireAndVerifyClientCert`. The default behavior is for TLS servers to not verify client certificates. This flaw has been resolved in {project-short} 2.6.2.

For more details, see link:https://access.redhat.com/security/cve/cve-2024-24783[(CVE-2024-24783)].

.CVE-2023-45290: `mtv-api-container`: Golang `net/http` memory exhaustion in `Request.ParseMultipartForm`

A flaw was found in the `net/http` Golang standard library package, which impacts previous versions of {project-short}. When parsing a `multipart` form, either explicitly with `Request.ParseMultipartForm` or implicitly with `Request.FormValue`, `Request.PostFormValue`, or `Request.FormFile`, limits on the total size of the parsed form are not applied to the memory consumed while reading a single form line. This permits a maliciously crafted input containing long lines to cause the allocation of arbitrarily large amounts of memory, potentially leading to memory exhaustion. This flaw has been resolved in {project-short} 2.6.2.

For more details, see link:https://access.redhat.com/security/cve/cve-2023-45290[(CVE-2023-45290)].

.ImageConversion does not run when target storage is set with WaitForFirstConsumer (WFFC)

In earlier releases of {project-short}, migration of VMs failed because the migration was stuck in the `AllocateDisks` phase. As a result of being stuck, the migration did not progress, and PVCs were not bound. The root cause of the issue was that `ImageConversion` did not run when target storage was set for `wait-for-first-consumer`. The problem was resolved in {project-short} 2.6.2. link:https://issues.redhat.com/browse/MTV-1126[(MTV-1126)]


.forklift-controller panics when importing VMs with direct LUNs

In earlier releases of {project-short}, `forklift-controller` panicked when a user attempted to import VMs that had direct LUNs. The problem was resolved in {project-short} 2.6.2. link:https://issues.redhat.com/browse/MTV-1134[(MTV-1134)]

[id="resolved-issues-26-1_{context}"]
=== Resolved issues 2.6.1

.VMs with multiple disks that are migrated from vSphere and OVA files are not being fully copied

In {project-short} 2.6.0, there was a problem in copying VMs with multiple disks from VMware vSphere and from OVA files. The migrations appeared to succeed but all the disks were transferred to the same PV in the target environment while other disks were empty. In some cases, bootable disks were overridden, so the VM could not boot. In other cases, data from the other disks was missing. The problem was resolved in {project-short} 2.6.1. link:https://issues.redhat.com/browse/MTV-1067[(MTV-1067)]

.Migrating VMs from one {ocp} cluster to another fails due to a timeout

In {project-short} 2.6.0,  migrations from one {ocp} cluster to another failed when the time to transfer the disks of a VM exceeded the time to live (TTL) of the Export API in {ocp-name}, which was set to 2 hours by default. The problem was resolved in {project-short} 2.6.1 by setting the default TTL of the Export API to 12 hours, which greatly reduces the possibility of an expiration of the Export API. Additionally, you can increase or decrease the TTL setting as needed. link:https://issues.redhat.com/browse/MTV-1052[(MTV-1052)]

.{project-short} forklift-controller pod crashes when receiving a disk without a datastore

In earlier releases of {project-short}, if a VM was configured with a disk that was on a datastore that was no longer available in vSphere at the time a migration was attempted, the `forklift-controller` crashed, rendering {project-short} unusable. In {project-short} 2.6.1, {project-short} presents a critical validation for VMs with such disks, informing users of the problem, and the `forklift-controller` no longer crashes, although it cannot transfer the disk. link:https://issues.redhat.com/browse/MTV-1029[(MTV-1029)]

[id="resolved-issues-26-0_{context}"]
=== Resolved issues 2.6.0

.Deleting an OVA provider automatically also deletes the PV

In earlier releases of {project-short}, the PV was not removed when the OVA provider was deleted. This has been resolved in {project-short} 2.6.0, and the PV is automatically deleted when the OVA provider is deleted. link:https://issues.redhat.com/browse/MTV-848[(MTV-848)]

.Fix for data being lost when migrating VMware VMs with snapshots

In earlier releases of {project-short}, when migrating a VM that has a snapshot from VMware, the VM that was created in {ocp-name} Virtualization contained the data in the snapshot but not the latest data of the VM. This has been resolved in {project-short} 2.6.0.  link:https://issues.redhat.com/browse/MTV-447[(MTV-447)]

.Canceling and deleting a failed migration plan does not clean up the `populate` pods and PVC

In earlier releases of {project-short}, when you canceled and deleted a failed migration plan, and after creating a PVC and spawning the `populate` pods, the `populate` pods and PVC were not deleted. You had to delete the pods and PVC manually. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-678[(MTV-678)]

.{ocp} to {ocp} migrations require the cluster version to be 4.13 or later

In earlier releases of {project-short}, when migrating from {ocp} to {ocp}, the version of the source provider cluster had to be {ocp} version 4.13 or later. This issue has been resolved in {project-short} 2.6.0, with validation being shown when migrating from versions of {ocp-name} before 4.13. link:https://issues.redhat.com/browse/MTV-734[(MTV-734)]

.Multiple storage domains from RHV were always mapped to a single storage class

In earlier releases of {project-short}, multiple disks from different storage domains were always mapped to a single storage class, regardless of the storage mapping that was configured. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-1008[(MTV-1008)]

.Firmware detection by virt-v2v

In earlier releases of {project-short}, a VM that was migrated from an OVA that did not include the firmware type in its OVF configuration was set with UEFI. This was incorrect for VMs that were configured with BIOS. This issue has been resolved in {project-short} 2.6.0, as {project-short} now consumes the firmware that is detected by `virt-v2v` during the conversion of the disks. link:https://issues.redhat.com/browse/MTV-759[(MTV-759)]

.Creating a host secret requires validation of the secret before creation of the host

In earlier releases of {project-short}, when configuring a transfer network for vSphere hosts, the console plugin created the `Host` CR before creating its secret. The secret should be specified first in order to validate it before the `Host` CR is posted. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-868[(MTV-868)]

.When adding OVA provider a `ConnectionTestFailed` message appears

In earlier releases of {project-short}, when adding an OVA provider, the error message `ConnectionTestFailed` instantly appeared, although the provider had been created successfully. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-671[(MTV-671)]

.RHV provider `ConnectionTestSucceeded` True response from the wrong URL

In earlier releases of {project-short}, the `ConnectionTestSucceeded` condition was set to `True` even when the URL was different than the API endpoint for the RHV Manager. This issue has been resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-740[(MTV-740)]

.Migration does not fail when a vSphere Data Center is nested inside a folder

In earlier releases of {project-short}, migrating a VM that is placed in a Data Center that is stored directly under the `/vcenter` in vSphere succeeded. However, it failed when the Data Center was stored inside a folder. This issue was resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-796[(MTV-796)]

.The OVA inventory watcher detects deleted files

The OVA inventory watcher detects files changes, including deleted files. Updates from the `ova-provider-server` pod are now sent every five minutes to the `forklift-controller` pod that updates the inventory. link:https://issues.redhat.com/browse/MTV-733[(MTV-733)]

.Unclear error message when Forklift fails to build or create a PVC

In earlier releases of {project-short}, the error logs lacked clear information to identify the reason for a failure to create a PV on a destination storage class that does not have a configured storage profile. This issue was resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-928[(MTV-928)]

.Plans stay indefinitely in the `CopyDisks` phase when there is an outdated ovirtvolumepopulator

In earlier releases of {project-short}, an earlier failed migration could have left an outdated `ovirtvolumepopulator`. When starting a new plan for the same VM to the same project,  the `CreateDataVolumes` phase did not create populator PVCs when transitioning to `CopyDisks`, causing the `CopyDisks` phase to stay indefinitely. This issue was resolved in {project-short} 2.6.0. link:https://issues.redhat.com/browse/MTV-929[(MTV-929)]


For a complete list of all resolved issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12436210[Resolved Issues] in Jira.

[id="known-issues-26_{context}"]
== Known issues

This release has the following known issues:

[WARNING]
.Warm migration and remote migration flows are impacted by multiple bugs
====
Warm migration and remote migration flows are impacted by multiple bugs. It is strongly recommended to fall back to cold migration until this issue is resolved. link:https://issues.redhat.com/browse/MTV-1366[(MTV-1366)]
====

.Migrating older Linux distributions from VMware to {ocp}, the name of the network interfaces changes

When migrating older Linux distributions, such as CentOS 7.0 and 7.1, virtual machines (VMs) from VMware to {ocp}, the name of the network interfaces changes, and the static IP configuration for the VM no longer functions. This issue is caused by RHEL 7.0 and 7.1 still requiring `virtio-transitional`. Workaround: Manually update the guest to RHEL 7.2 or update the VM specification post-migration to use transitional. link:https://issues.redhat.com/browse/MTV-1382[(MTV-1382)]

.[[mtv-1344]]Dynamic disks are offline in Windows Server 2022 after migration from vSphere to CNV with `ceph-rbd`

The dynamic disks are *Offline* in Windows Server 2022 after cold and warm migrations from vSphere to container-native virtualization (CNV) with Ceph RADOS Block Devices (RBD), using the storage class `ocs-storagecluster-ceph-rbd`. link:https://issues.redhat.com/browse/MTV-1344[(MTV-1344)]

.Unclear error status message for VM with no operating system

The error status message for a VM with no operating system on the *Plans* page of the web console does not describe the reason for the failure. link:https://bugzilla.redhat.com/show_bug.cgi?id=2008846[(BZ#22008846)]

.Migration of virtual machines with encrypted partitions fails during a conversion (vSphere only)

vSphere only: Migrations from {rhv-short} and {osp} do not fail, but the encryption key might be missing on the target {ocp} cluster.

.Migration fails during precopy/cutover while performing a snapshot operation on the source VM

Warm migration from {rhv-short} fails if a snapshot operation is triggered and running on the source VM at the same time as the migration is scheduled. The migration does not wait for the snapshot operation to finish. link:https://issues.redhat.com/browse/MTV-456[(MTV-456)]

.Unable to schedule migrated VM with multiple disks to more than one storage class of type `hostPath`

When migrating a VM with multiple disks to more than one storage class of type `hostPath`, it might happen that a VM cannot be scheduled. Workaround: Use shared storage on the target {ocp} cluster.

.Non-supported guest operating systems in warm migrations

Warm migrations and migrations to remote {ocp} clusters from vSphere do not support the same guest operating systems that are supported in cold migrations and migrations to the local {ocp} cluster. RHEL 8 and RHEL 9 might cause this limitation.

See link:https://access.redhat.com/articles/1351473[Converting virtual machines from other hypervisors to KVM with virt-v2v in RHEL 7, RHEL 8, and RHEL 9] for the list of supported guest operating systems.

.VMs from vSphere with RHEL 9 guest operating system can start with network interfaces that are down

When migrating VMs that are installed with RHEL 9 as a guest operating system from vSphere, the network interfaces of the VMs could be disabled when they start in {ocp-name} Virtualization. link:https://issues.redhat.com/browse/MTV-491[(MTV-491)]


.Migration of a VM with NVME disks from vSphere fails

When migrating a virtual machine (VM) with NVME disks from vSphere, the migration process fails, and the Web Console shows that the `Convert image to kubevirt` stage is `running` but did not finish successfully. link:https://issues.redhat.com/browse/MTV-963[(MTV-963)]

.Importing image-based VMs can fail

Migrating an image-based VM without the `virtual_size` field can fail on a block mode storage class. link:https://issues.redhat.com/browse/MTV-946[(MTV-946)]

.Deleting a migration plan does not remove temporary resources

Deleting a migration plan does not remove temporary resources such as importer pods, conversion pods, config maps, secrets, failed VMs, and data volumes. You must archive a migration plan before deleting it to clean up the temporary resources. link:https://bugzilla.redhat.com/show_bug.cgi?id=2018974[(BZ#2018974)]

.Migrating VMs with independent persistent disks from VMware to OCP-V fails

Migrating VMs with independent persistent disks from VMware to OCP-V fails. link:https://issues.redhat.com/browse/MTV-993[(MTV-993)]

.Guest operating system from vSphere might be missing

When vSphere does not receive updates about the guest operating system from the VMware tools, it considers the information about the guest operating system to be outdated and ceases to report it. When this occurs, {project-short} is unaware of the guest operating system of the VM and is unable to associate it with the appropriate virtual machine preference or {ocp-name} template. link:https://issues.redhat.com/browse/MTV-1046[(MTV-1046)]

.Failure to migrate an image-based VM from {osp} to the `default` project

The migration process fails when migrating an image-based VM from {osp} to the `default` project. link:https://issues.redhat.com/browse/MTV-964[(MTV-964)]

For a complete list of all known issues in this release, see the list of link:https://issues.redhat.com/issues/?filter=12436209[Known Issues] in Jira.
