// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_content-type: CONCEPT
[id="resolved-issues-2-10-2_{context}"]
= Resolved issues 2.10.2

XCOPY usage detection during volume population::

Before this update, there was no indication of whether Extended Copy (XCOPY) was used during volume population. When copying with `vmkfstools` falls back to host copy because of storage array configuration errors or network issues, users were unaware if XCOPY was in use or not. With this release, XCOPY usage detection is implemented in the `vmkfstools-wrapper` tool. As a result, users can now monitor whether XCOPY was used during volume population through the new `vsphere_xcopy_volume_populator_xcopy_used` metric.
+
link:https://issues.redhat.com/browse/MTV-3090[MTV-3090]

Improved data transfer efficiency with FC prioritization::

Before this update, host mapping prioritized iSCSI over FC when both were present. As a result, users experienced data transfer fallback to network copy when both FC and iSCSI adapters were online. With this release, FC adapters are checked before iSCSI for volume mapping. FC is prioritized over iSCSI for ESXi adapters, reducing potential network copy fallbacks and improving data transfer efficiency.
+
link:https://issues.redhat.com/browse/MTV-3966[MTV-3966] 

Resolved inspection pod failures during large-scale warm migrations::

Before this update, inspection pod failures occurred during large-scale warm migrations because the parent backing of disks was missing. This update introduces a retry limit for obtaining the parent backing of disks during inspection. As a result, large-scale warm migrations complete successfully, reducing the occurrence of inspection pod failures and stalled pods during the `PreflightInspection` step.
+
link:https://issues.redhat.com/browse/MTV-4059[MTV-4059] 

Resolved certificate validation errors for VM migrations with pre-migration hooks::

Before this update, the {virt} migration of VMs with pre-migration hooks caused migration plan failure in the Initialize phase because of certificate validation issues. With this update, certificate validation errors are resolved for migration of VMs with pre-migration hooks.
+
link:https://issues.redhat.com/browse/MTV-2894[MTV-2894] 

