// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-2.5_{context}"]
= {project-full} 2.5

You can use {the-lc} {project-first} to migrate virtual machines from the following source providers to {virt} destination providers:

* VMware vSphere
* {rhv-full} ({rhv-short})
* {osp}
* Open Virtual Appliances (OVAs) that were created by VMware vSphere
* Remote {virt} clusters

The release notes describe technical changes, new features and enhancements, and known issues for {project-full}.

[id="technical-changes-25_{context}"]
== Technical changes

This release has the following technical changes:

// Speak to Arik about technical changes for MTV 2.5.5

.Migration from OpenStack moves to being a fully supported feature

In this version of {project-short}, migration using OpenStack source providers graduated from a Technology Preview feature to a fully supported feature.

.Disabling FIPS

EMS enforcement is disabled for migrations with VMware vSphere source providers to enable migrations from versions of vSphere that are supported by {project-short} but do not comply with the 2023 FIPS requirements.

.Integration of the create and update provider user interface

The user interface of create and update providers now aligns with the look and feel of the {ocp} web console and displays up-to-date data.

.Standalone UI

The old UI of MTV 2.3 cannot be enabled by setting `feature_ui: true` in ForkliftController anymore.

.Errors logged in populator pods are improved

// thanks Arik.
In previous releases of {project-short} {project-version}, populator pods were always restarted on failure. This made it difficult to gather the logs from the failed pods. In {project-short} 2.5.3, the number of restarts of populator pods is limited to three times. On the third and final time, the populator pod remains in the fail status and its logs can then be easily gathered by must-gather and by forklift-controller to know this step has failed. link:https://issues.redhat.com/browse/MTV-818[(MTV-818)]

[id="new-features-and-enhancements-25_{context}"]
== New features and enhancements

This release has the following features and improvements:

.Migration using OVA files created by VMware vSphere

// i need to wait for this ticket to be merged to add a link
In {project-short} {project-version}, you can migrate using Open Virtual Appliance (OVA) files that were created by VMware vSphere as source providers. link:https://issues.redhat.com/browse/MTV-336[(MTV-336)]

[NOTE]
====
Migration of OVA files that were not created by VMware vSphere but are compatible with vSphere might succeed. However, migration of such files is not supported by {project-short}. {project-short} supports only OVA files created by VMware vSphere.
====

include::snippet_ova_tech_preview.adoc[]

.Migrating VMs between {ocp} clusters

In {project-short} {project-version}, you can now use Red Hat {virt} provider as a source provider as well as a destination provider. You can migrate VMs from the cluster that MTV is deployed on to another cluster, or from a remote cluster to the cluster that {project-short} is deployed on. link:https://issues.redhat.com/browse/MTV-571[(MTV-571)]

.Migration of VMs with direct LUNs from RHV

During the migration from RHV, direct LUNs are detached from the source virtual machines and attached to the target virtual machines. Note that this mechanism does not work yet for Fibre Channel. link:https://issues.redhat.com/browse/MTV-329[(MTV-329)]

.Additional authentication methods for OpenStack

In addition to standard password authentication, the following authentication methods are supported: Token authentication and Application credential authentication. link:https://issues.redhat.com/browse/MTV-539[(MTV-539)]

.Validation rules for OpenStack

The validation service includes default validation rules for virtual machines from OpenStack. link:https://issues.redhat.com/browse/MTV-508[(MTV-508)]

.VDDK is now optional for VMware vSphere providers

The VMware vSphere source provider can now be created without specifying a VDDK `init` image. It is strongly recommended to create a VDDK `init` image to accelerate migrations.

.Deployment on OKE enabled

In {project-short} 2.5.3, deployment on OpenShift Kubernetes Engine (OKE) has been enabled. For more information, see link:https://docs.openshift.com/container-platform/4.14/welcome/oke_about.html[About OpenShift Kubernetes Engine]. link:https://issues.redhat.com/browse/MTV-803[(MTV-803)]

.Migration of VMs to destination storage classes with encrypted RBD now supported

In {project-short} 2.5.4, migration of VMs to destination storage classes that have encrypted RADOS Block Devices (RBD) volumes is now supported.

To make use of this new feature, set the value of the parameter `controller_block_overhead` to `1Gi`, following the procedure in link:https://access.redhat.com/documentation/en-us/migration_toolkit_for_virtualization/2.5/html-single/installing_and_using_the_migration_toolkit_for_virtualization/index#configuring-mtv-operator_mtv[Configuring the MTV Operator]. link:https://issues.redhat.com/browse/MTV-851[(MTV-851)]

[id="known-issues-25_{context}"]
== Known issues

This release has the following known issues:

.Known issue

Known issue

[id="resolved-issues-255_{context}"]
== Resolved issues

This release has the following resolved issues:

.CVE-2024021484 jsrsasign package vulnerable to Observable Discrepancy

The *jsrsasign* package is vulnerable to an Observable Discrepancy when precessed by RSA PKCS 1.5 or RSAOAEP decryption process. This vulnerability allows an attacker to decrypt cyphertexts, which gives the attacker access to cyphertexts encrypted with the same key.

////
[id="deprecated-features-25_{context}"]
== Deprecated features

This release has the following deprecated feature:

.Migration from {rhv-full} 4.3

Migration from {rhv-full} 4.3 has been deprecated in {project-short} {project-version}.
////
