// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_mod-docs-content-type: REFERENCE
[id="resolved-issues-2-10-6_{context}"]
= Resolved issues 2.10.6

[role="_abstract"]
Review the resolved issues in this release of {project-short}.

XFSv4 migrations failed::
{project-short} 2.10.1 was rebased to {rhel-first} 10, which does not support XFS version 4 (XFSv4). As a result, XFSv4 migrations failed for {project-short} 2.10.1-2.10.5. With this release, a new `spec.xfsCompatibility` option is available on the migration plan. When set to `false`, the default setting, the plan uses the standard conversion image. When set to `true`, the plan uses the XFS-compatible conversion image instead of the standard conversion image. 
+
[WARNING]
====
If you enable XFS support for a migration plan, then the plan cannot support Btrfs migration.
====
+
link:https://issues.redhat.com/browse/MTV-4685[MTV-4685] and link:https://issues.redhat.com/browse/MTV-4709[MTV-4709]


Migrations with shared disk migration disabled failed::

In {project-short}, migration of shared disks is done by running two migration plans, one with the `migrateSharedDisk` option set to `true` and one with the option set to `false`. Before this update, the migration plan with the option set to `false` failed because an unnecessary `populator` pod was created. With this release, the unnecessary pod is not created, and migration of shared disks works as expected.
+
link:https://issues.redhat.com/browse/MTV-4555[MTV-4555]