// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-21_{context}"]
= {project-full} 2.1

[id="technical-changes-21_{context}"]
== Technical changes

[id="vddk-image-21_{context}"]
=== VDDK image

The VMware Virtual Disk Development Kit (VDDK) SDK image is referenced in the `HyperConverged` custom resource. Before this release, it was referenced in the `v2v-vmware` config map.

[id="new-features-and-enhancements-21_{context}"]
== New features and enhancements

This release adds the following features and improvements.

[id="cold-migration-from-rhv-21_{context}"]
=== Cold migration from {rhv-full}

You can perform a cold migration of VMs from {rhv-full}.

[id="migration-hooks-21_{context}"]
=== Migration hooks

You can create migration hooks to run Ansible playbooks or custom code before or after migration.

[id="filtered-must-gather-data-collection-21_{context}"]
=== Filtered must-gather data collection

You can specify options for the `must-gather` tool that enable you to filter the data by namespace, migration plan, or VMs.

[id="sr-iov-network-support-21_{context}"]
=== SR-IOV network support

You can migrate VMs with a single root I/O virtualization (SR-IOV) network interface if the {virt} environment has an SR-IOV network.

[id="known-issues-21_{context}"]
== Known issues

[id="disk-copy-stage-does-not-progress-21_{context}"]
=== Disk copy stage does not progress
// to be fixed in 2.2
The disk copy stage of a {rhv-short} VM does not progress and the {project-short} web console does not display an error message. link:https://bugzilla.redhat.com/show_bug.cgi?id=1990596[(*BZ#1990596*)]

The cause of this problem might be one of the following conditions:

* The storage class does not exist on the target cluster.
* The VDDK image has not been added to the `HyperConverged` custom resource.
* The VM does not have a disk.
* The VM disk is locked.
* The VM time zone is not set to UTC.
* The VM is configured for a USB device.
+
To disable USB devices, see link:https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html-single/virtual_machine_management_guide/index#sect-Configuring_USB_Devices[Configuring USB Devices] in the Red Hat Virtualization documentation.

To determine the cause:

. Click *Workloads* -> *Virtualization* in the {ocp} web console.
. Click the *Virtual Machines* tab.
. Select a virtual machine to open the *Virtual Machine Overview* screen.
. Click *Status* to view the status of the virtual machine.

[id="vm-time-zone-must-be-utc-with-no-offset-21_{context}"]
=== VM time zone must be UTC with no offset

The time zone of the source VMs must be UTC with no offset. You can set the time zone to `GMT Standard Time` after first assessing the potential impact on the workload. link:https://bugzilla.redhat.com/show_bug.cgi?id=1993259[(*BZ#1993259*)]

[id="rhv-resource-uuid-causes-a-provider-not-found-error-21_{context}"]
=== {rhv-short} resource UUID causes a "Provider not found" error

If a {rhv-short} resource UUID is used in a `Host`, `NetworkMap`, `StorageMap`, or `Plan` custom resource (CR), a "Provider not found" error is displayed.

You must use the resource name. link:https://bugzilla.redhat.com/show_bug.cgi?id=1994037[(*BZ#1994037*)]

[id="same-rhv-resource-name-in-different-data-centers-21_{context}"]
=== Same {rhv-short} resource name in different data centers causes ambiguous reference

If a {rhv-short} resource name is used in a `NetworkMap`, `StorageMap`, or `Plan` custom resource (CR) and if the same resource name exists in another data center, the `Plan` CR displays a critical "Ambiguous reference" condition. You must rename the resource or use the resource UUID in the CR.

In the web console, the resource name appears twice in the same list without a data center reference to distinguish them. You must rename the resource. link:https://bugzilla.redhat.com/show_bug.cgi?id=1993089[(*BZ#1993089*)]
