// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_mod-docs-content-type: CONCEPT
[id="resolved-issues-2-11-0_{context}"]
= Resolved issues 2.11.0

[role="_abstract"]
Review the resolved issues in this release of {project-short}.

Target cluster namespaces now visible for cross-cluster live migration::

Before this update, during cross-cluster live migration, projects were fetched from the host cluster instead of the target cluster. As a consequence, target cluster namespaces were not visible in the UI, causing user inconvenience. With this release, cross-cluster live migration fetches project data from the target cluster, making target cluster namespaces visible in the UI during migration.
+
link:https://issues.redhat.com/browse/MTV-3915[MTV-3915]

VDDK image archive upload succeeds in private namespaces::

Before this update,  VMware Virtual Disk Development Kit (VDDK) image archive upload failure occurred in private namespaces due to incorrect namespace usage. As a consequence, users experienced VDDK image upload failure in private namespaces during source provider creation. With this release, you can upload VDDK tar archives successfully in private namespaces. 
+
link:https://issues.redhat.com/browse/MTV-3618[3618]

Correct UI display of migration type after change::

Before this update, if you changed the `Migration type` on the Plan details page in the {project-short} UI from warm to cold, the YAML file was updated correctly but the UI did not display the the updated migration type. With this release, the UI edit field for `Migration type` updates the migration type in the YAML file and the UI correctly displays the updated migration type.
+
link:https://issues.redhat.com/browse/MTV-3476[MTV-3476]

Correct VM name display in migration progress::

Before this update, during the migration of a VM with a non-conformant name in OpenShift, the name was standardized. However, the migration progress in the {project-short} UI showed the original non-conformant VM name. As a consequence, users saw incorrect VM names in the Migration progress list, with links causing `404` errors. With this release, the migration progress now shows accurate VM names and links.
+
link:https://issues.redhat.com/browse/MTV-4386[MTV-4386]

Resolved "Unable to retrieve data" error in cold migration plans with static IP preservation::

Before this update, users encountered an "Unable to retrieve data" error during VM listing in cold migration plans created with static IP preservation on vCenter7. With this release, cold migration plans now retrieve VM data correctly, eliminating 'Unable to retrieve data' errors.
+
link:https://issues.redhat.com/browse/MTV-3266[MTV-3266]

Improved `DiskTransfer` warm migration progress Indicator::

Before this update, the warm migration progress indicator for `DiskTransfer` remained unchecked due to incomplete progress evaluation. As a consequence, users saw incomplete migration progress for the `DiskTransfer` step. With this release, the `DiskTransfer` progress indicator shows a checkmark when all tasks are completed, improving migration visibility.
+
link:https://issues.redhat.com/browse/MTV-3585[MTV-3585]  

Fetch and populate volumes for storage mappings during plan creation for OCP provider::

Before this update, you could not fetch and populate volumes for storage mappings from Red Hat OpenShift Container Platform (OCP) during plan creation for an OCP provider. With this release, plan creation for host-to-host plans includes fetching and populating source storage, improving the selection of storage mappings during plan creation.
+
link:https://issues.redhat.com/browse/MTV-3574[MTV-3574]

Improved cluster-to-cluster live migration network mapping in OCP::

Before this update, incorrect management of network attachments in Red Hat OpenShift Container Platform (OCP) target networks during updates led to complications with network mapping during live migration, resulting in inaccurate network configurations. With this release, the target network mapping issue in {project-short} for an OCP source provider is resolved. As a result, cluster-to-cluster live migration now correctly maps networks, improving migration accuracy.
+
link:https://issues.redhat.com/browse/MTV-3576[MTV-3576]

Removed misleading VM shutdown message during migrations for OVA providers::

Before this update, users received a misleading message about VM shutdown during Open Virtual Appliance (OVA) migration, even though no VMs are sourced for OVA providers. With this release, the incorrect message for OVA providers during plan migration is removed. 
+
link:https://issues.redhat.com/browse/MTV-3572[MTV-3572]

Adjusted 'Tips and tricks' link placement to avoid conflict with reserved UI elements::

Before this update, the 'Tips and tricks' link placement in the upper-right corner of the {project-short} UI conflicted with reserved UI elements. As a consequence, UI elements were misaligned, causing content shift and potential confusion. With this release, the 'Tips and tricks' link is displayed to the left side of the reserved UI element. As a result, the UI now has improved consistency.
+
link:https://issues.redhat.com/browse/MTV-3870[MTV-3870]

Topic selector consistency improvement::

Before this update, the topic selector in the Tips and tricks panel in the {project-short} UI displayed the active topic while it was pointing to the active topic. As a consequence, end users saw duplicate topic headings in the topic selector and the top area of the Tips and tricks panel. With this release, the topic selector defaults to `No topic selected`, enhancing the overall UI consistency.
+
link:https://issues.redhat.com/browse/MTV-3869[MTV-3869]

Improved Migration plan page visibility for target projects::

Before this update, the Migration plan page in the {project-short} UI displayed the `openshift-mtv` project by default, but the target project was not displayed by default. With this update, the default view of the Migration plan page now includes the 'Target project' column, enhancing visibility and navigation for migration plans.
+
link:https://issues.redhat.com/browse/MTV-3864[MTV-3864]

Restoration of 'Target name' column on Virtual machines tab::

Before this update, the removal of the 'Target name' column during {project-short} product updates caused the column to disappear from the `Virtual machines` tab on the Plan details page in the {project-short} UI. With this release, the 'Target name' column on the `Virtual machines` tab is now restored. 
+
link:https://issues.redhat.com/browse/MTV-4238[MTV-4238] 

Removal of invalid NADs during network map creation::

Before this update, the {project-short} UI became unresponsive when trying to remove an invalid Network Attachment Definition (NAD) during network map creation from YAML. With this release, you can remove network maps with invalid NAD IDs and manage network maps more effectively.
+
link:https://issues.redhat.com/browse/MTV-3610[MTV-3610]


