// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-28-resolved-issues_{context}"]
= Resolved issues

{project-first} 2.8 has the following resolved issues:

[id="resolved-issues-2-8-3_{context}"]
== Resolved issues 2.8.3

.VMware disks named by using a PVC template are not sorted correctly
In earlier releases of {project-short}, VMware disks with names generated by using a PVC template were not sorted by using the same method as the VM builder. This issue has been resolved in {project-short} 2.8.3. link:https://issues.redhat.com/browse/MTV-2303[(MTV-2303)]

.Post-migration hooks do not run
In earlier releases of {project-short}, post-migration hooks failed to mount a `ConfigMap`API object. As a result, post-migration hooks did not run. This issue has been resolved in {project-short} 2.8.3. link:https://issues.redhat.com/browse/MTV-2421[(MTV-2421)]

[id="resolved-issues-2-8-2_{context}"]
== Resolved issues 2.8.2

.MTV does not add a separator after the name of a PVC when a custom name template is used
In earlier releases of {project-short}, when a custom PVC template was used, the name of the PVC was followed immediately by the random alphanumeric characters that {project-short} generates to ensure that PVC names are unique. As a result, it was difficult to distinguish between the name the template generated and the random characters. This issue has been resolved in {project-short} 2.8.2 by {project-short} adding a hyphen (`-`) as a separator between the name generated by the template and the random characters added by {project-short}. link:https://issues.redhat.com/browse/MTV-2257[(MTV-2257)]

.The static route gateway of Windows VMs is passed as the default gateway during migration
In earlier releases of {project-short}, the static route gateway of Windows virtual machines (VMs) was passed as the default gateway during migration instead of the actual default gateway. This caused VMs to be incorrectly configured. This issue has been resolved in {project-short} 2.8.2. link:https://issues.redhat.com/browse/MTV-2408[(MTV-2408)]

.MTV does not list any VM that is part of a vApp
In earlier releases of {project-short}, any VM that was part of a VMware vApp was not listed. This issue has been resolved in {project-short} 2.8.2. link:https://issues.redhat.com/browse/MTV-1153[(MTV-1153)]
 
[id="resolved-issues-2-8-1_{context}"]
== Resolved issues 2.8.1

.VMs with mutually exclusive spec values as source VM and destination VM cannot be migrated
In earlier releases of {project-short}, it was possible for a VM to have the `spec` value `Running` as a source VM with the `spec` value `runStrategy` as a destination VM. This caused migrations to fail because `Running` and `runStrategy` are mutually exclusive. This issue has been resolved in {project-short} 2.8.1. link:https://issues.redhat.com/browse/MTV-2092[(MTV-2092)]

.The code base of MTV contains a deprecated value for a parameter
In earlier releases of {project-short}, the code base contained the deprecated value `vm.Spec.Running`, which caused some migrations to fail. This issue has been resolved in {project-short} 2.8.1. link:https://issues.redhat.com/browse/MTV-2105[(MTV-2105)]

.Migrations using custom templates fail if a user-supplied name is too long
In earlier releases of {project-short}, migrations that used custom templates failed if a user-supplied was too long because it exceeded 63 characters. This issue has been resolved in {project-short} 2.8.1. Now {project-short} automatically truncates names that are too long. link:https://issues.redhat.com/browse/MTV-2244[(MTV-2244)]

.User supplied template names are not validated against the RFC DNS1123 standard
In earlier releases of {project-short}, user-supplied template names were not validated against the RFC DNS1123 standard. This caused migrations of VMs with template names that did not conform to RFC DNS1123 to fail. This issue has been resolved in {project-short} 2.8.1. link:https://issues.redhat.com/browse/MTV-2249[(MTV-2249)]

.Canceling the migration of a virtual machine causes the Plan controller to loop forever
In earlier releases of {project-short}, if the migration of a virtual machine (VM) was canceled, the scheduler of the Plan controller would endlessly reschedule it for migration. This issue has been resolved in {project-short} 2.8.1. link:https://issues.redhat.com/browse/MTV-2287[(MTV-2287)]

.MTV fails to migrate VMs with template names that contain multiple periods
In earlier releases of {project-short}, a VM whose name contained multiple periods (for example, `vm...`) could not be migrated because its name did not comply with the application and support protocol RFC DNS1123. This issue has been resolved in {project-short} 2.8.1. Now, {project-short} automatically changes multiple periods in a VM name to a single period, making it compliant with RFC DNS1123. link:https://issues.redhat.com/browse/MTV-2308[(MTV-2308)]

.UI displays an incorrect "Invalid VM Name" message for a VM name containing a period
In earlier releases of {project-short}, the UI displayed an "Invalid VM Name" message for a VM name containing a period, even though {project-short} supports such names. This issue has been resolved in {project-short} 2.8.1. link:https://issues.redhat.com/browse/MTV-2309[(MTV-2309)]

[id="resolved-issues-2-8-0_{context}"]
== Resolved issues 2.8.0

.MTV does not preserve the gateway IP address of an NIC from a different subnet
In earlier releases of {project-short}, the gateway IP address of the virtual machine was not copied after migration if the IP address was out of the network interface subnet range. This issue affected migrations even if you enabled the `Preserve static IPs` setting. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-2018[(MTV-2018)]

.MTV displays an error in the migration plan for VMs without a static IP address
In earlier releases of {project-short}, for migration plans in which `Preserve static IPs` is enabled, {project-short} displayed an error message if you did not configure a static IP address for the guest VM. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-1458[(MTV-1458)]

.Disk counter does not update progress while migrating VMs with multiple disks
In earlier releases of {project-short}, the `Disk Counter` did not show real-time progress of disk transfer when migrating a VM with multiple disks. This issue has been resolved in {project-short} 2.8.0.  link:https://issues.redhat.com/browse/MTV-1718[(MTV-1718)]

.Incomplete migration plan error for VMs with shared disks before cold migration
In earlier releases of {project-short}, the migration plan for a VM with shared disks showed an error that did not list all VMs to be powered off before the cold migration. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-2206[(MTV-2206)]

.MTV runs a migration plan after a VMware VM in the plan is canceled 
In earlier releases of {project-short}, during warm migrations of multiple VMware VMs, {project-short} continued to run the migration plan after you canceled a VM in the plan. The initial plan was run after you successfully migrated the canceled VM through a second migration plan. This issue has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-1796[(MTV-1796)]

.Static IP address is not preserved for VMs with manual MAC address configuration
In earlier releases of {project-short}, the static IP address of a VMware VM was not preserved if you configured a MAC address with uppercase for the virtual network adapter of the VM. This issue affected migrations where the `Preserve static IPs` setting was enabled and has been resolved in {project-short} 2.8.0. link:https://issues.redhat.com/browse/MTV-2285[(MTV-2285)] 