// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="rn-26_{context}"]
= {project-full} 2.6

Migrate virtual machines (VMs) from VMware vSphere or {rhv-full} or {osp} to {virt} with {the-lc} {project-first}.

The release notes describe technical changes, new features and enhancements, and known issues.

[id="technical-changes-26_{context}"]
== Technical changes

// {project-short} {project-z-version} is a maintenance release. There are no technical changes.

This release has the following technical changes:

.Technical change

Technical change

[id="new-features-and-enhancements-26_{context}"]
== New features and enhancements

// {project-short} {project-z-version} is a maitenance release. There are no new features.
This release has the following features and improvements:

.Cross-Provider Features

Cross-provider features. link:https://issues.redhat.com/browse/MTV-802[(MTV-802)]

.RH-SDL

RH-SDL. link:https://issues.redhat.com/browse/MTV-801[(MTV-801)]

.OCP Provider

OCP (OpenShift Container Platform) provider. link:https://issues.redhat.com/browse/MTV-739[(MTV-739)]

.Console Plugin

Console plugin. link:https://issues.redhat.com/browse/MTV-736[(MTV-736)]

.OVA Provider

OVA provider. link:https://issues.redhat.com/browse/MTV-690[(MTV-690)]

[id="known-issues-26_{context}"]
== Known issues

This release has the following known issues:

For 

[id="resolved-issues-26_{context}"]
== Resolved issues

This release has the following resolved issues:
