// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

:_content-type: CONCEPT
[id="resolved-issues-2-10-5_{context}"]
= Resolved issues 2.10.5

[role="_abstract"]
Review the resolved issues in this release of {project-short}.

A fatal error occurred when migrating win-virtio VMs::

Before this update, migrations of `win-virtio` VMs failed due to a `MEMORY MANAGEMENT` fatal error. With this release, the error no longer occurs and migrations of `win-virtio` VMs work as expected.
+
link:https://issues.redhat.com/browse/MTV-4534[MTV-4534]

Warm migrations of VMs with multiple VirtIO disks failed::

Before this update, warm migrations of VMs with multiple VirtIO disks failed due to a `virt-v2v` issue. The failure prevented {project-short} from identifying the disks. With this release, `virt-v2v` works as expected, allowing {project-short} to identify multiple VirtIO disks correctly and to migrate the VMs as expected.
+
link:https://issues.redhat.com/browse/MTV-4130[MTV-4130]