// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="running-live-migration-plan_{context}"]
= Running a migration plan for a live migration between {virt} clusters

[role="_abstract"]
You can run a migration plan and view its progress in the {ocp} web console.

.Prerequisites

* Valid migration plan.

.Procedure

. In the {ocp} web console, click *Migration* > *Plans for virtualization*.
+
The *Plans* list displays the source and target providers, the number of virtual machines (VMs) being migrated, the status, the date that the migration started, and the description of each plan.

. Click *Start* beside a migration plan to start the migration.
. Click *Start* in the confirmation window that opens.
+
The plan's *Status* changes to *Running*, and the migration's progress is displayed in the following stages:
+
* *Initiate* : Migration begins.
* *PrepareTarget*: {project-short} creates empty target `DataVolumes` in the target {virt} cluster. {project-short} then copies all secrets or config maps that are mounted by a source VM to the target namespace. {project-short} then creates target VMs in a running state. {project-short} also creates a `VirtualMachineInstanceMIgration` resource for each cluster so that the VMs can synchronize.
* *Synchronization*: {virt} now synchronizes the VMs by using the `KubeVirt` resource of each source VM to transfer the VM's state to each target VM. This communication is done using the `VirtualMachineInstanceMIgration` resource. 
+
[WARNING]
====
Do not take a snapshot of a VM after you start a migration. Taking a snaphot after a migration starts might cause the migration to fail. 
====
+
. Optional: Click the links in the migration's *Status* to see its overall status and the status of each VM:

** The link on the left indicates whether the migration failed, succeeded, or is ongoing. It also reports the number of VMs whose migration succeeded, failed, or was canceled.
** The link on the right opens the *Virtual Machines* tab of the *Plan Details* page. For each VM, the tab displays the following data:

*** The name of the VM
*** The start and end times of the migration
*** A progress pipeline for the VM's migration

. Optional: To view your migration's logs, either as it is running or after it is completed, perform the following actions:

.. Click the *Virtual Machines* tab.
.. Click the arrow (*>*) to the left of the virtual machine whose migration progress you want to check.
+
The VM's details are displayed.
+
.. In the *Pods* section, in the *Pod links* column, click the *Logs* link.
+
The *Logs* tab opens.
+
[NOTE]
====
Logs are not always available. The following are common reasons for logs not being available:

* The migration is from {virt} to {virt}. In this case, `virt-v2v` is not involved, so no pod is required.
* No pod was created.
* The pod was deleted.
* The migration failed before running the pod.
====

.. To see the raw logs, click the *Raw* link.
.. To download the logs, click the *Download* link.
