// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="running-migration-plan_{context}"]
= Running a migration plan

You can run a migration plan and view its progress in the {ocp} web console.

.Prerequisites

* Valid migration plan.

.Procedure

. In the {ocp} web console, click *Migration* -> *Plans for virtualization*.
+
The *Plans* list displays the source and target providers, the number of virtual machines (VMs) being migrated, the status, and the description of each plan.

. Click *Start* beside a migration plan to start the migration.
. Click *Start* in the confirmation window that opens.
+
The plan's *Status* changes to *Running* and migration's progress is displayed.
+
Warm migration only:

* The precopy stage starts.
* Click *Cutover* to complete the migration.

. Click the links in the migration's *Status* to see its overall status and the status of each VM:

** The link on the left indicates whether the migration failed, succeeded, or is ongoing and reports the number of VMs whose migration succeeded, failed, or was canceled.
** The link on the right opens the *Virtual Machines* tab of the *Plan Details* page. For each VM, the tab displays the name of the VM, the start and end times of the migration, the amount of data copied, and a progress pipeline for its migration.

. To view your migration's logs, either as it is running or after it is completed:

.. Click the *Virtual Machines* tab.
.. Click the arrow (*>*) to the left of the virtual machine whose migration progress you want to check.
+
The VM's details are displayed.
+
.. In the *Pods* section, in the *Pod links* column, click the *Logs* link.
+
The *Logs* tab opens.
+
[NOTE]
====
Logs are not always available. The most common reasons for this are:

* The migration is from {virt} to {virt}. In this case, `virt-v2v` is not involved, so no pod is required.
* No pod was created.
* The pod was deleted.
* The migration failed prior to running the pod.
====

.. To see the raw logs, click the *Raw* link.
.. To download the logs, click the *Download* link.


