// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="selecting-migration-network-for-virt-provider_{context}"]
= Selecting a migration network for {a-virt} provider

You can select a default migration network for {a-virt} provider in the {ocp} web console to improve performance. The default migration network is used to transfer disks to the namespaces in which it is configured.

If you do not select a migration network, the default migration network is the `pod` network, which might not be optimal for disk transfer.

[NOTE]
====
You can override the default migration network of the provider by selecting a different network when you create a migration plan.
====



.Procedure

. In the {ocp} web console, click *Migration* > *Providers for virtualization*.
. Click the {virt} provider whose migration network you want to change. 
+
When the *Providers detail* page opens:

. Click the *Networks* tab.
. Click *Set default transfer network*.
. Select a default transfer network from the list and click *Save*.
