// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="selecting-migration-network-for-source-provider_{context}"]
= Selecting a migration network for a VMware provider

You can select a migration network in the {project-short} web console for a VMware source provider to reduce risk to the VMware environment and to improve performance.

The default migration network is the management network. However, using the management network for migration can result in poor performance because the network might not have sufficient bandwidth. This situation can have a negative effect on the VMware platform because the disk transfer operation might saturate the network and impede communication between vCenter and the ESXi hosts.

.Prerequisites

* The migration network must have sufficient throughput, minimum speed of 10 Gbps, for disk transfer.
* The migration network must be accessible to the {virt} nodes through the default gateway.
+
[NOTE]
====
The source virtual disks are copied by a pod that is connected to the pod network of the target namespace.
====

* The migration network must have jumbo frames enabled.
* You must have administrator privileges for each ESXi host.

.Procedure

. In the {project-short} web console, click *Providers*
. Click *VMware*.
. Click the host number in the *Hosts* column beside a VMware provider to view a list of hosts.
. Select one or more hosts and click *Select migration network*.
. Complete the following fields:

* *Network*: Select the migration network.
+
You can clear the migration network selection by selecting the default management network.

* *ESXi host admin username*: Specify the ESXi host admin user name, for example, `root`.
* *ESXi host admin password*: Specify the ESXi host password.

. Click *Save*.
. Verify that the status of each host is *Ready*.
+
If a host status is not *Ready*, the host might be unreachable on the migration network or the credentials might be incorrect. You can modify the host configuration and save the changes.
