// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-cnv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-osp.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-ova.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-rhv.adoc
// * documentation/doc-Planning_your_migration/assemblies/assembly_planning-migration-vmware.adoc

:_mod-docs-content-type: PROCEDURE
[id="selecting-migration-network-for-virt-provider_{context}"]
= Selecting a migration network for {a-virt} provider

[role="_abstract"]
You can select a default migration network for {a-virt} provider in the {ocp} web console to improve performance. The default migration network is used to transfer disks to the namespaces in which it is configured.

After you select a transfer network, associate its network attachment definition (NAD) with the gateway to be used by this network.

In {project-short} version 2.9 and earlier, {project-short} used the `pod` network as the default network. 

In version 2.10.0 and later, {project-short} detects if you have selected a user-defined network (UDN) as your default network. Therefore, if you set the UDN to be the migration's namespace, you do not need to select a new default network when you create your migration plan. 

[IMPORTANT]
====
{project-short} supports using UDNs for all providers except {virt}.
====

For more information about UDNs, see 'About user defined networks' in _Migrating your virtual machines to Red Hat {virt}_. Migration procedures have been updated to include UDNs.

[NOTE]
====
You can override the default migration network of the provider by selecting a different network when you create a migration plan.
====

.Procedure

. In the {ocp} web console, click *Migration* > *Providers for virtualization*.
. Click the {virt} provider whose migration network you want to change.
+
When the *Providers detail* page opens:

. Click the *Networks* tab.
. Click *Set default transfer network*.
. Select a default transfer network from the list and click *Save*.
. Configure a gateway in the network used for {project-short} migrations by completing the following steps:
.. In the {ocp} web console, click *Networking* > *NetworkAttachmentDefinitions*.
.. Select the appropriate default transfer network NAD.
.. Click the *YAML* tab.
.. Add `forklift.konveyor.io/route` to the metadata:annotations section of the YAML, as in the following example:
+
[source,yaml,subs="attributes+"]
----
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-network
  namespace: mtv-test
  annotations:
    forklift.konveyor.io/route: <IP address> # <1>
----
<1> The `NetworkAttachmentDefinition` parameter is needed to configure an IP address for the interface, either from the Dynamic Host Configuration Protocol (DHCP) or statically. Configuring the IP address enables the interface to reach the configured gateway.
.. Click *Save*.
