:_content-type: SNIPPET

ifdef::vmware,dest_vwmware[]

[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:creating-migration-plan-2-8_vmware[Creating a migration plan].
====

endif::[]

ifdef::dest_rhv[]

[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:creating-migration-plan-2-8_rhv[Creating a migration plan].
====

endif::[]

ifdef::dest_ostack[]

[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:creating-migration-plan-2-8_ostack[Creating a migration plan].
====

endif::[]

ifdef::dest_ova[]

[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:creating-migration-plan-2-8_ostack[Creating a migration plan].
====

endif::[]

ifdef::dest_cnv[]

[NOTE]
====
If you input any value of maximum transmission unit (MTU) besides the default value in your migration network, you must also input the same value in the {ocp-short} transfer network that you use. For more information about the {ocp-short} transfer network, see xref:creating-migration-plan-2-8_cnv[Creating a migration plan].
====

endif::[]
