// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_prerequisites-for-migration.adoc

:_mod-docs-content-type: REFERENCE
[id="ref_source-vm-prerequisites_{context}"]
= Source VM prerequisites

[role="_abstract"]
Source VM prerequisites apply to all migrations from a source provider to {virt}. 

Prerequisites::

* ISO images and CD-ROMs are unmounted.
* Each NIC contains either an IPv4 address or an IPv6 address, although a NIC may use both.
* The operating system of each VM is certified and supported as a guest operating system for conversions.

[NOTE]
====
You can check that the operating system is supported by referring to the table in link:https://access.redhat.com/articles/1351473[Converting virtual machines from other hypervisors to KVM with virt-v2v]. See the columns of the table that refer to RHEL 8 hosts and RHEL 9 hosts.
====

* VMs that you want to migrate with MTV 2.6._z_ run on RHEL 8.
* VMs that you want to migrate with MTV 2.7._z_ run on RHEL 9.
* The name of a VM must not contain a period (`.`). {project-first} changes any period in a VM name to a dash (`-`).
* The name of a VM must not be the same as any other VM in the {virt} environment.

