// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="source-vm-prerequisites_{context}"]
= Source virtual machine prerequisites

The following prerequisites apply to all migrations:

* ISO/CDROM disks must be unmounted.
* Each NIC must contain one IPv4 and/or one IPv6 address.
* The operating system of a VM must be certified and supported as a link:https://access.redhat.com/articles/973163#ocpvirt[guest operating system with {virt}].
* The name of a VM must not contain a period (`.`). {project-first} changes any period in a VM name to a dash (`-`).
* The name of a VM must not be the same as any other VM in the {virt} environment.
+
[NOTE]
====
{project-full} automatically assigns a new name to a VM that does not comply with the rules.

{project-full} makes the following changes when it automatically generates a new VM name:

* Excluded characters are removed.
* Uppercase letters are switched to lowercase letters.
* Any underscore (`_`) is changed to a dash (`-`).

This feature allows a migration to proceed smoothly even if someone enters a VM name that does not follow the rules.
====

include::snip_secure_boot_issue.adoc[]

include::snip_measured_boot_windows_vm.adoc[]
