// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="about-storage_{context}"]
= Storage support and default modes

{project-short} uses the following default volume and access modes for supported storage.

[NOTE]
====
If the {virt} storage does not support link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/storage/dynamic-provisioning[dynamic provisioning], you must apply the following settings:

* `Filesystem` volume mode
+
`Filesystem` volume mode is slower than `Block` volume mode.
* `ReadWriteOnce` access mode
+
`ReadWriteOnce` access mode does not support live virtual machine migration.

See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/virtualization/virtual-machines#virt-customizing-storage-profile_virt-creating-data-volumes[Enabling a statically-provisioned storage class] for details on editing the storage profile.
====

[NOTE]
====
If your migration uses block storage and persistent volumes created with an EXT4 file system, increase the file system overhead in CDI to be more than 10%. The default overhead that is assumed by CDI does not completely include the reserved place for the root partition. If you do not increase the file system overhead in CDI by this amount, your migration might fail.
====


.Default volume and access modes
[cols="1,1,1", options="header"]
|===
|Provisioner |Volume mode |Access mode

|kubernetes.io/aws-ebs
|Block
|ReadWriteOnce

|kubernetes.io/azure-disk
|Block
|ReadWriteOnce

|kubernetes.io/azure-file
|Filesystem
|ReadWriteMany

|kubernetes.io/cinder
|Block
|ReadWriteOnce

|kubernetes.io/gce-pd
|Block
|ReadWriteOnce

|kubernetes.io/hostpath-provisioner
|Filesystem
|ReadWriteOnce

|manila.csi.openstack.org
|Filesystem
|ReadWriteMany

|openshift-storage.cephfs.csi.ceph.com
|Filesystem
|ReadWriteMany

|openshift-storage.rbd.csi.ceph.com
|Block
|ReadWriteOnce

|kubernetes.io/rbd
|Block
|ReadWriteOnce

|kubernetes.io/vsphere-volume
|Block
|ReadWriteOnce
|===
