// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_prerequisites-for-migration.adoc

:_mod-docs-content-type: REFERENCE
[id="about-storage_{context}"]
= Storage support and default modes

[role="_abstract"]
{project-first} uses the following default volume and access modes for supported storage.

.Default volume and access modes
[cols="1,1,1", options="header"]
|===
|Provisioner |Volume mode |Access mode

|Kubernetes.io/aws-ebs
|Block
|ReadWriteOnce

|Kubernetes.io/azure-disk
|Block
|ReadWriteOnce

|Kubernetes.io/azure-file
|Filesystem
|ReadWriteMany

|Kubernetes.io/cinder
|Block
|ReadWriteOnce

|Kubernetes.io/gce-pd
|Block
|ReadWriteOnce

|Kubernetes.io/hostpath-provisioner
|Filesystem
|ReadWriteOnce

|manila.csi.openstack.org
|Filesystem
|ReadWriteMany

|openshift-storage.cephfs.csi.ceph.com
|Filesystem
|ReadWriteMany

|openshift-storage.rbd.csi.ceph.com
|Block
|ReadWriteOnce

|Kubernetes.io/rbd
|Block
|ReadWriteOnce

|Kubernetes.io/vsphere-volume
|Block
|ReadWriteOnce
|===

[NOTE]
====
If the {virt} storage does not support link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html/storage/dynamic-provisioning[dynamic provisioning], you must apply the following settings:

* `Filesystem` volume mode
+
`Filesystem` volume mode is slower than `Block` volume mode.
* `ReadWriteOnce` access mode
+
`ReadWriteOnce` access mode does not support live virtual machine migration.

See link:https://docs.redhat.com/en/documentation/openshift_container_platform/{ocp-version}/html-single/virtualization/index#virt-customizing-storage-profile_virt-configuring-storage-profile[Enabling a statically-provisioned storage class] for details on editing the storage profile.
====

[NOTE]
====
If your migration uses block storage and persistent volumes created with an EXT4 file system, increase the file system resource usage in the Containerized Data Importer (CDI) to be more than 10%. The default resource usage that is assumed by CDI does not completely include the reserved place for the root partition. If you do not increase the file system resource usage in CDI by this amount, your migration might fail.
====

[NOTE]
====
When you migrate from {osp}, or when you run a cold migration from {rhv-full} to the {ocp} cluster that {project-short} is deployed on, the migration allocates persistent volumes without CDI. In these cases, you might need to adjust the file system resource usage.

If the configured file system resource usage, which has a default value of 10%, is too low, the disk transfer will fail due to lack of space. In such a case, you would want to increase the file system resource usage.

In some cases, however, you might want to decrease the file system resource usage to reduce storage consumption.

You can change the file system resource usage by changing the value of the `controller_filesystem_resource usage` in the `spec` portion of the `forklift-controller` CR, as described in xref:configuring-mtv-operator_{context}[Configuring the MTV Operator].
====



