// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="technical-changes-2-8_{context}"]
= Technical changes

{project-first} 2.8 has the following technical changes:

.Shortened plan durations with scheduler optimizations in warm migrations
When you start multiple warm or remote migration plans concurrently, the scheduler is optimized to schedule pending migration plans after completing smaller disk transfers in the current plan. This scheduler optimization enables faster warm migration. link:https://issues.redhat.com/browse/MTV-1574[(MTV-1574)] 

.MTV supports optimized migration of VMware VMs with shared disks 
{project-short} detects a shared disk used by multiple VMware virtual machines (VMs) in the migration plan and provides an option to migrate the shared disk one time. You can add the shared disk along with a VM by using the `migrateSharedDisks` plan attribute. When you migrate the other VMs that use the same shared disk, you can configure the `migrateSharedDisks` plan attribute as `false` in a new migration plan.

Migration of shared disks is supported for VMs created using the following operating systems:

* Windows
* Linux (block devices only)

link:https://issues.redhat.com/browse/MTV-1963[(MTV-1963)]