// Module included in the following assemblies:
//
// * documentation/doc-Release_notes/master.adoc

[id="technical-changes-2-8_{context}"]
= Technical changes

{project-first} 2.8 has the following technical changes:

.Shortened plan durations with scheduler optimizations in warm migrations
When you start multiple warm or remote migration plans concurrently, the scheduler is optimized to schedule pending migration plans after completing smaller disk transfers in the current plan. The scheduler optimization enables faster warm migration. link:https://issues.redhat.com/browse/MTV-1574[(MTV-1574)] 

.MTV supports optimised migration of VMware virtual machines with shared disks 
{project-short} detects shared volumes used by multiple VMware virtual machines (VMs) in the migration plan and provides an option to migrate the shared volume once. Migration of shared disks is supported for virtual machines created using the following operating systems:
* Windows
* Linux block devices only
link:https://issues.redhat.com/browse/MTV-1963[(MTV-1963)]