// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_upgrading-uninstalling-mtv.adoc

:_content-type: PROCEDURE
[id="uninstalling-mtv-cli_{context}"]
= Uninstalling {project-short} from the command line

[role="_abstract"]
You can uninstall {project-first} from the command line.

[NOTE]
====
This action does not remove resources managed by the {project-short} Operator, including custom resource definitions (CRDs) and custom resources (CRs). To remove these after uninstalling the {project-short} Operator, you might need to manually delete the {project-short} Operator CRDs.
====

.Prerequisites

* You must be logged in as a user with `cluster-admin` privileges.

.Procedure

. Delete the `forklift` controller by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc delete ForkliftController --all -n openshift-mtv
----

. Delete the subscription to the {project-short} Operator by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc get subscription -o name|grep 'mtv-operator'| xargs oc delete
----

. Delete the `clusterserviceversion` for the {project-short} Operator by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc get clusterserviceversion -o name|grep 'mtv-operator'| xargs oc delete
----

. Delete the plugin console CR by running the following command:
+
[source,terminal,subs="attributes+"]
----
$ oc delete ConsolePlugin forklift-console-plugin
----

. Optional: Delete the custom resource definitions (CRDs) by running the following command:
+
[source,terminal,subs="attributes+"]
----
{oc} get crd -o name | grep 'forklift.konveyor.io' | xargs {oc} delete
----

. Optional: Perform cleanup by deleting the {project-short} project by running the following command:
+
[source,terminal,subs="attributes+"]
----
oc delete project openshift-mtv
----
