// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_upgrading-uninstalling-mtv.adoc
:_mod-docs-content-type: PROCEDURE
[id="upgrading-mtv-ui_{context}"]
= Upgrading the {project-full}

[role="_abstract"]
You can upgrade the {operator-name} by using the {ocp} web console to install the new version.

.Procedure

. In the {ocp} web console, click *Operators* -> *Installed Operators* -> *{operator-name-ui}* -> *Subscription*.

. Change the update channel to the correct release.
+
ifeval::["{build}" == "upstream"]
See link:https://docs.okd.io/latest/operators/admin/olm-upgrading-operators.html#olm-changing-update-channel_olm-upgrading-operators[Changing update channel] in the {ocp} documentation.
endif::[]
ifeval::["{build}" == "downstream"]
See {ocp-doc}/operators/administrator-tasks#olm-changing-update-channel_olm-upgrading-operators[Changing the update channel for an Operator] in the {ocp} documentation.
endif::[]

. Confirm that *Upgrade status* changes from *Up to date* to *Upgrade available*. If it does not, restart the `CatalogSource` pod:

..  Note the catalog source, for example, `redhat-operators`.
..  From the command line, retrieve the catalog source pod:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get pod -n openshift-marketplace | grep <catalog_source>
----

..  Delete the pod:
+
[source,terminal,subs=attributes+]
----
$ {oc} delete pod -n openshift-marketplace <catalog_source_pod>
----
+
*Upgrade status* changes from *Up to date* to *Upgrade available*.
+
If you set *Update approval* on the *Subscriptions* tab to *Automatic*, the upgrade starts automatically.
+
. If you set *Update approval* on the *Subscriptions* tab to *Manual*, approve the upgrade.
+
ifeval::["{build}" == "upstream"]
See link:https://docs.okd.io/latest/operators/admin/olm-upgrading-operators.html#olm-approving-pending-upgrade_olm-upgrading-operators[Manually approving a pending upgrade] in the {ocp} documentation.
endif::[]
ifeval::["{build}" == "downstream"]
See {ocp-doc}/operators/administrator-tasks#olm-approving-pending-upgrade_olm-upgrading-operators[Manually approving a pending Operator upgrade] in the {ocp} documentation.
endif::[]

. If you are upgrading from {project-short} 2.2 and have defined VMware source providers, edit the VMware provider by adding a VDDK `init` image. Otherwise, the update will change the state of any VMware providers to `Critical`. For more information, see link:https://access.redhat.com/documentation/en-us/migration_toolkit_for_virtualization/2.4/html/installing_and_using_the_migration_toolkit_for_virtualization/migrating-vms-web-console#adding-source-provider_vmware[Adding a VMware source provider].

. If you mapped to NFS on the {ocp} destination provider in {project-short} 2.2, edit the `AccessModes` and `VolumeMode` parameters in the NFS storage profile. Otherwise, the upgrade will invalidate the NFS mapping. For more information, see {ocp-doc}/virtualization/index#virt-configuring-storage-profile[Customizing storage profiles].
