// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: PROCEDURE
[id="upgrading-mtv-ui_{context}"]
= Upgrading {the-lc} {project-full}

You can upgrade the {operator-name} by using the {ocp} web console to install the new version.

[NOTE]
====
You must upgrade to the next release without skipping a release, for example, from 2.0 to 2.1 or from 2.1 to 2.2.
====

.Procedure

. Change the update channel to *release-v2.2.0*.
+
ifeval::["{build}" == "upstream"]
See link:https://docs.okd.io/latest/operators/admin/olm-upgrading-operators.html#olm-changing-update-channel_olm-upgrading-operators[Changing update channel] in the {ocp} documentation.
endif::[]
ifeval::["{build}" == "downstream"]
See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html-single/operators/index#olm-changing-update-channel_olm-upgrading-operators[Changing update channel] in the {ocp} documentation.
endif::[]

. Restart the `CatalogSource` pod:

.. In the the {ocp-short} web console, click *Operators* -> *Installed Operators*. Click *Forklift Operator* to view the *Operator details* page.

..  On the *Subscriptions* tab, note the catalog source, for example, `redhat-operators`.
..  From the command line, retrieve the catalog source pod:
+
[source,terminal,subs=attributes+]
----
$ {oc} get pod -n openshift-marketplace | grep <catalog_source> <1>
----
<1> Specify the catalog source, for example, `redhat-operators`.
+
..  Delete the pod:
+
[source,terminal,subs=attributes+]
----
$ {oc} delete pod -n openshift-marketplace <catalog_source_pod>
----
+
On the *Subscriptions* tab of the *Operator details* page in the {ocp-short} web console, *Upgrade status* changes from *Up to date* to *Upgrade available*.
+
If you set *Update approval* on the *Subscriptions* tab to *Automatic*, the upgrade starts automatically.
+
. If you set *Update approval* on the *Subscriptions* tab to *Manual*, approve the upgrade.
+
ifeval::["{build}" == "upstream"]
See link:https://docs.okd.io/latest/operators/admin/olm-upgrading-operators.html#olm-approving-pending-upgrade_olm-upgrading-operators[Manually approving a pending upgrade] in the {ocp} documentation.
endif::[]
ifeval::["{build}" == "downstream"]
See link:https://access.redhat.com/documentation/en-us/openshift_container_platform/{ocp-version}/html-single/operators/index#olm-approving-pending-upgrade_olm-upgrading-operators[Manually approving a pending upgrade] in the {ocp} documentation.
endif::[]

. Verify that the `forklift-ui` pod is in a `Ready` state before you log in to the web console:
+
[source,terminal,subs="attributes+"]
----
$ {oc} get pods -n {namespace}
----
+
.Example output
----
NAME                                  READY  STATUS   RESTARTS  AGE
forklift-controller-788bdb4c69-mw268  2/2    Running  0         2m
forklift-operator-6bf45b8d8-qps9v     1/1    Running  0         5m
forklift-ui-7cdf96d8f6-xnw5n          1/1    Running  0         2m
----
