// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="using-must-gather_{context}"]
= Using the must-gather tool

You can collect logs and information about {project-short} custom resources (CRs) by using the `must-gather` tool. You must attach a `must-gather` data file to all customer cases.

You can gather data for a specific namespace, migration plan, or virtual machine (VM) by using the filtering options.

[NOTE]
====
If you specify a non-existent resource in the filtered `must-gather` command, no archive file is created.
====

You can collect metrics data for a 24-hour period and view the data with the Prometheus console.

.Prerequisites

* You must be logged in to the {virt} cluster as a user with the `cluster-admin` role.
* You must have the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[{ocp} CLI (`oc`)] installed.

.Collecting logs and CR information

. Navigate to the directory where you want to store the `must-gather` data.
. Run the `oc adm must-gather` command:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather}
----
+
The data is saved as `/must-gather/must-gather.tar.gz`. You can upload this file to a support case on the link:https://access.redhat.com/[Red Hat Customer Portal].

. Optional: Run the `oc adm must-gather` command with the following options to gather filtered data:

* Namespace:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} \
  -- NS=<namespace> /usr/bin/targeted
----

* Migration plan:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} \
  -- PLAN=<migration_plan> /usr/bin/targeted
----

* Virtual machine:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} \
  -- VM=<vm_id> NS=<namespace> /usr/bin/targeted <1>
----
<1> Specify the VM _ID_ as it appears in the `Plan` CR.

.Collecting and viewing metrics data

. Navigate to the directory where you want to store the `must-gather` data.
. Run the `oc adm must-gather` command with the `gather_metrics_dump` script to gather data for the past 24 hours:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} \
  -- /usr/bin/gather_metrics_dump
----
+
This operation can take a long time. The data is saved as `/must-gather/metrics/prom_data.tar.gz`.

. To view the data with the Prometheus console, create a local Prometheus instance:
+
[source,terminal]
----
$ make prometheus-run
----
+
The command outputs the Prometheus URL:
+
.Output
[source,terminal]
----
Started Prometheus on http://localhost:9090
----

. Launch a web browser and navigate to the Prometheus URL to view the data.
. After you have viewed the data, delete the Prometheus instance and data:
+
[source,terminal]
----
$ make prometheus-cleanup
----
