// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="using-must-gather_{context}"]
= Using the must-gather tool

You can collect logs, metrics, and information about {project-short} custom resources by using the `must-gather` tool.

The `must-gather` data must be attached to all customer cases.

[NOTE]
====
If you specify a non-existent resource in the filtered `must-gather` command, no archive file is created.
====

.Prerequisites

* You must be logged in to the {virt} cluster as a user with the `cluster-admin` role.
* You must have the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[{ocp} CLI (`oc`)] installed.

.Procedure

. Navigate to the directory where you want to store the `must-gather` data.
. Run the `oc adm must-gather` command:

* To gather data for the past hour:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather}
----
+
The data is saved as `/must-gather/must-gather.tar.gz`. You can upload this file to a support case on the link:https://access.redhat.com/[Red Hat Customer Portal].

* To gather data for the past 24 hours:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} -- /usr/bin/gather_metrics_dump
----
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} \
  -- VM=<vm_id> NS=<namespace> /usr/bin/targeted <1>
----
<1> Specify the VM _ID_ as it appears in the `Plan` CR.
