// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="using-must-gather_{context}"]
= Using the must-gather tool

You can collect logs, metrics, and information about {project-short} custom resources by using the `must-gather` tool.

The `must-gather` data must be attached to all customer cases.

You can collect data for a one-hour or a 24-hour period and view the data with the Prometheus console.

.Prerequisites

* You must be logged in to the {virt} cluster as a user with the `cluster-admin` role.
* You must have the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[{ocp} CLI (`oc`)] installed.

.Procedure

. Navigate to the directory where you want to store the `must-gather` data.
. Run the `oc adm must-gather` command:
+
[source,terminal,subs="attributes+"]
----
$ oc adm must-gather --image={must-gather} \ <1>
  -- /usr/bin/gather_metrics_dump <2>
----
<1> `oc adm must-gather` collects data for the past hour and saves the data as `/must-gather/must-gather.tar.gz`.
<2> `oc adm must-gather` with the `/usr/bin/gather_metrics_dump` script collects data for the past 24 hours.
+
[NOTE]
====
The 24-hour data collection can take a long time.
====

. Upload the `must-gather.tar.gz` file to your support case on the link:https://access.redhat.com/[Red Hat Customer Portal].

.To view data with the Prometheus console

. Create a local Prometheus instance:
+
[source,terminal]
----
$ make prometheus-run
----
+
The command outputs the Prometheus URL.
+
.Output
[source,terminal]
----
Started Prometheus on http://localhost:9090
----

. Launch a web browser and navigate to the Prometheus URL to view the data.
. After you have viewed the data, delete the Prometheus instance and data:
+
[source,terminal]
----
$ make prometheus-cleanup
----
