// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="vddk-validator-containers_{context}"]
= VDDK validator containers need requests and limits

If you have the cluster or project resource quotas set, you must ensure that you have a sufficient quota for the {project-short} pods to perform the migration. 

// For more information, see {ocp-doc}/building_applications/index#quotas-creating-a-quota_quotas-setting-per-project

You can see the defaults, which you can override in the ForkliftController custom resource (CR), listed as follows. If necessary, you can adjust these defaults. 

These settings are highly dependent on your environment. If there are many migrations happening at once and the quotas are not set enough for the migrations, then the migrations can fail. This can also be correlated to the `MAX_VM_INFLIGHT` setting that determines how many VMs/disks are migrated at once.

.Defaults which can be overriden in the ForkliftController CR:

* This affects both cold and warm migrations:
+
For cold migration, it is likely to be more resource intensive as it performs the disk copy. For warm migration, you could potentially reduce the requests.

** virt_v2v_container_limits_cpu: `4000m`
** virt_v2v_container_limits_memory: `8Gi`
** virt_v2v_container_requests_cpu: `1000m`
** virt_v2v_container_requests_memory: `1Gi`
+

[NOTE]
====
Cold and warm migration using `virt-v2v` can be resource-intensive. For more details, see link:https://libguestfs.org/virt-v2v.1.html#compute-power-and-ram[Compute power and RAM].
====


* This affects any migrations with hooks:
** hooks_container_limits_cpu: `1000m`
** hooks_container_limits_memory: `1Gi`
** hooks_container_requests_cpu: `100m`
** hooks_container_requests_memory: `150Mi`

* This affects any OVA migrations:

** ova_container_limits_cpu: `1000m`
** ova_container_limits_memory: `1Gi`
** ova_container_requests_cpu: `100m`
** ova_container_requests_memory: `150Mi`
