// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: REFERENCE
[id="vddk-validator-containers_{context}"]
= Requests and limits for VDDK validator containers 

When you set cluster or project resource quotas, be sure that you have a sufficient quota for the {project-short} pods to perform the migration. 

For more information on creating, setting, and viewing quotas, see {ocp-doc}/building_applications/index#quotas[Quotas].

[id="defaults-that-can-be-overridden-in-forklift-controller_{context}"]
== Defaults that can be overridden in the ForkliftController CR:

The defaults that are related to VDDK validator containers are listed as follows. You can override these defaults in the `ForkliftController` custom resource (CR).

[NOTE]
====
These settings are highly dependent on your environment. If there are many migrations happening at once and the quotas are not set high enough for the migrations, then the migrations can fail. 

Migration success or failure is also connected to the `MAX_VM_INFLIGHT` setting that determines how many VMs or disks are migrated at once.
====

* These defaults affect both cold and warm migrations:
+
Cold migration is likely to be more resource intensive because it copies the disks. For warm migration, you could potentially reduce the requests.

** virt_v2v_container_limits_cpu: `4000m`
** virt_v2v_container_limits_memory: `8Gi`
** virt_v2v_container_requests_cpu: `1000m`
** virt_v2v_container_requests_memory: `1Gi`
+
[NOTE]
====
Cold and warm migration using `virt-v2v` can be resource-intensive. For more details, see link:https://libguestfs.org/virt-v2v.1.html#compute-power-and-ram[Compute power and RAM].
====

* These defaults affect all migrations with hooks:

** hooks_container_limits_cpu: `1000m`
** hooks_container_limits_memory: `1Gi`
** hooks_container_requests_cpu: `100m`
** hooks_container_requests_memory: `150Mi`

* These defaults affect all Open Virtual Appliance (OVA) file migrations:

** ova_container_limits_cpu: `1000m`
** ova_container_limits_memory: `1Gi`
** ova_container_requests_cpu: `100m`
** ova_container_requests_memory: `150Mi`
