// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: CONCEPT
[id="virt-migration-workflows_{context}"]
= Detailed migration workflow

You can use the detailed migration workflow to troubleshoot a failed migration.

// ifeval::["{build}" == "downstream"]
// .Detailed {virt} migration workflow
// image::136_OpenShift_Migration_Toolkit_0121_virt-workflow.svg[{virt} workflow]
// endif::[]
// ifeval::["{build}" == "upstream"]
// .Detailed {virt} migration workflow
// image::136_Upstream_Migration_Toolkit_0121_virt-workflow.svg[{virt} workflow]
// endif::[]

The workflow describes the following steps:

. When you create a `Migration` custom resource (CR) to run a migration plan, the `Migration Controller` service  creates a `VirtualMachine` CR for each source virtual machine (VM) and a `DataVolume` CR for each source VM disk.
+
*For each VM disk:*

. The `Containerized Data Importer (CDI) Controller` service creates a persistent volume claim (PVC) based on the parameters specified in the `DataVolume` CR.  
. The persistent volume (PV) is dynamically provisioned by the `StorageClass` provisioner.  
. The `CDI Controller` service creates an `importer` pod.
. The `importer` pod streams the VM disk to the PV.
+
*After the VM disks are transferred:*

. The `Migration Controller` service creates a `conversion` pod with the PVCs attached to it.
+
The `conversion` pod runs `virt-v2v`, which installs and configures device drivers on the PVCs of the target VM.

. When the target VM is powered on, the `KubeVirt Controller` service creates a `virt-launcher` pod and a `VirtualMachineInstance` CR.
+
The `virt-launcher` pod runs `QEMU-KVM` with the PVCs attached as VM disks.
