// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_understanding-mtv-migration.adoc

:_mod-docs-content-type: CONCEPT
[id="virt-v2v-mtv-main-functions_{context}"]
= Main functions of virt-v2v in MTV migrations

[role="_abstract"]
During migration, {project-short} uses `virt-v2v` to collect metadata about VMs, make necessary changes to VM disks, and copy the disks containing the VMs to {virt}.

`virt-v2v` makes the following changes to VM disks to prepare them for migration:

* Additions:

** Injection of VirtIO drivers, for example, network or disk drivers.
** Preparation of hypervisor-specific tools or agents, for example, a QEMU guest agent installation.
** Modification of boot configuration, for example, updated boot loader or boot entries.

* Removals:

** Unnecessary or former hypervisor-specific files, for example, VMware tools or VirtualBox additions.
** Old network driver configurations, for example, removing VMware-specific NIC drivers.
** Configuration settings that are incompatible with the target system, for example, old boot settings.

If you are migrating from {vmw} or from Open Virtual Appliances (OVA) files, `virt-v2v` also sets their IP addresses either during the migration or during the first reboot of the VMs after migration.
[NOTE]
====
You can also run predefined Ansible hooks before or after a migration using {project-short}. For more information, see xref:about-hooks-for-migration-plans_mtv[About hooks for MTV migration plans].

These hooks do not necessarily use `virt-v2v`.
====
