// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

:_content-type: context
[id="virt-migration-workflow_{context}"]
= Detailed migration workflow

You can use the detailed migration workflow to troubleshoot a failed migration.

// ifeval::["{build}" == "downstream"]
// .Detailed {virt} migration workflow
// image::136_OpenShift_Migration_Toolkit_0121_virt-workflow.svg[{virt} workflow]
// endif::[]
// ifeval::["{build}" == "upstream"]
// .Detailed {virt} migration workflow
// image::136_Upstream_Migration_Toolkit_0121_virt-workflow.svg[{virt} workflow]
// endif::[]

The workflow describes the following steps:

*Warm Migration or migration to a remote {ocp-name} cluster:*

. When you create the `Migration` custom resource (CR) to run a migration plan, the `Migration Controller` service creates a `DataVolume` CR for each source VM disk.
+
*For each VM disk:*

. The `Containerized Data Importer (CDI) Controller` service creates a persistent volume claim (PVC) based on the parameters specified in the `DataVolume` CR.  
. If the `StorageClass` has a dynamic provisioner, the persistent volume (PV) is dynamically provisioned by the `StorageClass` provisioner.
. The `CDI Controller` service creates an `importer` pod.
. The `importer` pod streams the VM disk to the PV.
+
*After the VM disks are transferred:*

. The `Migration Controller` service creates a `conversion` pod with the PVCs attached to it when importing from VMWare.
+
The `conversion` pod runs `virt-v2v`, which installs and configures device drivers on the PVCs of the target VM.
+
. The `Migration Controller` service creates a `VirtualMachine` CR for each source virtual machine (VM), connected to the PVCs.

. If the VM ran on the source environment, the `Migration Controller` powers on the VM, the `KubeVirt Controller` service creates a `virt-launcher` pod and a `VirtualMachineInstance` CR.
+
The `virt-launcher` pod runs `QEMU-KVM` with the PVCs attached as VM disks.

*Cold migration from {rhv-short} or {osp} to the local {ocp-name} cluster:*

. When you create a `Migration` custom resource (CR) to run a migration plan, the `Migration Controller` service creates for each source VM disk a `PersistentVolumeClaim` CR, and an `OvirtVolumePopulator` when the source is {rhv-short}, or an `OpenstackVolumePopulator` CR  when the source is {osp}.
+
*For each VM disk:*

. The `Populator Controller` service creates a temporarily persistent volume claim (PVC).
. If the `StorageClass` has a dynamic provisioner, the persistent volume (PV) is dynamically provisioned by the `StorageClass` provisioner.
- The `Migration Controller` service creates a dummy pod to bind *all PVCs*. The name of the pod contains `pvcinit`.
. The `Populator Controller` service creates a `populator` pod.
. The `populator` pod transfers the disk data to the PV.
+
*After the VM disks are transferred:*
. The temporary PVC is deleted, and the initial PVC points to the PV with the data.
. The `Migration Controller` service creates a `VirtualMachine` CR for each source virtual machine (VM), connected to the PVCs.
. If the VM ran on the source environment, the `Migration Controller` powers on the VM, the `KubeVirt Controller` service creates a `virt-launcher` pod and a `VirtualMachineInstance` CR.
+
The `virt-launcher` pod runs `QEMU-KVM` with the PVCs attached as VM disks.

*Cold migration from VMWare to the local {ocp-name} cluster:*

. When you create a `Migration` custom resource (CR) to run a migration plan, the `Migration Controller` service creates a `DataVolume` CR for each source VM disk.
+
*For each VM disk:*

. The `Containerized Data Importer (CDI) Controller` service creates a blank persistent volume claim (PVC) based on the parameters specified in the `DataVolume` CR.  
. If the `StorageClass` has a dynamic provisioner, the persistent volume (PV) is dynamically provisioned by the `StorageClass` provisioner.

*For all VM disks:*

. The `Migration Controller` service creates a dummy pod to bind *all PVCs*. The name of the pod contains `pvcinit`.
. The `Migration Controller` service creates a `conversion` pod for all PVCs.
. The `conversion` pod runs `virt-v2v`, which converts the VM to the KVM hypervisor and transfers the disks' data to their corresponding PVs.
+
*After the VM disks are transferred:*
. The `Migration Controller` service creates a `VirtualMachine` CR for each source virtual machine (VM), connected to the PVCs.
. If the VM ran on the source environment, the `Migration Controller` powers on the VM, the `KubeVirt Controller` service creates a `virt-launcher` pod and a `VirtualMachineInstance` CR.
+
The `virt-launcher` pod runs `QEMU-KVM` with the PVCs attached as VM disks.
