// Module included in the following assemblies:
//
// * documentation/doc-Migrating_your_virtual_machines/assemblies/assembly_understanding-mtv-migration.adoc

:_mod-docs-content-type: CONCEPT

[id="virt-v2v-mtv-customizing-removing-installing-_{context}"]
= Customizing, removing, and installing files

[role="_abstract"]
{project-short} uses `virt-v2v` to perform additional guest customizations during the conversion, such as the following actions:

* Customization to preserve IP addresses
* Customization to preserve drive letters

[NOTE]
====
For {rhel-first}-based guests, `virt-v2v` attempts to install the guest agent from the Red Hat registry. If the migration is run in a detached environment, the installation program fails, and you must use hooks or other automation to install the guest agent.
====

For more information, see the man reference pages:

* link:https://libguestfs.org/virt-v2v.1.html[`virt-v2v` - Convert a guest to use KVM]
* link:https://libguestfs.org/virt-customize.1.html[`virt-customize` - Customize a virtual machine]

