// Module included in the following assemblies:
//
// * documentation/doc-Planning_your_migration/assemblies/assembly_prerequisites-for-migration.adoc

:_mod-docs-content-type: REFERENCE
[id="vmware-prerequisites_{context}"]
= {vmw} prerequisites

[role="_abstract"]
It is strongly recommended to create a VDDK image to accelerate migrations. For more information, see xref:creating-vddk-image_mtv[Creating a VDDK image].

[WARNING]
====
Virtual machine (VM) migrations do not work without VDDK when a VM is backed by {vmw} vSAN.
====

[WARNING]
====
{project-first} cannot migrate {vmw} vSphere 6 and {vmw} vSphere 7 VMs to a FIPS-compliant {virt} cluster.
====

The following prerequisites apply to {vmw} migrations:

* You must use a xref:compatibility-guidelines_{context}[compatible version] of {vmw} vSphere.
* You must be logged in as a user with at least the minimal set of xref:vmware-privileges_{context}[VMware privileges].
* To access the virtual machine using a pre-migration hook, link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Tools] must be installed on the source virtual machine.
* The VM operating system must be certified and supported for use as a link:https://access.redhat.com/articles/973163#ocpvirt[guest operating system with {virt}] _and_ for link:https://access.redhat.com/articles/1351473[conversion to KVM with `virt-v2v`].
* If you are running a warm migration, you must enable link:https://kb.vmware.com/s/article/1020128[changed block tracking (CBT)] on the VMs and on the VM disks.
* If you are migrating more than 10 VMs from an ESXi host in the same migration plan, you must increase the Network File Copy (NFC) service memory of the host.
* It is strongly recommended to disable hibernation because {project-first} does not support migrating hibernated VMs.
* The target namespace must have network connectivity to the {vmw} source environment. NetworkPolicies that block egress connections from the target namespace prevent migration from succeeding.
* A default `MigController` instance must be present. This instance is required for the Storage Migration option in the {ocp} web console in certain {ocp-name} versions. For steps to create the default `MigController` instance, see link:https://access.redhat.com/solutions/7136894[Storage Migration Option Missing for Virtual Machines in OpenShift 4.20 Despite Availability in 4.18].

[WARNING]
====
For virtual machines (VMs) running Microsoft Windows, Volume Shadow Copy Service (VSS) inside the guest VM is used to quiesce the file system and applications. When performing a warm migration of a Microsoft Windows virtual machine from {vmw}, you must start VSS on the Windows guest operating system in order for the snapshot and `Quiesce guest file system` to succeed.

If you do not start VSS on the Windows guest operating system, the snapshot creation during the warm migration fails with the following error: `An error occurred while taking a snapshot: Failed to restart the virtual machine.`

If you set the VSS service to `Manual` and start a snapshot creation with `Quiesce guest file system = yes`. In the background, the {vmw} Snapshot provider service requests VSS to start the shadow copy.
====

[IMPORTANT]
====
In case of a power outage, data might be lost for a VM with disabled hibernation. However, if hibernation is not disabled, migration will fail.
====

[id="vmware-privileges_{context}"]
