// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="adding-source-provider_{context}"]
= Adding a source provider

You can add a VMware source provider by using the {project-short} web console.

.Prerequisites

* You have a VMware vCenter user account with administrator privileges

.Procedure

. In the {project-short} web console, click *Providers*.
. Click *Add provider*.
. Select *VMware* from the *Type* list.
. Fill in the following fields:

* *Name*: vCenter name to display in the list of providers
* *Hostname or IP address*: vCenter host name or IP address
* *Username*: vCenter admin user name, for example, `administrator@vsphere.local`
* *Password*: vCenter password
* *Certificate SHA1 Fingerprint*: vCenter server SSL SHA 1 fingerprint
+
To obtain the vCenter server SSL fingerprint, enter the following command:
+
[source,terminal]
----
$ openssl s_client \
    -connect <vcenter.example.com>:443 < /dev/null 2>/dev/null \ <1>
    | openssl x509 -fingerprint -noout -in /dev/stdin \
    | cut -d '=' -f 2
----
<1> Specify the vCenter server host name.

. Click *Add* to add and save the provider.
+
The VMware provider appears in the list of providers.
