// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="creating-storage-mapping_{context}"]
= Creating a storage mapping

You can create a storage mapping to map source data stores to {virt} storage classes.

{project-first} supports the following link:https://docs.openshift.com/container-platform/{ocp-version}/virt/virtual_machines/importing_vms/virt-importing-vmware-vm.html#virt-features-for-storage-matrix_virt-importing-vmware-vm[storage features].

[NOTE]
====
If the {virt} storage does not support link:https://docs.openshift.com/container-platform/{ocp-version}/storage/dynamic-provisioning.html[dynamic provisioning], the default settings, `Filesystem` volume mode and `ReadWriteOnce` access mode, are applied. `Filesystem` volume mode is slower than `Block` volume mode. `ReadWriteOnce` access mode does not allow live VM migration.
====

.Prerequisites

* You have added source and target providers to the web console.
* The local and shared persistent storage support VM migration.

.Procedure

. In the web console, navigate to *Mappings* -> *Storage*.
. Click *Create mapping*.
. Complete the following fields:

* *Name*: Enter a name to display in the storage mappings list.
* *Source provider*: Select a source provider.
* *Target provider*: Select a target provider.
* *Source datastores*: Select a source data store.
* *Target storage classes*: Select a target storage class.

. Optional: Click *Add* to create additional storage mappings or to map multiple data stores to a single storage class.
. Click *Create*.
+
The mapping is displayed on the *Storage mappings* screen.
