// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="creating-migration-plan_{context}"]
= Creating a migration plan

You can create a migration plan by using the {project-short} web console.

A migration plan allows you to group virtual machines that should be migrated together or with the same migration parameters, for example, a percentage of the members of a cluster or a complete application.

.Prerequisites

* VDDK image added to the `v2v-vmware` config map.
* Source and target providers added to the web console.

.Procedure

. In the web console, navigate to *Migration plans* and click *Create migration plan*.
. Complete the following fields:

* *Plan name*: Enter a migration plan name to display in the migration plan list.
* *Plan description*: Optional: Brief description of the migration plan.
* *Source provider*: Select a source provider.
* *Target provider*: Select a target provider.
* *Target namespace*: You can type to search for an existing target namespace or create a new namespace.
* You can change the migration transfer network for this plan by clicking *Select a different network*, selecting a network from the list, and clicking *Select*.
+
If you defined a migration transfer network for the {virt} provider and if the network is in the target namespace, that network is the default network for all migration plans. Otherwise, the `pod` network is used.

. Click *Next*.
. Click *By clusters and hosts* or *By folders*, select clusters, hosts, or folders to filter the VMs, and then click *Next*.
. Select the VMs to migrate and click *Next*.
. Select an existing network mapping or create a new network mapping.
. If you selected *Create a new network mapping*, select a target network for each source network.
. Optional: Select *Save mapping to use again* and enter a network mapping name.
. Click *Next*.
. Select an existing storage mapping or create a new storage mapping.
. If you selected *Create a new storage mapping*, select a target storage class for each source data store.
. Optional: Select *Save mapping to use again* and enter a storage mapping name.
. Click *Next*.
. Review your migration plan and click *Finish*.
+
The migration plan is saved in the migration plan list.
