// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/assemblies/assembly_migrating-vms-web-console.adoc
// * documentation/doc-Forklift/assemblies/assembly_migrating-vms-web-console.adoc

[id="creating-a-migration-plan_{context}"]
= Creating a migration plan

You can create a migration plan in the web console.

A migration plan allows you to group virtual machines that should be migrated together or with the same migration parameters, for example, a percentage of the members of a cluster or a complete application.

.Prerequisites

* The migration network supports migration.
* The web console has source and target providers.

.Procedure

. In the web console, navigate to *Migration plans* and click *Create migration plan*.
. Fill in the following fields in the *General settings* screen:
* *Plan name*: Plan name that is displayed in the web console.
* *Plan description*: Optional. Brief description of the migration plan.
* *Source provider*: Select a VMware provider.
* *Target provider*: Select the {virt} provider.

. Click *Next*.
. Filter the VMs that you want to migrate by selecting data centers, clusters, or folders.
. Select the VMs to migrate. You can click each VM to view its migration risk assessment.
. Select an existing storage mapping or create a new storage mapping.
. If you want to create a new storage mapping:
.. Select a data store from the *Source datastores* list and a storage class from the *Target storage classes* list.
.. Click *Add* to create additional storage mappings or to map multiple data stores to a single storage class.
. Click *Next*.
. Select an existing network mapping or create a new network mapping.
. If you want to create a new network mapping:
.. Select a network from the *Source networks* list and a network from the *Target networks* list.
.. Click *Add* to create additional network mappings or to map multiple source networks to a single target network.
. Click *Next*.
// . If you want to add a hook to the migration plan:
//
// .. Select an existing hook from the list or click *Add hook*.
// .. Select *Ansible playbook* or *Custom container image* as the hook definition.
// .. Select the migration step when you want the hook to run.
// .. Click *Add*.
//
// . Click *Next*.
. Review your migration plan and click *Finish*.
+
The migration plan is saved in the migration plan list.
