// Module included in the following assemblies:
//
// doc-mtv_2.0/master.adoc

[id="creating-mappings_{context}"]
ifdef::network[]
= Creating a network mapping

You can create a network mapping to map VMware networks to {virt} networks.

[NOTE]
====
You cannot map an opaque network to a {virt} network.
====
endif::[]
ifdef::storage[]
= Creating a storage mapping

You can create a storage mapping to map VMware data stores to {virt} storage classes.

.Prerequisites

* The local and shared persistent storage must support VM migration.
endif::[]


.Procedure

ifdef::network[]
. In the web console, navigate to *Mappings* -> *Network*.
endif::[]
ifdef::storage[]
. In the web console, navigate to *Mappings* -> *Storage*.
endif::[]
. Click *Create mapping*.
ifdef::network[]
. Select a *Source provider* and a *Target provider*.
. Select a network from the *Source networks* list and from the *Target networks* list.
. Click *Add* to create additional network mappings or to map multiple source networks to a single target network.
endif::[]
ifdef::storage[]
. Select a *Source provider* and a *Target provider*.
. Select a data store from the *Source datastores* list and a storage class from the *Target storage classes* list.
. Click *Add* to create additional storage mappings or to map multiple data stores to a single storage class.
endif::[]
. Click *Create*.
ifdef::network[]
+
The mapping is displayed in the *Network mappings* list.
endif::[]
ifdef::storage[]
+
The mapping is displayed in the *Storage mappings* list.
endif::[]
