// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-console_{context}"]
= Installing {the-lc} {project-full} by using the web console

You can install {the-lc} {project-first} by using the {ocp} web console.

.Prerequisites

* You have installed {ocp} {ocp-version} on your cluster.
* You have installed the {virt} Operator.
* You have logged in as a user with `cluster-admin` privileges.

.Procedure

. In the {ocp} web console, navigate to *Operators* -> *OperatorHub*.
. Use the *Filter by keyword* field to find the *{operator}*.
ifeval::["{build}" == "upstream"]
+
[NOTE]
====
The {operator} is a Community Operator. Red Hat does not support Community Operators.
====
endif::[]
. Click the {operator} and then click *Install*.
. On the *Install Operator* page, click *Install*.
. Click *Operators* -> *Installed Operators* to verify that the {operator} appears in the *{namespace}* project with the status *Succeeded*.
. Click the {operator}.
. Under *Provided APIs*, locate the *ForkliftController*, and click *Create Instance*.
. Click *Create*.
. Click *Workloads* -> *Pods* to verify that the {project-short} pods are running.
