// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-cli_{context}"]
= Installing {the-lc} {project-full} from the CLI

You can install {the-lc} {project-first} from the command line interface (CLI).

.Prerequisites

* VMware vSphere 6.5 or later.
* {ocp} {ocp-version} installed.
* {virt} Operator installed.
* You must be logged in as a user with `cluster-admin` permissions.
* If you are performing more than 10 concurrent migrations from a single ESXi host, you must increase the NFC service memory of the host.

* VMware virtual machines:
** link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Tools] installed.
** ISO/CDROM disks  unmounted.
** NIC with no more than one IPv4 and/or one IPv6 address.
** VM name containing only lowercase letters (`a-z`), numbers (`0-9`), or hyphens (`-`), up to a maximum of 253 characters. The first and last characters must be alphanumeric. The name must not contain uppercase letters, spaces, periods (`.`), or special characters.
** VM name that does not duplicate the name of a virtual machine in the {virt} environment.
** Operating system certified and supported link:https://access.redhat.com/articles/973163#ocpvirt[for use as a guest operating system with {virt}] _and_ link:https://access.redhat.com/articles/1351473[for conversion to KVM with `virt-v2v`].

* Network:
** IP addresses, VLANs, and other network configuration settings must not be changed before or after migration. The MAC addresses of the virtual machines are preserved during migration.
** Uninterrupted and reliable network connections between the clusters and the replication repository.
** Network ports enabled in the firewall rules.

[cols="1,1,1,1,2",options="header"]
.Network ports required for migration
|===
|Port |Protocol |Source |Destination |Purpose

|443
|TCP
|OpenShift nodes
|VMware vCenter
a|VMware provider inventory

Disk transfer authentication

|443
|TCP
|OpenShift nodes
|VMware ESXi hosts
|Disk transfer authentication

|902
|TCP
|OpenShift nodes
|VMware ESXi hosts
|Disk transfer data copy
|===

.Procedure

. Create the {namespace} project:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {namespace}
EOF
----

. Create an `OperatorGroup` CR called `migration`:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
  namespace: {namespace}
spec:
  targetNamespaces:
    - {namespace}
EOF
----

. Create a `Subscription` CR for the Operator:
ifeval::["{build}" == "upstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {operator}
  namespace: {namespace}
spec:
  channel: development
  installPlanApproval: Automatic
  name: {operator}
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "konveyor-forklift-operator.v2.0.0"
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {operator}
  namespace: {namespace}
spec:
  channel: release-v2.0.0
  installPlanApproval: Automatic
  name: {operator}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "mtv-operator.v2.0.0"
EOF
----
endif::[]

. Create a `ForkliftController` CR:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: forklift.konveyor.io/v1alpha1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: {namespace}
spec:
  olm_managed: true
EOF
----

. Verify that the {project-short} pods are running:
+
[source,terminal,subs="attributes+"]
----
$ oc get pods -n {namespace}
----
+
.Example output
----
NAME                                   READY   STATUS    RESTARTS   AGE
forklift-controller-788bdb4c69-mw268   2/2     Running   0          2m
forklift-operator-6bf45b8d8-qps9v      1/1     Running   0          5m
forklift-ui-7cdf96d8f6-xnw5n           1/1     Running   0          2m
----
