// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-console_{context}"]
= Installing {the-lc} {project-full} by using the {ocp} web console

You can install {the-lc} {project-first} by using the {ocp} web console.

.Prerequisites

* The source cluster must be VMware vSphere 6.5 or later.
* If you are performing more than 10 concurrent migrations from a single ESXi host, you must increase the NFC service memory of the host.
* You must install {ocp} {ocp-version} on the target cluster.
* You must install the {virt} Operator.
* You must log in as a user with `cluster-admin` permissions.

* VMware virtual machines:
** link:https://www.vmware.com/support/ws5/doc/new_guest_tools_ws.html[VMware Tools] must be installed.
** ISO/CDROM disks must be unmounted.
** A NIC must have no more than one IPv4 and/or one IPv6 address.
** The VM name can contain lowercase letters (`a-z`), numbers (`0-9`), and hyphens (`-`), up to a maximum of 253 characters. The first and last characters must be alphanumeric. The name must not contain uppercase letters, spaces, periods (`.`), or special characters.
** The VM name must not duplicate the name of a virtual machine in the {virt} environment.
** The operating system must be certified and supported link:https://access.redhat.com/articles/973163#ocpvirt[for use as a guest operating system with {virt}] _and_ link:https://access.redhat.com/articles/1351473[for conversion to KVM with `virt-v2v`].

* Network:
** IP addresses, VLANs, and other network configuration settings must not be changed before or after migration. The MAC addresses of the virtual machines are preserved during migration.
** The network connections between the clusters and the replication repository must be uninterrupted and reliable.
** The firewall rules must enable traffic over the network ports required for migration.

[cols="1,1,1,1,2",options="header"]
.Required network ports
|===
|Port |Protocol |Source |Destination |Purpose

|443
|TCP
|OpenShift nodes
|VMware vCenter
a|VMware provider inventory

Disk transfer authentication

|443
|TCP
|OpenShift nodes
|VMware ESXi hosts
|Disk transfer authentication

|902
|TCP
|OpenShift nodes
|VMware ESXi hosts
|Disk transfer data copy
|===

.Procedure

. In the {ocp} web console, navigate to *Operators* -> *OperatorHub*.
. Use the *Filter by keyword* field to find the *{operator}*.
ifeval::["{build}" == "upstream"]
+
[NOTE]
====
The {operator} is a Community Operator. Red Hat does not support Community Operators.
====
endif::[]
. Click the {operator} and then click *Install*.
. On the *Install Operator* page, click *Install*.
. Click *Operators* -> *Installed Operators* to verify that the {operator} appears in the *{namespace}* project with the status *Succeeded*.
. Click the {operator}.
. Under *Provided APIs*, locate the *ForkliftController*, and click *Create Instance*.
. Click *Create*.
. Click *Workloads* -> *Pods* to verify that the {project-short} pods are running.
