// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-console_{context}"]
= Installing {the-lc} {project-full} using the web console

You can install {the-lc} {project-first} using the {ocp} web console.

.Prerequisites

* Install {ocp} {ocp-version} on your cluster.
* Install the {virt} Operator.
* Log in as a user with `cluster-admin` privileges.

.Procedure

. Open a browser window and log in to the {ocp} web console.
. Click *Operators* -> *OperatorHub*.
ifeval::["build" == "upstream"]
. Use the *Filter by keyword* field to find the *Konveyor Operator for VMs*.
+
[NOTE]
====
The Konveyor Operator for VMs is a Community Operator. Red Hat does not support Community Operators.
====
endif::[]
ifeval::["build" == "downstream"]
. Use the *Filter by keyword* field to find the *{project-full} Operator*.
endif::[]
. Click the Operator and then click *Install*.
. On the *Install Operator* page, click *Install*.
+
On the *Installed Operators* page, the Operator appears in the *openshift-migration* project with the status *Succeeded*.

. Click the Operator.
. Under *Provided APIs*, locate the *VirtController* tile, and click *Create Instance*.
. Click *Create*.
. Click *Workloads* -> *Pods* to verify that the `ProviderInventory`, `Validation`, `UserInterface`, and `Controller` pods are running.
