// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="installing-mtv-cli_{context}"]
= Installing {the-lc} {project-full} using the CLI

You can install {the-lc} {project-first} using the command line interface (CLI).

.Prerequisites

* Install {ocp} {ocp-version} on your cluster.
* Install the {virt} Operator.
* Install the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI].
* Log in as a user with `cluster-admin` privileges.

.Procedure

ifeval::["{build}" == "upstream"]
. Create an `openshift-migration` project:
endif::[]
ifeval::["{build}" == "downstream"]
. Create an `openshift-rhmtv` project:
endif::[]
+
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-migration
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: openshift-rhmtv
EOF
----
endif::[]

. Create an `OperatorGroup` object called `migration`:
+
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
  namespace: openshift-rhmtv
spec:
  targetNamespaces:
    - openshift-rhmtv
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
  namespace: openshift-rhmtv
spec:
  targetNamespaces:
    - openshift-rhmtv
EOF
----
endif::[]

ifeval::["{build}" == "upstream"]
. Create a `Subscription` object for the `virt-operator`:
endif::[]
ifeval::["{build}" == "downstream"]
. Create a `Subscription` object for the `rhmtv-operator`:
endif::[]
+
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: virt-operator
  namespace: openshift-migration
spec:
  channel: development
  installPlanApproval: Automatic
  name: virt-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "konveyor-virt-operator.v2.0.0-beta.0"
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhmtv-operator
  namespace: openshift-rhmtv
spec:
  channel: release-v2.0.0-beta
  installPlanApproval: Automatic
  name: rhmtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: "mtv-operator.v2.0.0-beta.1"
EOF
----
endif::[]

. Create a `ForkliftController` object:
+
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: forklift.konveyor.io/v1alpha1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: openshift-migration
spec:
  olm_managed: true
EOF
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat << EOF | oc apply -f -
---
apiVersion: forklift.konveyor.io/v1alpha1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: openshift-rhmtv
spec:
  olm_managed: true
EOF
----
endif::[]

. View the pods created during the `ForkliftController` object reconciliation:
+
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ oc get pods -n openshift-migration
----
endif::[]
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ oc get pods -n openshift-rhmtv
----
endif::[]
+
.Example output
----
NAME                                   READY   STATUS    RESTARTS   AGE
forklift-controller-788bdb4c69-mw268   2/2     Running   0          2m
forklift-operator-6bf45b8d8-qps9v      1/1     Running   0          5m
forklift-ui-7cdf96d8f6-xnw5n           1/1     Running   0          2m
----
