// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="migrating-virtual-machines-cli_{context}"]
= Migrating virtual machines from the CLI

You can migrate virtual machines from the command line (CLI) by creating the following custom resources (CRs):

* `Secret` CR contains the VMware provider credentials.
* `Provider` CR specifies the VMware provider.
* `Plan` CR specifies the source and target clusters, network mappings, data store mappings, and VMs to migrate.
* `Migration` CR runs the `Plan` CR.
+
If a migration does not complete, you can create a new `Migration` CR, without changing the `Plan` CR, to migrate the remaining VMs.

.Prerequisites

* Install {ocp} {ocp-version} on your cluster.
* Install the {virt} Operator.
* Install the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI].
* Log in as a user with `cluster-admin` privileges.

.Procedure

. Get the SSL thumbprint of the vCenter host:
+
[source,terminal]
----
$ openssl s_client \
    -connect <vcenter.example.com>:443 \ <1>
    < /dev/null 2>/dev/null \
    | openssl x509 -fingerprint -noout -in /dev/stdin \
    | cut -d '=' -f 2
----
<1> Specify the vCenter host name.

. Create a `Secret` CR with the VMware credentials:
+
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: vmware-secret
  namespace: openshift-rhmtv
type: Opaque
stringData:
  user: administrator@vsphere.local
  password: <password> <1>
  thumbprint: <01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF:01:23:45:67> <2>
EOF
----
endif::[]
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: v1
kind: Secret
metadata:
  name: vmware-secret
  namespace: openshift-migration
type: Opaque
stringData:
  user: administrator@vsphere.local
  password: <password> <1>
  thumbprint: <01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF:01:23:45:67> <2>
EOF
----
endif::[]
<1> Specify the password.
<2> Specify the thumbprint.

. Create a `Provider` CR for VMware vSphere:
+
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: virt.konveyor.io/v1alpha1
kind: Provider
metadata:
  name: vmware-provider
  namespace: openshift-rhmtv
spec:
  type: vsphere
  url: https://<vcenter.example.com>/sdk <1>
  secret:
    name: vmware-secret <2>
    namespace: openshift-rhmtv
EOF
----
endif::[]
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: virt.konveyor.io/v1alpha1
kind: Provider
metadata:
  name: vmware-provider
  namespace: openshift-migration
spec:
  type: vsphere
  url: https://<vcenter.example.com>/sdk <1>
  secret:
    name: vmware-secret <2>
    namespace: openshift-migration
EOF
----
endif::[]
<1> Specify the vSphere API end point.
<2> Specify the `Secret`.

. Create a `Plan` CR for the migration:
+
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: virt.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: test-migration-plan
  namespace: openshift-rhmtv
spec:
  provider:
    source:
      name: vmware-provider
      namespace: openshift-rhmtv
    destination:
      name: host <1>
      namespace: openshift-rhmtv
  map:
    networks:
      - source:
          id: <network-31> <2>
        destination:
          type: pod
          name: pod
          namespace: openshift-rhmtv
      - source:
          id: <network-723>
        destination:
          type: pod
          name: pod
          namespace: openshift-rhmtv
    datastores:
      - source:
          id: <datastore-30> <3>
        destination:
          storageClass: standard
      - source:
          id: <datastore-35>
        destination:
          storageClass: standard
  vms:
    - id: <vm-1630> <4>
    - id: <vm-2841>
EOF
----
endif::[]
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: virt.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: test-migration-plan
  namespace: openshift-migration
spec:
  provider:
    source:
      name: vmware-provider
      namespace: openshift-migration
    destination:
      name: host <1>
      namespace: openshift-migration
  map:
    networks:
      - source:
          id: <network-31> <2>
        destination:
          type: pod
          name: pod
          namespace: openshift-migration
      - source:
          id: <network-723>
        destination:
          type: pod
          name: pod
          namespace: openshift-migration
    datastores:
      - source:
          id: <datastore-30> <3>
        destination:
          storageClass: standard
      - source:
          id: <datastore-35>
        destination:
          storageClass: standard
  vms:
    - id: <vm-1630> <4>
    - id: <vm-2841>
EOF
----
endif::[]
<1> The OpenShift provider where {project-short} is deployed is added automatically as `host`.
<2> Specify a source network by its Managed Object Reference.
<3> Specify a source data store by its Managed Object Reference.
<4> Specify the IDs of the VMs to migrate by their Managed Object Reference.

. Create a `Migration` CR to run the `Plan` CR:
+
ifeval::["{build}" == "downstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: virt.konveyor.io/v1alpha1
kind: Migration
metadata:
  name: migration-test-001
  namespace: openshift-rhmtv
spec:
  plan:
    name: test-migration-plan
    namespace: openshift-rhmtv
EOF
----
endif::[]
ifeval::["{build}" == "upstream"]
[source,terminal]
----
$ cat < EOF | oc apply -f -
---
apiVersion: virt.konveyor.io/v1alpha1
kind: Migration
metadata:
  name: migration-test-001
  namespace: openshift-migration
spec:
  plan:
    name: test-migration-plan
    namespace: openshift-migration
EOF
----
endif::[]

The `Migration` CR creates a `VirtualMachineImport` CR for each VM being migrated. You can monitor the progress of the migration by viewing the `VirtualMachineImport` pods in the target namespace.
