// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="migrating-virtual-machines-cli_{context}"]
= Migrating virtual machines from the CLI

You can migrate virtual machines from the command line (CLI) by creating the following custom resources (CRs):

* `Secret` CR: Contains the VMware provider credentials.
* `Provider` CR: Describes the VMware provider.
* `Plan` CR: Describes the source and target clusters, network mappings, data store mappings, and VMs to migrate.
* `Migration` CR: Runs the `Plan` CR.
+
If a migration does not complete, you can create a new `Migration` CR, without changing the `Plan` CR, to migrate the remaining VMs. You can associate multiple `Migration` CRs with a single `Plan` CR.

.Prerequisites

* You have installed {ocp} {ocp-version} on your cluster.
* You have installed the {virt} Operator.
* You have installed the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI].
* You have logged in as a user with `cluster-admin` privileges.

.Procedure

. Obtain the SSL thumbprint of the vCenter host:
+
[source,terminal]
----
$ openssl s_client \
    -connect <vcenter_host>:443 \ <1>
    < /dev/null 2>/dev/null \
    | openssl x509 -fingerprint -noout -in /dev/stdin \
    | cut -d '=' -f 2
----
<1> Specify the vCenter host name.

. Create a `Secret` CR for the VMware provider:
+
[source,terminal,subs="attributes"]
----
$ cat << EOF | oc apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: vmware-secret
  namespace: {namespace}
type: Opaque
stringData:
  user: administrator@vsphere.local
  password: <password> <1>
  thumbprint: <vmware_thumbprint> <2>
EOF
----
<1> Specify the password.
<2> Specify the thumbprint, for example, `01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF:01:23:45:67`.

. Create a `Provider` CR for the VMware provider:
+
[source,terminal,subs="attributes"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Provider
metadata:
  name: vmware-provider
  namespace: {namespace}
spec:
  type: vsphere
  url: <api_end_point> <1>
  secret:
    name: vmware-secret <2>
    namespace: {namespace}
EOF
----
<1> Specify the vSphere API end point, for example, `/https://vcenter.host.com/sdk`.
<2> Specify the VMware `Secret` CR.

. Create a `Plan` CR for the migration:
+
[source,terminal,subs="attributes"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: migration-plan
  namespace: {namespace}
spec:
  provider:
    source:
      name: vmware-provider
      namespace: {namespace}
    destination:
      name: host <1>
      namespace: {namespace}
  map:
    networks:
      - source:
          id: <network_ref> <2>
        destination:
          type: pod
          name: pod
          namespace: {namespace}
    datastores:
      - source:
          id: <datastore_ref> <3>
        destination:
          storageClass: standard
  vms:
    - id: <vm_ref> <4>
EOF
----
<1> The cluster on which {project-short} is deployed is added automatically as `host`.
<2> Specify the managed object reference of one or more VMware networks.
<3> Specify the managed object reference of the VMware data store.
<4> Specify the managed object reference of one or more VMware VMs.

. Create a `Migration` CR to run the `Plan` CR:
+
[source,terminal,subs="attributes"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Migration
metadata:
  name: migration-001
  namespace: {namespace}
spec:
  plan:
    name: test-migration-plan
    namespace: {namespace}
EOF
----
+
The `Migration` CR creates a `VirtualMachineImport` CR for each VM that is migrated.

. Monitor the progress of the migration by viewing the `VirtualMachineImport` pods:
+
[source,terminal,subs="attributes"]
----
$ oc get pods -n {namespace}
----
