// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="migrating-virtual-machines-cli_{context}"]
= Migrating virtual machines from the CLI

You can migrate virtual machines from the command line (CLI) by creating the following custom resources (CRs):

* `Secret` CR: Contains the VMware provider credentials.
* `Provider` CR: Describes the VMware provider.
* `Plan` CR: Describes the source and target clusters, network mappings, data store mappings, and VMs to migrate.
* `Migration` CR: Runs the `Plan` CR.
+
If a migration does not complete, you can create a new `Migration` CR, without changing the `Plan` CR, to migrate the remaining VMs. You can associate multiple `Migration` CRs with a single `Plan` CR.

.Prerequisites

* {virt} Operator installed.
* {operator-name} installed.
* link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI] installed.
* VDDK image added to the `v2v-vmware` config map.
* You must be logged in as a user with `cluster-admin` privileges.

.Procedure

. Obtain the SSL thumbprint of the vCenter host:
+
[source,terminal]
----
$ openssl s_client \
    -connect <vcenter_host>:443 \ <1>
    < /dev/null 2>/dev/null \
    | openssl x509 -fingerprint -noout -in /dev/stdin \
    | cut -d '=' -f 2
----
<1> Specify the vCenter host name.
+
.Example output
+
[source,terminal]
----
01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF:01:23:45:67
----

. Create a `Secret` CR for the VMware provider:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: vmware-secret
  namespace: {namespace}
type: Opaque
stringData:
  user: <user_name> <1>
  password: <password> <2>
  thumbprint: <vcenter_thumbprint> <3>
EOF
----
<1> Specify the vCenter administrator account, for example, `administrator@vsphere.local`.
<2> Specify the vCenter password.
<3> Specify the SSL thumbprint of the vCenter host.

. Create a `Provider` CR for the VMware provider:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Provider
metadata:
  name: vmware-provider
  namespace: {namespace}
spec:
  type: vsphere
  url: <api_end_point> <1>
  secret:
    name: <vmware_secret> <2>
    namespace: {namespace}
EOF
----
<1> Specify the vSphere API end point, for example, `https://vcenter.host.com/sdk`.
<2> Specify the name of the VMware `Secret` CR.

. Create a `Plan` CR for the migration:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: <plan_name> <1>
  namespace: {namespace}
spec:
  provider:
    source:
      name: vmware-provider
      namespace: {namespace}
    destination:
      name: destination-cluster
      namespace: {namespace}
  map:
    networks: <2>
      - source: <3>
          id: <source_network_mor> <4>
          name: <source_network_name>
        destination:
          type: pod
          name: pod
          namespace: {namespace}
    datastores: <5>
      - source: <6>
          id: <source_datastore_mor> <7>
          name: <source_datastore_name>
        destination:
          storageClass: standard
  vms: <8>
    - id: <source_vm_mor> <9>
    - name: <source_vm_name>
EOF
----
<1> Specify the name of the `Plan` CR.
<2> You can create multiple network mappings for source and destination networks.
<3> You can use either the `id` _or_ the `name` parameter to specify the source network.
<4> _Managed object reference_ of the source network.
<5> You can create multiple storage mappings for source data stores and destination storage classes.
<6> You can use either the `id` _or_ the `name` parameter to specify the source data store.
<7> _Managed object reference_ of the source data store.
<8>  You can use either the `id` _or_ the `name` parameter to specify the source VM.
<9> _Managed object reference_ of the source VM.

. Create a `Migration` CR to run the `Plan` CR:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Migration
metadata:
  name: <migration_name> <1>
  namespace: {namespace}
spec:
  plan:
    name: <plan_name> <2>
    namespace: {namespace}
EOF
----
<1> Specify the name of the `Migration` CR.
<2> Specify the name of the `Plan` CR that you are running.
+
The `Migration` CR creates a `VirtualMachineImport` CR for each VM that is migrated.

. Monitor the progress of the migration by viewing the `VirtualMachineImport` pods:
+
[source,terminal,subs="attributes+"]
----
$ oc get pods -n {namespace}
----
