// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="migrating-virtual-machines-cli_{context}"]
= Migrating virtual machines from the CLI

You can migrate virtual machines from the command line (CLI) by creating the following custom resources (CRs):

* `Secret` CR: Contains the VMware provider credentials.
* `Provider` CR: Describes the VMware provider.
* `Plan` CR: Describes the source and target clusters, network mappings, data store mappings, and VMs to migrate.
* `Migration` CR: Runs the `Plan` CR.
+
If a migration does not complete, you can create a new `Migration` CR, without changing the `Plan` CR, to migrate the remaining VMs. You can associate multiple `Migration` CRs with a single `Plan` CR.

.Prerequisites

* You must install {ocp} {ocp-version} on your cluster.
* You must install the {virt} Operator.
* You must install the link:https://docs.openshift.com/container-platform/{ocp-version}/cli_reference/openshift_cli/getting-started-cli.html[OpenShift CLI].
* You must create a VDDK image and add it to the `v2v-vmware` config map.
* You must log in as a user with `cluster-admin` privileges.

.Procedure

. Obtain the SSL thumbprint of the vCenter host:
+
[source,terminal]
----
$ openssl s_client \
    -connect <vcenter_host>:443 \ <1>
    < /dev/null 2>/dev/null \
    | openssl x509 -fingerprint -noout -in /dev/stdin \
    | cut -d '=' -f 2
----
<1> Specify the vCenter host name.
+
.Example output
+
[source,terminal]
----
01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF:01:23:45:67
----

. Create a `Secret` CR for the VMware provider:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: vmware-secret
  namespace: {namespace}
type: Opaque
stringData:
  user: <user_name> <1>
  password: <password> <2>
  thumbprint: <vcenter_thumbprint> <3>
EOF
----
<1> Specify the vCenter administrator account, for example, `administrator@vsphere.local`.
<2> Specify the vCenter password.
<3> Specify the SSL thumbprint of the vCenter host.

. Create a `Provider` CR for the VMware provider:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Provider
metadata:
  name: vmware-provider
  namespace: source-namespace
spec:
  type: vsphere
  url: <api_end_point> <1>
  secret:
    name: <vmware-secret> <2>
    namespace: {namespace}
EOF
----
<1> Specify the vSphere API end point, for example, `https://vcenter.host.com/sdk`.
<2> Specify the VMware `Secret` CR name.

. Create a `Plan` CR for the migration:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: migration-plan
  namespace: {namespace}
spec:
  provider:
    source:
      name: vmware-provider
      namespace: source-namespace
    destination:
      name: <target_cluster> <1>
      namespace: <target_namespace> <2>
  map:
    networks:
      - source:
          id: <network_ref> <3>
        destination:
          type: pod
          name: pod
          namespace: <target_namespace> <4>
    datastores:
      - source: <5>
          id: <datastore_ref> <6>
        destination:
          storageClass: standard
  vms:
    - id: <vm_ref_or_name> <7>
EOF
----
<1> Specify the target cluster.
<2> Specify the target namespace.
<3> Specify the managed object reference of one or more VMware networks.
<4> Specify the target namespace.
<5> Specify one or more VMware data stores to map to the target data store.
<6> Specify the managed object reference of the data store.
<7> Specify the managed object reference or the names of one or more VMware VMs.

. Create a `Migration` CR to run the `Plan` CR:
+
[source,terminal,subs="attributes+"]
----
$ cat << EOF | oc apply -f -
apiVersion: virt.konveyor.io/v1alpha1
kind: Migration
metadata:
  name: migration-001
  namespace: {namespace}
spec:
  plan:
    name: test-migration-plan
    namespace: {namespace}
EOF
----
+
The `Migration` CR creates a `VirtualMachineImport` CR for each VM that is migrated.

. Monitor the progress of the migration by viewing the `VirtualMachineImport` pods:
+
[source,terminal,subs="attributes+"]
----
$ oc get pods -n {namespace}
----
