// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="mtv-workflow_{context}"]
= {project-full}  workflow

You can migrate virtual machines (VMs) using the {project-short} console or the command line.

The following diagram is a high-level view of the migration workflow.

ifeval::["{build}" == "downstream"]
.{project-short} workflow
image::136_OpenShift_Migration_Toolkit_0121_mtv-workflow.svg[{project-short} workflow]
endif::[]

ifeval::["{build}" == "upstream"]
.{project-short} workflow
image::136_Upstream_Migration_Toolkit_0121_mtv-workflow.svg[{project-short} workflow]
endif::[]

The {project-short} workflow comprises the following steps:

. You create a source provider, a target provider, a network mapping, and a storage mapping.
. You create a migration plan that includes the following resources:
* Source provider
* Target provider
* Network mapping
* Storage mapping
* One or more VMs

. You run a migration plan by creating a `Migration` CR that references the migration plan. If a migration is incomplete, you can run a migration plan multiple times until all VMs are migrated.
. For each VM in the migration plan, the _Migration Controller_ creates a `VirtualMachineImport` CR and monitors its status. When all VMs have been migrated, the Migration Controller sets the status of the migration plan to `Completed`. The power state of a source VM is maintained after migration.
