// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/master.adoc

[id="selecting-migration-network-for-virt-provider_{context}"]
= Selecting a migration network for {a-virt} provider

You can select a default migration network for {a-virt} provider in the {project-short} web console to improve performance. The default migration network is used to transfer disks to the namespaces in which it is configured.

If you do not select a migration network, the default migration network is the `pod` network, which might not be optimal for disk transfer.

[NOTE]
====
You can override the default migration network of the provider by selecting a different network when you create a migration plan.
====

.Procedure

. In the {project-short} web console, click *Providers*.
. Click *{virt}*.
. Select a provider and click *Select migration network*.
. Select a network from the list of available networks and click *Select*.
. Click the network number in the *Networks* column beside the provider to verify that the selected network is the default migration network.
