// Module included in the following assemblies:
//
// * documentation/doc-Forklift/assemblies/assembly_installing-mtv.adoc
// * documentation/doc-Migration_Toolkit_for_Virtualization/assemblies/assembly_installing-mtv.adoc

[id="adding-vddk-to-mtv_{context}"]
= Adding a VDDK image to {project-short}

You can create a VDDK image and store it in a private image registry. Then, you can add the image to the `v2v-vmware` ConfigMap.

[NOTE]
====
Storing the VDDK image in a public registry might violate the terms of the VMware license.
====

[discrete]
== Prerequisites

* An internal link:https://docs.openshift.com/container-platform/{ocp-version}/registry/configuring_registry_storage/configuring-registry-storage-baremetal.html[{ocp} image registry] or a secure link:https://docs.openshift.com/container-platform/{ocp-version}/registry/registry-options.html[external registry]
* Access to the image registry from your {virt} environment
* Podman installed

[discrete]
== Procedure

. Create and navigate to a temporary directory:
+
[source,terminal]
----
$ mkdir /tmp/<dir_name> && cd /tmp/<dir_name>
----

. In a browser, navigate to link:https://code.vmware.com/home[VMware code] and click *SDKs*.
. In the *Compute Virtualization* section, click *Virtual Disk Development Kit (VDDK)*.
. Select the VDDK version that corresponds to your VMware vSphere version, for example, VDDK 7.0 for vSphere 7.0.
. Click *Download* and save the VDDK archive in the temporary directory.
. Extract the VDDK archive:
+
[source,terminal]
----
$ tar -xzf VMware-vix-disklib-<version>.x86_64.tar.gz
----

. Create a `Dockerfile`:
+
[source,terminal]
----
$ cat > Dockerfile <<EOF
FROM busybox:latest
COPY vmware-vix-disklib-distrib /vmware-vix-disklib-distrib
RUN mkdir -p /opt
ENTRYPOINT ["cp", "-r", "/vmware-vix-disklib-distrib", "/opt"]
EOF
----

. Build the image:
+
[source,terminal]
----
$ podman build . -t <registry_route_or_server_path>/vddk:<tag> <1>
----
<1> Specify your image registry:
+
* For an internal {ocp} registry, specify the internal registry route, for example, `image-registry.openshift-image-registry.svc:5000/openshift/vddk:<tag>`.
* For an external registry, specify the server name, path, and tag, for example, `server.example.com:5000/vddk:<tag>`.

. Push the image to the registry:
+
[source,terminal]
----
$ podman push <registry_route_or_server_path>/vddk:<tag>
----

. Edit the `v2v-vmware` ConfigMap in the *openshift-cnv* project:
+
[source,terminal]
----
$ oc edit configmap v2v-vmware -n openshift-cnv
----

. Add the `vddk-init-image` parameter to the `data` stanza:
+
[source,yaml]
----
...
data:
  vddk-init-image: <registry_route_or_server_path>/vddk:<tag>
----
