// Module included in the following assemblies:
//
// * documentation/doc-Migration_Toolkit_for_Virtualization/assemblies/assembly_migrating-vms-web-console.adoc
// * documentation/doc-Forklift/assemblies/assembly_migrating-vms-web-console.adoc

[id="running-migration-plan_{context}"]
= Running a migration plan

You can run a migration plan and view its progress in the web console.

.Prerequisites

* The VMware VMs must be powered off.

.Procedure

. In the web console, navigate to *Migration plans*.
+
The *Migration plans* list displays the source and target providers, the number of VMs being migrated, the status of the plan, and a high-level progress bar that shows how many VMs have been migrated.

. Click *Start* beside a migration plan with a *Ready* status to run the plan.
. To view the *Migration Details by VM* screen, click the name of a migration plan.
+
This screen displays the migration start and end time, the amount of data copied, and a progress pipeline for each VM being migrated.

. Expand a VM to view the migration steps, elapsed time of each step, and the state.
