:_mod-docs-content-type: ASSEMBLY

[id="assembly_live-migration_{context}"]
= Live migration in {project-short} 

//:context: cold-warm-migration

[role="_abstract"]
Live migration enables you to migrate VMs between {virt} clusters or namespaces with minimal downtime. This feature requires {project-first} 2.10.0 or later and {virt} 4.20 or later on both source and target clusters.

[IMPORTANT]
====
Live migration is a Technology Preview feature only. Technology Preview features
are not supported with Red Hat production service level agreements (SLAs) and
might not be functionally complete. Red Hat does not recommend using them
in production. These features provide early access to upcoming product
features, enabling customers to test functionality and provide feedback during
the development process.
For more information about the support scope of Red Hat Technology Preview
features, see https://access.redhat.com/support/offerings/techpreview/.
====

include::../modules/benefits-live-migration.adoc[leveloffset=+1]

include::../modules/live-migration-mtv-cnv.adoc[leveloffset=+1]

include::../modules/live-migration-limitations.adoc[leveloffset=+1]

include::../modules/live-migration-workflow.adoc[leveloffset=+1]


ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]