
ifdef::context[:parent-context: {context}]

:_mod-docs-content-type: ASSEMBLY

[id="assembly_planning-migration-aws_{context}"]

= Planning a migration of virtual machines from {aws} {ec2}

//:context: planning-aws

[IMPORTANT]
====
Importing VMs from Amazon {ec2} is Technology Preview software only. Technology Preview features are not supported with Red{nbsp}Hat production service level agreements (SLAs) and might not be functionally complete. Red{nbsp}Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red{nbsp}Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

[role="_abstract"]
Create an {aws} {ec2} migration plan by setting up network maps, storage maps, and configuring source and destination providers in the {project-first} UI.

{aws} {ec2} migration supports cold migration only to Red Hat OpenShift Service on {aws} ({rosa}) or OpenShift Dedicated (OSD) on {aws} clusters.

:context: aws
:aws:

include::../modules/ref_aws-ec2-prerequisites.adoc[leveloffset=+1]

include::../modules/ref_aws-ec2-limitations.adoc[leveloffset=+1]

include::../modules/proc_creating-form-based-network-maps-ui-aws.adoc[leveloffset=+1]

include::../modules/proc_creating-form-based-storage-maps-ui-aws.adoc[leveloffset=+1]

include::../modules/proc_adding-source-provider.adoc[leveloffset=+1]

:!aws:
:context: dest_aws
:dest_aws:

include::../modules/proc_adding-source-provider.adoc[leveloffset=+1]

include::../modules/proc_selecting-migration-network-for-virt-provider.adoc[leveloffset=+1]

:!dest_aws:
:context: aws
:aws:

include::../modules/proc_creating-plan-wizard-aws.adoc[leveloffset=+1]

:!aws:

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]




