include::modules/common-attributes.adoc[]
[id="{rn-title}_{context}"]
= {rn-title}

:toc:
:toclevels: 3
:compat-mode:
:context: release-notes

ifeval::["{build}" == "downstream"]
include::modules/making-open-source-more-inclusive.adoc[]
endif::[]

== {project-full} {project-version} release notes

{the} {project-first} enables you to migrate virtual machines from VMware vSphere to {virt}, an add-on to {ocp} {ocp-version}. With {virt}, you can run and manage virtual machine workloads alongside container workloads.

[id="new-features-and-enhancements_{context}"]
=== New features and enhancements

This release adds the following features and improvements.

[id="warm-migration_{context}"]
==== Warm migration

Warm migration reduces downtime by copying most of the VM data during a precopy stage while the VMs are running. During the cutover stage, the VMs are stopped and the rest of the data is copied.

[id="cancel-migration_{context}"]
==== Cancel migration

You can cancel an entire migration plan or individual VMs while a migration is in progress. A canceled migration plan can be restarted in order to migrate the remaining VMs.

[id="select-migration-network_{context}"]
==== Migration network

You can select a migration network for the source and target providers for improved performance. By default, data is copied using the VMware administration network and the {ocp} pod network.

[id="validation-service_{context}"]
==== Validation service

The validation service checks source VMs for issues that might affect migration and flags the VMs with concerns in the migration plan.

ifeval::["{build}" == "downstream"]
:FeatureName: The validation service
include::modules/technology-preview.adoc[leveloffset=+1]
endif::[]
